= Client Settings

You may adjust some settings on the [.api]`Cluster` and [.api]`Bucket` objects.
Settings set on a [.api]`Cluster` object applies to any subsequently created [.api]`Bucket` objects (though not on ones created before the setting was modified).

Some settings are:

* [.api]`Cluster.SetConnectTimeout` - sets the time the client will block on a single [.api]`Cluster.OpenBucket` call
* [.api]`Cluster.SetServerConnectTimeout` - The connect timeout per-server, if multiple servers are passed, indicates how long the SDK should wait for each of them to connect.
* [.api]`Cluster.SetN1qlTimeout`, [.api]`Bucket.SetN1qlTimeout` - sets the timeout for N1QL queries.
You can also modify the N1QL timeout on a per-query basis.
* [.api]`Bucket.SetOperationTimeout` - sets the timeout for document (KV) operations such as [.api]`Bucket.Get` and [.api]`Bucket.Upsert`
* [.api]`Bucket.SetDurabilityTimeout` - sets the timeout for durability operations, indicating how long the SDK should wait for durability criteria should be satisfied before failing the operation.
