= Compatibility of Couchbase Features, Couchbase Versions and the Couchbase Go SDK
:navtitle: Compatibility

[abstract]
Compatibility Information for the Couchbase Go SDK

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Go SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Couchbase Go SDK and Couchbase Server Compatibility Version Matrix
[#table_sdk_versions]
|===
| _CB/SDK_ | *SDK 1.0* | *SDK 1.1 & 1.2* | *SDK 1.3*

| *CB 3.1*
| *◎*
| *✔*
| *✔*

| *CB 4.0 - 4.6*
| *✔*
| *✔*
| *✔*

| *CB 5.0 - 5.1*
| *✔*
| *✔*
| *✔*
|===

== Couchbase Feature Availability Matrix

.Couchbase Go SDK and Couchbase Server Feature Availability Matrix
|===
| Server → | 2.0 | 2.5 | 3.0 | 3.1 | 4.0 | 4.1 | 4.5 | 4.6 | 5.0

10+| *Basic Features*

| CRUD Operations
9+| Go SDK 1.0

| View Querying APIs
9+| Go SDK 1.0

| Geospatial Views
3+| Not Supported
6+| Since Go SDK 1.0

10+| *Advanced Features*

| Durability Requirements
9+| Since Go SDK 1.0

| Carrier Publication Configuration
2+| Not Supported
7+| Since Go SDK 1.0

| SSL Connectivity
3+| Not Supported
6+| Since Go SDK 1.0.5

| Bulk Operations
9+| Since Go SDK 1.0

| N1QL Querying
4+| Not Supported
5+| Since Go SDK 1.0

| Multi-Dimensional Scaling
4+| Not Supported
5+| Since Go SDK 1.0

| Sub-document API
6+| Not Supported
3+| Since Go SDK 1.1

| Fulltext Search
6+| Not Supported
3+| Since Go SDK 1.1

| Extended Attributes
8+| Not Supported
| Since Go SDK 1.2.1

10+| *Administrative Features*

| Administrative API
9+| Since Go SDK 1.0

| RBAC
8+| Not Supported
| Since Go SDK 1.2.3
|===

== Couchbase Go SDK

The Couchbase Go SDK is installed and managed using gopkg, in accordance with established best practices within the Go Community.
As a result, specific versions are installed within a specific developer environment.
The SDK follows http://semver.org/[Semantic Versioning^] and typically release an update of the SDK the third Tuesday of each month.
In order to update your specific developer environment to this new version, you will have to instruct Go to `go get` that specific version.
For further information, please reference the section on installation.

include::5.1@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
