= Compatibility of Couchbase Features, Couchbase Versions and the Couchbase Go SDK
:navtitle: Compatibility
:page-aliases: overview,migrate,project-docs:compatibility,project-docs:integrations

[abstract]
Compatibility Information for the Couchbase Go SDK

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Go SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25,20,20,25"]
|===
| | SDK 1.1, 1.2 | SDK 1.3 | SDK 1.4 | SDK 1.5, 1.6

| *Server 4.0-4.5*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 4.6*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 5.0-5.5*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 6.0*
| *✖*
| *✔*
| *✔*
| *✔*

| *Server 6.5*
| *✖*
| *✖*
| *✖*
| *✔*
|===


Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

== Couchbase Feature Availability Matrix

To take advantage of all features offered by Couchbase Server, you need to know what version of the Go SDK provides compatibility for the features you want to use.
The following matrix shows which versions of the Couchbase Go SDK support the major features of each version of Couchbase Server.

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells] 
[cols="<25,.^23,.^24,.^18,.^19"]
|===
| | Server 4.0, 4.1 | Server 4.5, 4.6 | Server 5.x | Server 6.0, 6.5

5+| *Basic Features*

| CRUD Operations
4+| All Versions

| View Querying APIs
4+| All Versions

| Geospatial Views
4+| All Versions

5+| *Advanced Features*

| Durability Requirements
4+| All Versions

| Carrier Publication Configuration
4+| All Versions

| SSL Connectivity
4+| All Versions

| Bulk Operations
4+| All Versions

| N1QL Querying
4+| All Versions

| Multi-Dimensional Scaling
4+| All Versions

| Sub-document API
4+| Since 1.1

| Full Text Search
| Since 1.1 (Experimental)
3+| Since 1.2

| Global Secondary Indexes (GSI)
4+| All Versions

| Memory Optimized Indexes (MOI)
| Not Supported
3+| All SDK versions

| Plasma Storage for Indexes
2+| Not Supported
2+| All SDK versions

| FTS Index Management from the SDK
2+| Not Supported
2+| Since 1.1

| Data Structures
| Not Supported
3+| Since 1.1

| Extended Attributes
2+| Not Supported
2+| Since 1.2.1

| RBAC
2+| Not Supported
2+| Since 1.2.3

| Analytics
2+| Not supported
| DP in 5.5 with 1.4
| Since 1.5

5+| *Administrative Features*

| Administrative API
4+| All Versions
|===

IMPORTANT: With xref:sdk-authentication-overview.adoc[RBAC], in Couchbase Server 5.0, authentication will depend upon access privileges, and upgrading to 5.0 with existing buckets, or upgrading Server, will require taking these changes into account.

== Couchbase Go SDK

The Couchbase Go SDK is installed and managed using gopkg, in accordance with established best practices within the Go Community.
As a result, specific versions are installed within a specific developer environment.
The SDK follows http://semver.org/[Semantic Versioning^] and typically release an update of the SDK the third Tuesday of each month.
In order to update your specific developer environment to this new version, you will have to instruct Go to `go get` that specific version.
For further information, please reference the section on installation.

include::6.0@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
