= Working with documents
:page-topic-type: concept

[abstract]
This topic covers the basic CRUD operations of creating, retrieving, updating, and deleting documents.
It also describes how to do bulk operations and atomic operations.

Operations use basic Go data types and JSON marshaling functionality.

== Data types

All Go data types that can be serialized via the JSON encoding library are supported by default.
Recursive structures cannot be serialized.
All textual data is represented by UTF-8 when stored in Couchbase Server.
You may alternatively implement your transcoders that modify the method by which your documents are serialized to Couchbase.

The following is an example of a transcoder that will transcode all documents as UTF-8 encoded JSON documents.

[source,go]
----
package main

    import (
    "github.com/couchbaselabs/gocb"
    "encoding/json"
    )

    type TestTranscoder struct {
    }

    func (t TestTranscoder) Decode(bytes []byte, flags uint32, out interface{}) error {
    err := json.Unmarshal(bytes, &out)
    if err != nil {
    return err
    }
    return nil
    }

    func (t TestTranscoder) Encode(value interface{}) ([]byte, uint32, error) {
    bytes, err := json.Marshal(value)
    if err != nil {
    return nil, 0, err
    }
    return bytes, 0, nil
    }

    func main() {
    myCluster := gocb.Connect("couchbase://127.0.0.1")
    myBucket := myCluster.OpenBucket("default", "")
    myBucket.SetTranscoder(TestTranscoder{})
    }
----

== Return Values

The Go SDK uses the typical Go pattern of multiple return values, where the last value is an error interface value.
All Go SDK methods follow this pattern.
In addition to this, methods which perform JSON marshalling may return values through a `ValuePtr` parameter of type `interface{}`.
