= Failure Considerations for the Go SDK in Couchbase
:navtitle: Failure Considerations
:page-aliases: concept-docs:durability-replication-failure-considerations.adoc

include::6.0@sdk:shared:partial$env-errors.adoc[tag=failover_definition]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=what_to_expect_in_application]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=what_to_expect_during_failover]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=missing-nodes]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=timeouts]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=network_failures]

[#devguide-replica-read]
== Reading from replicas

High-availability applications can read documents from replicas, exchanging consistency for availability.

If your bucket is configured for replication, then multiple replicas of each item exist within the cluster.
By default the client will attempt to access an item using its computed master or active node.
This returns the current and authoritative version of the item as it is stored within Couchbase.

In conditions where access to the active node is unavailable (for example, it is disconnected from the network), an application may be able to access a replica version of the item using the _get-from-replica_ operation which queries a replica node for a copy of the item.

NOTE: The item received from a replica node may be an older version.
It is possible a newer version exists in the active node, but did not manage to get replicated before the active node went offline.

[source,go]
----
var value interface
cas, err := bucket.Get("key", &value)
if err != nil {
    cas, err = bucket.GetReplica("key", &value, 0)
}
----

If the third parameter to [.api]`GetReplica` is greater than zero then only that specific replica will be queried.
Otherwise, a request will be sent to all replicas.
Once the SDK receives a successful response from a replica then it will attempt to cancel all other requests and, once all requests are cancelled, assign the value from the successful response.
If no successful response is received then an [.api]`ErrNoReplicas` error will be returned.
As the value is assigned from the first successful response this means that only one value will be assigned to the value pointer.
