= Handling errors
:page-topic-type: concept

[abstract]
All asynchronous methods within the SDK utilize the Node.js standard.

All methods within the SDK, which are capable of returning errors, utilize the Go standard of returning an error object as the last return value.
The easiest way to test for specific errors with the SDK is to test directly the error objects returned by a method with the set of `Err` constants (ex: ErrKeyNotFound or ErrKeyAlreadyExists) which are exported by the SDK.

In addition to doing a direct comparison with errors, you may also use interface testing to check for a particular error category.
For instance, you could check for any error which is a temporary condition with the following code:

[source,go]
----
```go
func isTemporaryError(err error) bool {
te, ok := err.(interface
{ Temporary() bool }
)
return ok :& :& te.Temporary()
}
```
----

The most common errors that occur are errors relating to keys existing when they shouldn't or not existing when they should.
In addition to these common errors, connection or timeout related errors might occur.
For more information about these, see xref:handling-timeouts.adoc[Handling timeouts.]
