= Hello Couchbase example
:page-topic-type: concept

[abstract]
The first code example is a `Hello Couchbase` app.

This example works with the `beer-sample` bucket that is provided with Couchbase Server.
The following sections contain instructions for running the example app and the annotated `Hello Couchbase` code.

== Running Hello Couchbase

To run the example Hello Couchbase program:

. Start Couchbase Server on your computer.
. Open the Couchbase administrator console.
. Make sure the `beer-sample` bucket is available by checking for it under the [.ui]*Data Buckets* tab.
If you need to install the bucket:
 .. Select menu:Settings[Sample Buckets].
 .. Install the `beer-sample` bucket.
. Run the hello-world Go code.

== Hello Couchbase code

The Hello Couchbase example consists of a single file.
The code opens a connection to Couchbase Server, retrieves a document, modifies the document, and stores the updated document in the database.
Here's the code:

[source,go]
----
package main

import (
"gopkg.in/couchbase/gocb.v1"
)

func main() {
   myCluster, _ := gocb.Connect("couchbase://127.0.0.1")
   myBucket, _ := myCluster.OpenBucket("beer-sample", "")

   var beer map[string]interface{}
   cas, _ := myBucket.Get("aass_brewery-juleol", &beer)

   beer["comment"] = "Random beer from Norway"

   myBucket.Replace("aass_brewery-juleol", &beer, cas, 0)
}
----

The following points explain each step in the example:

* _Connecting_
+
A `Bucket` object represents a connection to a single bucket within the cluster.
+
A bucket represents a logical namespace for a key.
All keys must be unique within a single bucket, but multiple buckets can have keys with the same names, and they will not conflict.
A new connection object must be created for each bucket that you want to interact with in your application.
This example creates one connection to the `beer-sample` bucket.
+
The gocb `Connect()` method is passed the cluster connection string, which specifies the nodes in your cluster.
You subsequently use the `OpenBucket()` method to acquire a Bucket instance.
In this case, we connect to the local cluster instance, and the bucket named `beer-sample` bucket.

* _Retrieving Data_
+
The `Get()` method initiates a request to retrieve the specified key.
If the key exists, the result consists of the documents value and CAS.
If the key does not exist on the server, and error will be returned, and a CAS of 0.

* _Storing Data_
+
To store documents in the server, you can use one of the storage methods which consists of `Insert()`, `Upsert()` and `Replace()`.
This example uses the `Replace()` method, which enforces the constraint that a previous value of the document must already exist.
This can be thought of as an update operation in terms of CRUD (create, read, update, delete) operations.
+
The storage methods also return meta-data about the document that was stored, namely the new CAS.
