= Managing Clusters Using the Go SDK with Couchbase Server
:navtitle: Managing Clusters

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Go SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the Go SDK may be performed through several interfaces depending on the object:

* [.api]`ClusterManager` interface (obtained via [.api]`Cluster.Manager(username, password string)`) (administrative username and password).
* [.api]`BucketManager` interface (obtained via [.api]`Bucket.Manager(username, password string)`) (cluster or bucket credentials).

[#go-creating-and-removing-buckets]
== Creating and Removing Buckets

The [.api]`ClusterManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the [.api]``Cluster``'s [.api]`Manager` method, providing the administrative username and password.

[source,go]
----
myCluster, _ := gocb.Connect("couchbase://localhost")
clusterManager = myCluster.Manager("Administrator", "123456")
----

To create a bucket, use the [.api]``ClusterManager``'s [.api]`InsertBucket(settings *BucketSettings)` method.
The [.api]`BucketSettings` struct is also used to expose information about existing buckets ([.api]`ClusterManager.GetBuckets()` returns a slice of settings) or to update an existing bucket ([.api]`ClusterManager.UpdateBucket(settings *BucketSettings)`).

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Only [.param]`name` and [.param]`type` parameters are mandatory for the [.api]`BucketSettings`.
Here is the list of parameters available:

* [.param]`Name`: The name of the bucket (mandatory to create one, cannot be updated).
* [.param]`Type`: The type of the bucket (mandatory to create one, cannot be changed).
Defaults to `BucketType.Couchbase`, but can also be `BucketType.Memcached` to create a cache bucket.
* [.param]`Quota`: How much memory should each node use for the bucket.
This number is specified in megabytes.
* [.param]`Password`: If specified, makes this bucket password protected, forcing future connects (using the [.api]`Bucket`) interface to specify the [.param]`password` parameter.
* [.param]`FlushEnabled`: Enables the [.api]`BucketManager#flush()` operation to be performed on this bucket (see the <<go-flushing>> section below).
* [.param]`Replicas`: The number of replicas to use for the bucket.
* [.param]`IndexReplicas`: Wether or not to replicate indexes.

The following example updates an existing "hello" bucket (notice how all parameters are set):

[source,go]
----
bucketSettings := BucketSettings {
        FlushEnabled: true,
        IndexReplicas: true,
        Name: "hello",
        Password: "",
        Quota: 120,
        Replicas: 1,
        Type: BucketType.Couchbase
}

manager := cluster.Manager("Administrator", "123456")
err := manager.UpdateBucket(bucketSettings)
----

Once you no longer need to use the bucket, you may delete the bucket using the [.api]`ClusterManager.RemoveBucket(name string)` method:

[source,go]
----
clusterManager.RemoveBucket("hello");
----

[#go-flushing]
== Flushing Buckets

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You may flush a bucket in the Go SDK by using the [.api]`BucketManager.Flush()` method (for an example of connecting to the `BucketManager`, see the _Index Management_ section below).

The [.api]`flush` operation may fail if the bucket does not have flush enabled:

[source,json]
----
{
    "_": "Flush is disabled for the bucket"
}
----

[#go-index-management]
== Index Management

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=index-management]

You can manage indexes in the Go SDK using the [.api]`BucketManager` interface, with its various N1QL related methods: [.api]`GetIndexes()`, [.api]`+CreateIndex(...)+`, etc\...

The following example creates a N1QL secondary index named "fooBar" on the "test" bucket, indexing fields "foo" and "bar":

[source,go]
----
myCluster, _ := gocb.Connect("couchbase://localhost")
testBucket, _ := myCluster.OpenBucket("test")
testManager := testBucket.Manager(username, password)

//true, false at the end: ignore errors if the index exists, don't defer the creation
testManager.CreateIndex("fooBar", string[]{ "foo", "bar" }, true, false);
----

[#go-view-management]
== View Management

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the Go SDK, design documents are represented by the `DesignDocument` and `View` structs.
All operations on design documents are performed on a `BucketManager` instance.

To inspect design documents, you can either retrieve them by name (`bucketManager.GetDesignDocument("landmarks")`) or iterate through a slice of documents (`bucketManager.GetDesignDocuments()`).

To create or update design documents, use the [.api]`InsertDesignDocument(ddoc *DesignDocument)` and [.api]`UpsertDesignDocument(ddoc *DesignDocument)` methods.

The following example inserts a design document with two regular views and one spatial view into a bucket named `travel-sample`:

[source,go]
----
//(note: obtaining the bucketManager is omitted in this snippet)
// Initialize design document
designDoc := DesignDocument {
        Name: "landmarks",
        Views: map[string]View {
                "by_country": View {
                        Map: "function (doc, meta) { if (doc.type == 'landmark') { emit([doc.country, doc.city], null); } }",
                        Reduce: nil
                },
                "by_activity": View {
                        Map: "function (doc, meta) { if (doc.type == 'landmark') { emit(doc.activity, null); } }",
                        Reduce: "_count"
                }
        },
        SpatialViews: map[string]View {
                "by_coordinates": View {
                        Map: "function (doc, meta) { if (doc.type == 'landmark') { emit([doc.geo.lon, doc.geo.lat], null); } }",
                        Reduce: nil
                }
        }
}

// Insert design document into the bucket
bucketManager.InsertDesignDocument(designDoc)
----

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

[source,go]
----
//(note: obtaining the bucketManager is omitted in this snippet)
// Get design document to be updated
designDoc := bucketManager.GetDesignDocument("landmarks")

// Update the "by_country" view, adding a reduce
designDoc.Views["by_country"] := View { //reuse same name
        Map: "function (doc, meta) { if (doc.type == 'landmark') { emit([doc.country, doc.city], null); } }", //same map function
        Reduce: "_count" //added reduce function
}

// Resend to server
bucketManager.UpsertDesignDocument(designDoc)
----

To remove a design document from a bucket, pass its name to the `RemoveDesignDocument` method.
