= Managing Connections Using the Go SDK with Couchbase Server
:navtitle: Managing Connections
:page-topic-type: concept

[abstract]
This section describes how to connect the Go SDK to a Couchbase cluster and bucket.
It contains best practices as well as information on the connection string,  SSL and other advanced connection options.

== Creating a Cluster Object

The [.api]`Cluster` object serves as an organizational unit for any [.api]`Bucket` objects created.
As on the server each bucket is a member of a cluster, likewise in the SDK each [.api]`Bucket` object is a child of a [.api]`Cluster`.
To create a cluster, construct it using a _connection string_, specifying the scheme and host(s) to connect to [.api]`gocb.Connect`:

[source,go]
----
cluster, err := gocb.Connect("couchbase://localhost")
----

You can also specify multiple hosts in the connection string by separating each host with a comma:

[source,go]
----
cluster, err := gocb.Connect("couchbase://host1,host2,host3,hostN")
----

Specifying multiple hosts may add xref:failure-considerations.adoc[additional redundancy] when bootstrapping.

[NOTE]
====
From Couchbase Go SDK 1.4.0, [.api]`AlternateAddress` is implemented, for connecting to nodes in a NATed environment, such as Docker containers using portmapping. It is on by default, if the server provides a topology that includes a multi-network configuration. Whichever network is selected at bootstrap will be logged.

Note that any SSL/TLS certificates must be set up at the point where the connections are being made.  The Couchbase SDKs will honor any valid SSL/TLS certificates.
====

== Authenticating

From Couchbase Server 5.0, you will need to authenticate the user, rather than against the bucket, as part of xref:6.0@server:learn:security/authorization-overview.adoc[Role-Based Access Control].
You will need to use `PasswordAuthenticator`:

[source,go]
----
cluster.Authenticate(gocb.PasswordAuthenticator{
     Username: username,
     Password: password,
 })
----

== Opening a Bucket

Once the [.api]`Cluster` object has been created, you may open one or more [.api]`Bucket` objects using [.api]`Cluster.OpenBucket`.
The first argument is the bucket name to use, and the second is the bucket password - which should be provided if the bucket is password protected, or supplied as `nil` otherwise.

[source,go]
----
bucket1, err := cluster.OpenBucket("messages", nil)
protectedBucket, err := cluster.OpenBucket("protected", "s3cr3t")
----

Note that the bucket password is _not_ the administrative password used to access the Couchbase Web UI.

Once the bucket has been created, it may be used throughout your application.
Buckets are thread-safe and need not be locked or otherwise protected to be used from multiple threads.

You should only need to open one [.api]`Bucket` object for each Couchbase Bucket in your application, and you should attempt to keep the [.api]`Bucket` object available and open for as long as you plan to access Couchbase within your application.

include::6.0@sdk:pages:partial$max-connections.adoc[tag=limits]

== Closing a Bucket

When your application is done talking to Couchbase, you can issue the [.api]`Bucket.Close()` call on the bucket, which will disconnect your application from the given bucket.

[#ssl]
== Configuring SSL

WARNING: Be aware that certificate validation when connecting to Couchbase using SSL requires Go 1.6+ and gocb 1.2+.
Otherwise SSL connections are subject to https://en.wikipedia.org/wiki/Man-in-the-middle_attack[man-in-the-middle^] attacks.

To configure SSL, pass an SSL scheme with your connection string when creating your cluster object.

[source,go]
----
myCluster, _ := gocb.Connect("couchbases://10.1.1.1")
myBucket, _ := myCluster.OpenBucket("default", "")
----

include::6.0@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]

To use DNS SRV in the Go SDK, simply pass the single bootstrap node (in this case `couchbase://example.com`).
DNS SRV lookup will not be performed if there is more than a single node in the bootstrap list.
