= Non-JSON Documents
:page-aliases: concept-docs:nonjson,howtos:transcoders-nonjson

// tag::nonjson_intro[]
[abstract]
Couchbase is a document database and functions best when document contents are JSON.
Nevertheless Couchbase may be used to store non-JSON data for various use cases.
This page discusses how to use Couchbase with non-JSON documents, including strings and binary-data.

Non-JSON formats may be more efficient in terms of memory and processing power (for example, if storing only flat strings, JSON adds an additional syntactical overhead of two bytes per string).
Non-JSON documents may be desirable if migrating a legacy application which is using a customized binary format.

Note that only JSON documents can be accessed using Query (N1QL).
Limited support for non-JSON documents is available for MapReduce views.
Additionally, non-JSON documents will not be accessible using the xref:webui-cli-access.adoc[Web UI] (the contents will be shown in their Base64 equivalent).

== Using non-JSON documents

It's important to note that a JSON document can also refer to a simple integer (`42`), string (`"hello"`), array (`[1,2,3]`), boolean (`true`, `false`) and the JSON `null` value.
Nevertheless if your application requires a non-JSON format, the SDK may still support it natively.

If there is no native support for your format, you can write a _transcoder_ which handles the encoding and decoding of your documents to and from the server.

[#devguide_nonjson_itmflags]
== Item flags

Every item (record) in Couchbase contains metadata stored along with it in the server.
One of the metadata fields is a 32 bit "flag" value.

Couchbase SDKs accept native object types (integers, strings, arrays, dictionaries) as valid inputs for a Document and internally convert them to JSON before sending them to the server to be stored.
When the SDK serializes the Document, it notes the type of serialization performed (JSON) and sends a corresponding type code along with the serialized document to the server to be stored.
This type code is stored in the flags field within the item’s metadata.

Later, when retrieving the document from the server, the SDK checks the type code which informs it about the type of serialization used to encode the document, and thus how the SDK should de-serialize the document.

Note that using non-JSON serialization will prevent the document from being accessible via Query and MapReduce.

The table below shows the built-in formats available in most SDKs.
The _name_ column displays the format name; the _native type_ column displays the native language type which is used as input and output for the document, the _description_ contains the properties of such a type, and the _flags value_ contains the actual code used for the format.
The format code is discussed more in depth below.

.Built-in format types
[cols="28,43,88,21"]
|===
| Name | Native Type | Description | Flags value (see below)

| JSON
| Dictionary, Array, Number, String, Integer
| Default serialization.
Serializes document to JSON.
Document can be used with Query
| 0x02 << 24

| STRING
| Unicode or String
| Indicates the document is a UTF-8 string.
This may be more space-efficient than JSON for documents that are a simple string, as JSON requires strings to be encapsulated by quotes.
Using this serialization format may save two bytes for each string value
| 0x04 << 24

| BINARY
| ByteArray, buffer, etc.
| Indicates this value is a raw sequence of bytes.
It is the simplest encoding form and indicates that the application will process and interpret its contents as it sees fit.
| 0x03 << 24

| PRIVATE
| SDK/Language dependent
| This indicates that a language-specific serialization format is being used.
The serialization format depends on the language (for example, Pickle for Python, Marshal for Ruby, Java Serialization for Java, etc).
_Using this format will make your documents inaccessible from other-language SDKs_.
| 0x01 << 24
|===

== Custom formats

If your application must store data that cannot be handled by any of the built-in SDK formats (for example, if the application wishes to store data as UTF-16), there are generally two options:
// end::nonjson_intro[]

== Using the _RAW_ format

Manually serialize your document to a raw buffer, store the document using the _RAW_ format, and manually deserialize your document upon retrieval, reading and decoding the retrieved buffer manually.
Here is an example of manually encoding and decoding a byte string, the Go SDK will treat this as binary data:

[source,golang]
----
byteString := []byte("Hello World!")
_, err := bucket.Upsert("byte_doc", byteString, 0)
if err != nil {
    // error handling
}

var getBytes []byte
_, err = bucket.Get("byte_doc", &getBytes)
if err != nil {
    // error handling
}

fmt.Println(string(getBytes))
----

[#transcoders]
== Using transcoders

NOTE: Not all SDKs support transcoders.
Refer to your SDK documentation to determine whether and how transcoders are supported.

A Transcoder refers to a pair of functions which are responsible for serializing (encoding) a document before sending it to the server and de-serializing (decoding) a document to a suitable application type when it is retrieved.

Using transcoders is preferred over RAW serialization when possible, as it provides a cleaner interface as well as allows it to work in a mixed type environment (if there are multiple custom types) without having to encode the document type within the document itself.

The _encoding_ function in the transcoder accepts an interface as input (as created by your application), encodes it as a byte buffer, and returns the byte buffer along with a type code.

The _decoding_ function accepts a buffer (as fetched from the server) and a type code (the flags from the metadata) and assigns the value into the pointer value within the application.

The following shows an implementation of a transcoder which only supports string or []byte and encodes them with a custom flag:

[source,golang]
----
const customTypecode = 0x0A000000

type CustomTranscoder struct {
}

func (t CustomTranscoder) Decode(bytes []byte, flags uint32, out interface{}) error {
	if flags == customTypecode {
		switch typedOut := out.(type) {
		case *[]byte:
			*typedOut = bytes
			return nil
		case *string:
			*typedOut = string(bytes)
			return nil
		default:
			// return an error as we don't support anything else
		}
	}

	return fmt.Errorf("unsupported flags type")
}

func (t CustomTranscoder) Encode(value interface{}) ([]byte, uint32, error) {
	var bytes []byte

	switch typeValue := value.(type) {
	case []byte:
		bytes = typeValue
	case *[]byte:
		bytes = *typeValue
	case string:
		bytes = []byte(typeValue)
	case *string:
		bytes = []byte(*typeValue)
	default:
		// return an error as we only support string and []byte
	}

	return bytes, customTypecode, nil
}

func transcode() {
	transcoder := CustomTranscoder{}
	bucket.SetTranscoder(transcoder)
	_, err = bucket.Upsert("transcoded", "Transcoded string", 0)
	if err != nil {
		panic(err)
	}

	var transcodedString string
	_, err = bucket.Get("transcoded", &transcodedString)
	if err != nil {
		panic(err)
	}

	fmt.Println(transcodedString)
}
----

// tag::nonjson_flags[]
== Format flags (type codes) and SDK interoperability

Modern Couchbase SDKs have standardized type codes for the various built-in document formats.
This has not always been the case however, and older, legacy SDKs would use different flag values for typecodes (so for example, the code for a string value could be 100 or 4 depending on the SDK used).

In order to remain backwards-compatible with legacy SDKs and to retain interoperability with current SDKs, the standard typecodes follow the following format.
Note that typecodes are stored under the flags field in the server’s metadata, which is a 32 bit field.

Current SDKs set the flags value using these two factors:

* The _modern_ or _common_ typecode: This is the modern SDK code for a given type, and is standard across all SDKs.
* The legacy or compat typecode: This is the code which was used by older versions of a given SDK.
It is valid only for that language’s SDK.
It is important to note that all legacy typecodes (regardless of language) are under 24 bits in width.
Legacy SDKs will also often have a mask value (typically no wider than 16 bits).

The resultant typecode (actually stored as the _flags_ value is a bitwise OR of the modern typecode and the legacy typecode.
For example, the older legacy Python code for _JSON_ was `0x00` and the unified typecode for _JSON_ is `0x02`.
The resultant typecode is thus:

....
(0x02 << 24) | (0x00)
0x02000000
....

Another example: The legacy typecode for the _RAW_ format in Python is `0x02`, and the common type code is `0x03`.
The resultant typecode is:

....
(0x03 << 24) | (0x02)
0x03000002
....

When defining a new type code using the transcoder, ensure to keep the above information in mind, so as not to clash with any existing ones.
// end::nonjson_flags[]
