= Overview
:page-topic-type: concept

[abstract]
The Couchbase Go SDK enables you to interact with Couchbase Server from a Go application.

The Go SDK consists of a native Go library along with various other components, including:

* Go Couchbase client
* Developer guide (you're reading it now!)
* API reference
* Sample applications (https://github.com/couchbaselabs/beersample-go[beer database^])

== Architecture

To debug errors, you must be familiar with the client's architecture to understand where problems might originate.
The following components participate in typical operations:

* *Couchbase Server*
+
This is the server itself, which stores your data.
Errors can happen here if your data does not exist, or if there are connectivity issues with one or more nodes in the server.
While Couchbase Server is scalable and fault tolerant, there are naturally some conditions that cause failures (for example, if all nodes are unreachable).

* *gocbcore*
+
This is the core IO handling library powering the Go SDK.
It handles network communication and protocol handling between a client and the Couchbase node.
Network connectivity issues tend to present themselves here.

* *gocb*
+
This is our developer friendly front-end for gocbcore.
It interfaces with gocbcore and handles marshaling of information between your application and the low-level API's available through gocbcore.
It also performs input validation, encoding and decoding of keys and values and provides a synchronous API for use within goroutines.

== Compatibility

To take advantage of all features offered by Couchbase Server, you need to know what version of our Go SDK provides compatibility for the features you want to use.
The following matrix shows which versions of the client support the major features of each version of Couchbase Server.

.Couchbase Server and SDK Supported Version Matrix
|===
| | Server 1.8 | Server 2.0 | Server 2.5 | Server 3.0 | Server 4.0

6+| *Basic Features*

| CRUD Operations
5+| Since 0.1

| View Querying APIs
5+| Since 0.2

6+| *Advanced Features*

| Durability Requirements
5+| Since 0.3

| Fast (CCCP) Bootstrapping
2+| Not Supported
3+| Since 0.1

| SSL Connectivity
3+| Not Supported
2+| Since 0.1

| Transparent Compression
5+| Not Supported

| Bulk Operations
5+| Not Supported

| Cross-SDK Data types
| Not Supported
4+| Since 0.1

| N1QL Querying
5+| Since 0.3

6+| *Administrative Features*

| Administrative API
5+| Since 0.2
|===

== Contributing

Couchbase welcomes community contributions to the Go SDK.
The https://github.com/couchbaselabs/gocb[Go SDK source code^] is available on GitHub.
If you would like to contribute code, read the https://github.com/couchbaselabs/gocb/blob/master/CONTRIBUTING.md[contributor's guide^] for details.
