= Querying buckets
:page-topic-type: concept

[abstract]
You can retrieve sets of information from Couchbase Server by using view queries or N1QL queries.

== Working with view queries

You can use MapReduce views to create queryable secondary indexes in Couchbase Server.

The primary index for documents is the key you use when performing the standard CRUD methods.

The following example queries a `by_name` view in a beer design document.
This view checks whether a document is a beer and has a name.
If it does, it emits the beer's name into the index.
This view allows beers to be queried for by name.
For example, it's now possible to ask the question "What beers start with A?"

[source,javascript]
----
function (doc, meta) {
			if (doc.type && doc.type == "beer" && doc.name) {
			emit(doc.name, null);
			}
			}
----

Querying a view through the Go SDK is performed through the `ViewQuery` interface that is instantiated through the NewViewQuery method of the gocb library.

[source,go]
----
myQuery := gocb.NewViewQuery("beer", "by_name")
----

The `ViewQuery` interface enables you to query the view and specify various available options for the query.
Once you have the query ready for execution, pass it to the `ExecuteViewQuery` method of the your Bucket instance:

[source,go]
----
rows, err := myBucket.ExecuteViewQuery(myQuery)
			if err != nil {
			fmt.Printf("View query error: %s\n", err)
			}

			var row interface{}
			for rows.Next(&row) {
			fmt.Printf("Row: %+v\n", row)
			}
			if err := rows.Close(); err != nil {
			fmt.Printf("View query results error: %s\n", err)
			}
----

You can modify your view results by specifying various options before executing the `query` method.
Here is an example that skips the first six items and limits the results to three items:

[source,go]
----
myQuery = gocb.NewViewQuery("beer", "by_name").Skip(6).Limit(3)
----

== Working with N1QL queries

You can perform Couchbase Query Language (N1QL) queries via the Go SDK.

The following example shows how to send a N1QL query:

[source,go]
----
myQuery := gocb.NewN1qlQuery("SELECT * FROM default")
				rows, err := myBucket.ExecuteN1qlQuery(myQuery)
				if err != nil {
				fmt.Printf("N1QL query error: %s\n", err)
				}

				var row interface{}
				for rows.Next(&row) {
				fmt.Printf("Row: %+v\n", row)
				}
				if err := rows.Close(); err != nil {
				fmt.Printf("N1QL query error: %s\n", err)
				}
----

== Read Your Own Writes (RYOW)

Often you will want to insert or update some data into Couchbase and immediately read this data back using a N1QL query.
This is referred to as read your own write (RYOW).

RYOW can be achieved by using the `consistency` option of the [.api]`N1qlQuery` structure:

[source,go]
----
myQuery := gocb.NewN1qlQuery("SELECT * FROM default")
					myQuery.Consistency(gocb.RequestPlus)

					rows, err := myBucket.ExecuteN1qlQuery(myQuery, nill)
					if err != nil {
					fmt.Printf("N1QL query error: %s\n", err)
					}

					var row interface{}
					for rows.Next(&row) {
					fmt.Printf("Row: %+v\n", row)
					}
					if err := rows.Close(); err != nil {
					fmt.Printf("N1QL query error: %s\n", err)
					}
----
