= Authentication

[abstract]
RBAC requires that users pass appropriate _credentials_ to Couchbase Server in order to access cluster-resources.
The SDK provides enhanced support for the passing of credentials.

include::6.0@sdk:shared:partial$sdk-authentication-overview.adoc[tag=RBAC_and_the_SDK]

include::6.0@sdk:shared:partial$sdk-authentication-overview.adoc[tag=authenticating_with_legacy_sdk_versions]

== Passing Credentials

The most recent versions of the SDK are RBAC-enabled, and provide enhanced support for authentication.
Code examples for Go can be found in xref:start-using-sdk.adoc[Getting Started with the SDK], and also as part of the xref:sdk-user-management-example.adoc[Sample Code] provided to demonstrate user management.

[#go_upgrading_to_rbac_sdk_versions]
== Upgrading to RBAC-Enabled SDK-Versions

The last pre-RBAC version of the Go SDK was 1.1.3.
The first RBAC-enabled version was 1.2.3.
See the SDK link:/server/other-products/release-notes-archives/go-sdk[Release Notes] for more information.

With the most recent versions of the SDK, the legacy authentication interface and the new, optimized authentication interface can both be used: each supports access to buckets on Couchbase Servers whose version is either 5.0 and beyond, or pre-5.0.

== Further Information on RBAC
All aspects of the Couchbase RBAC system are covered in the section xref:6.0@server:learn:security/authorization-overview.adoc[Authorization].
Specifically, for information on:

* Adding _Users_ and assigning _roles_, by means of the Couchbase Web Console, see xref:6.0@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users and Roles].
* _Roles_ required for resource-access, and the privileges they entail, see xref:6.0@server:learn:security/roles.adoc[Roles].
* _Resources_ controlled by Couchbase RBAC, see xref:6.0@server:learn:security/resources-under-access-control.adoc[Resources Under Access Control].

== Certificate-Based Authentication

Couchbase Server supports the use of X.509 certificates to authenticate clients (only available in the Enterprise Edition, not the Community Edition).
This allows authenticated users to access specific resources by means of the data service (no other service is currently available to clients through this form of authentication).

The process relies on a certificate authority, for the issuing of certificates that validate identities.
A certificate includes information such as the name of the entity it identifies, an expiration date, the name of the authority that issued the certificate, and the digital signature of the authority.
A client attempting to access Couchbase Server can present a certificate to the server, allowing the server to check the validity of the certificate.
If the certificate is valid, the user under whose identity the client is running, and the roles assigned that user, are verified.
If the assigned roles are appropriate for the level of access requested to the specified resource, access is granted.

The Go SDK has supported certificate authentication since version 1.3.3.
The client certificate can be generated with the shell script on the xref:c-sdk::sdk-authentication-overview.adoc[C SDK Authentication page].
Connection involves using `gocb.CertAuthenticator{}` to tell the Server that cert-auth is the authenticator, and passing `certpath` and `keypath` in the connection string:

----
cluster, err := gocb.Connect("couchbases://10.0.0.1?certpath=/path/to/chain.pem&keypath=/path/to/client.key")
if err != nil {
    panic(err)
}
cluster.Authenticate(gocb.CertAuthenticator{})
bucket, err := cluster.OpenBucket("travel-sample", "")
if err != nil {
    panic(err)
}
----

NOTE: If the certificate generated does not directly match the host, then the SAN (Subject Alternative Name) field should supply the appropriate names: _gocb_ may fail to authenticate if it can't verify the hostname is valid for the certificate.
Other SDKs' platforms - Java and .NET - are by default less strict on verification of hostnames.
