= Extended Attributes
:page-aliases: concept-docs:sdk-xattr-overview

[abstract]
Extended Attributes (XATTR) are metadata that can be provided on a per-application basis.

include::6.0@sdk:shared:partial$sdk-xattr-overview.adoc[tag=intro_extended_attributes]

include::6.0@sdk:shared:partial$sdk-xattr-overview.adoc[tag=using_extended_attributes]


== Virtual Extended Attributes

_Virtual_ extended attributes consist of metadata on an individual document: this can be retrieved by specifying `$document` as a search-path.
For example:

[source,go]
----
frag, err := bucket.LookupIn("test").Get("$document", gocb.SubdocFlagXattr").Execute()
----

See xref:6.0@server:learn:data/extended-attributes-fundamentals.adoc#virtual-extended-attributes[the Virtual XATTR Section] for more information on the metadata that they expose.

These attributes are generated on-demand to expose storage-level document metadata, such as TTL to expose document expiration.
For TTL using Virtual XATTR, use the following:

[source,go]
----
frag, err := bucket.LookupIn("test").Get("$document.exptime", gocb.SubdocFlagXattr").Execute()
----

See the xref:sdk-xattr-example.adoc#virtual-extended-attributes-example[example page] for a complete code sample.
