= Install and Start Using the Go SDK with Couchbase Server
:navtitle: Start Using the SDK

The Couchbase Go SDK allows you to connect to a Couchbase cluster from Go.
It is a native Go library and uses the high-performance gocbcore to handle communicating to the cluster over Couchbase’s binary protocols

== Installation

You can install the SDK via `go get`

[source,bash]
----
$ go get gopkg.in/couchbase/gocb.v1
----

Information on new features, fixes, known issues as well as information on how to install older release versions is xref:sdk-release-notes.adoc[in the release notes].

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
Currently we support using the Couchbase Go Client with Go releases 1.12 and 1.11.
Older versions may work, but are not supported.

== Hello Couchbase

Once you've installed the SDK you can run this simple code snippet showcasing some of its features.

* Error checking has been omitted for brevity.
* Replace [.in]`localhost` with the IP or hostname of a cluster node, if the host running the example is not also a Couchbase node.

[source,go]
----
package main

import (
	"fmt"
	"gopkg.in/couchbase/gocb.v1"
)

type User struct {
	Id string `json:"uid"`
	Email string `json:"email"`
	Interests []string `json:"interests"`
}

func main() {
        cluster, _ := gocb.Connect("couchbase://localhost")
        cluster.Authenticate(gocb.PasswordAuthenticator{
            Username: "USERNAME",
            Password: "PASSWORD",
        })
        bucket, _ := cluster.OpenBucket("bucketname", "")

        bucket.Manager("", "").CreatePrimaryIndex("", true, false)

        bucket.Upsert("u:kingarthur",
                User{
                        Id: "kingarthur",
                        Email: "kingarthur@couchbase.com",
                        Interests: []string{"Holy Grail", "African Swallows"},
                }, 0)

        // Get the value back
        var inUser User
        bucket.Get("u:kingarthur", &inUser)
        fmt.Printf("User: %v\n", inUser)

        // Use query
        query := gocb.NewN1qlQuery("SELECT * FROM bucketname WHERE $1 IN interests")
        rows, _ := bucket.ExecuteN1qlQuery(query, []interface{}{"African Swallows"})
        var row interface{}
        for rows.Next(&row) {
                fmt.Printf("Row: %v", row)
        }
}
----

The above example demonstrates the xref:core-operations.adoc[upsert, get], and xref:n1ql-query.adoc[N1QL query functionality] as used in the Go SDK.
First a [.api]`Cluster` object is created with the address of a cluster node, then a connection to a data bucket is opened in the form of [.api]`Cluster.OpenBucket`.

Data operations are performed against [.api]`Bucket` objects.
In this case a document is stored into the cluster using [.api]`Bucket.Upsert`.
The document is then retrieved using its ID (primary key) using the [.api]`Bucket.Get`, and lastly it is queried with the N1QL query language using [.api]`Bucket.ExecuteN1qlQuery`.

The above example also shows how you can use your own document types.
Note that JSON annotations are not required for operations, but demonstrate how existing objects may fit into your application.

== Additional Resources

* https://github.com/couchbase/gocb[Git repository^]
* https://godoc.org/github.com/couchbase/gocb[API Documentation^]
