= MapReduce Views Using the Go SDK with Couchbase Server
:navtitle: MapReduce Views

[abstract]
You can use MapReduce views to create queryable secondary indexes in Couchbase Server.

include::4.5@sdk:shared:partial$views.adoc[tag=views-intro]

include::4.5@sdk:shared:partial$views.adoc[tag=example-beer]

== Querying views through the Go SDK

Querying a view through the Go SDK is performed through the `ViewQuery` interface that is instantiated through the NewViewQuery method of the gocb library.

[source,go]
----
myQuery := gocb.NewViewQuery("beer", "by_name")
----

The `ViewQuery` interface enables you to query the view and specify various available options for the query.
Once you have the query ready for execution, pass it to the `ExecuteViewQuery` method of the your Bucket instance:

[source,go]
----
rows, err := myBucket.ExecuteViewQuery(myQuery)
if err != nil {
        fmt.Printf("View query error: %s\n", err)
}

var row interface{}
for rows.Next(&row) {
        fmt.Printf("Row: %+v\n", row)
}
if err := rows.Close(); err != nil {
        fmt.Printf("View query results error: %s\n", err)
}
----

You can modify your view results by specifying various options before executing the `query` method.
Here is an example that skips the first six items and limits the results to three items:

[source,go]
----
myQuery = gocb.NewViewQuery("beer", "by_name").Skip(6).Limit(3)
----
