= Collecting Information & Logging
:nav-title: Logging
:page-topic-type: howto

[abstract]
Logging with `gocb.Logger` & using other implementations.

The Go SDK offers simple logging of library internals to help debug issues.
Logging may be configured on a global library-level basis.
*Note that the logging API is subject to change*.

You can configure logging using the `gocb.SetLogger`, which accepts an implementation of [.api]`gocb.Logger`.
The SDK comes with two built-in `Logger` implementations, which can be instantiated using the following _methods_:

[[gocb.logger_instantiation_methods]]
* [.api]`gocb.DefaultStdioLogger()` returns a logger that logs errors and warnings.
This is fairly non-disruptive and does not produce a lot of output.
* [.api]`gocb.VerboseStdioLogger()` returns a logger that logs more detailed tracing information.
This logger should only be used when trying to diagnose an issue.

[source,go]
----
import (
        "github.com/couchbase/gocb/v2"
)

func main() {
        gocb.SetLogger(gocb.DefaultStdioLogger())

        // Use the gocb library.
}
----

It is also possible to provide other logger implementations to [.api]`gocb.SetLogger`.
Implementations must satisify the [.api]`gocb.Logger` interface.

[source,go]
----
  type Logger interface {
	// Outputs logging information:
	// level is the verbosity level
	// offset is the position within the calling stack from which the message
	// originated. This is useful for contextual loggers which retrieve file/line
	// information.
	Log(level LogLevel, offset int, format string, v ...interface{}) error
}
----

The [.api]`gocb.DefaultStdioLogger()` and [.api]`gocb.VerboseStdioLogger()` wrap their [.api]`gocbcore` counterparts to provide a stable interface.
The [.api]`gocb` versions should be used.


== Log Redaction

Redacting logs is a two-stage process. 
If you want to redact client logs (for example before handing them off to the Couchbase Support team) you first need to enable log redaction in your application.

[source,golang]
----
gocb.SetLogRedactionLevel(gocb.RedactFull)
----

Different redaction levels are supported -- please see the `RedactionLevel` enum description for more information.

Note that you need to run this command before any of the SDK code is initialized so all of the logs are captured properly. 
Once the SDK writes the logs with the tags to a file, you can then use the xref:6.5@server:cli:cbcli/cblogredaction.adoc[`cblogredaction` tool] to obfuscate the log.

* You may wish to read more on Log Redaction xref:6.5@server:manage:manage-logging/manage-logging.adoc#understanding_redaction[in the Server docs].

== Using your own logger

Sometimes you want to use your own logger with the SDK.
You might want your logging to use a popular logging framework such as logrus.
In the following examples we show to use the SDK with a logrus logger:

First we need to create our own logger that wraps the logrus logger.
The logrus `Log`/`Logf` functions don't quite match the gocb logging interface and the log levels are slightly different.
This means that we need to do a bit of marshalling to get the data into a set of parameters that logrus can use.

[source,golang,indent=0]
----
include::devguide:example$go/custom-logging.go[tag=loggerwrapper]
----

Next we need to create a logrus logger instance, wrap it in our own logger and then pass it to gocb:

[source,golang,indent=0]
----
include::devguide:example$go/custom-logging.go[tag=creation]
----

Now all of the gocb logging output will go through our logger and be outputted to stdout (e.g. the terminal) in JSON.
