= Distributed Transactions from the Go SDK
:description: A practical guide to using Couchbase’s distributed ACID transactions, via the Go SDK.
:navtitle: ACID Transactions
:page-partial:
:page-topic-type: howto
:page-aliases: acid-transactions
:page-toclevels: 2
:page-pagination: next

include::project-docs:partial$attributes.adoc[]
include::howtos:partial$acid-transactions-attributes.adoc[]

[abstract]
{description}

This guide will show you examples of how to perform multi-document ACID (atomic, consistent, isolated, and durable) database transactions within your application, using the Couchbase Go SDK.

Refer to the xref:concept-docs:transactions.adoc[Distributed ACID Transactions] concept material for a high-level overview.

== Prerequisites

[{tabs}]
====
Couchbase Capella::
+
--
* Couchbase Capella account.
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:n1ql-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:cloud:organizations:organization-projects-overview.adoc[Organizations & Access] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
--

Couchbase Server::
+
--
* Couchbase Server 7.0.0 or above.
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:n1ql-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:{version-server}@server:learn:security/roles.adoc[Roles] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
* NTP should be configured so nodes of the Couchbase cluster are in sync with time.
--
====

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]

== Creating a Transaction

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

[source,go]
----
include::devguide:example$go/transactions.go[tag=examples,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=lambda-ctx]

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating-error]

=== Logging

To aid troubleshooting, raise the log level on the SDK.
// TODO: need to add logging details
//To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:
//
//[source,java]
//----
//include::devguide:example$go/transactionsExample.java[tag=logging,indent=0]
//----
//
//A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.
//
//For convenience there is also a config option that will automatically write this programmatic log to the standard Couchbase Java logging configuration inherited from the SDK if a transaction fails.
//This will log all lines of any failed transactions, to `WARN` level:
//[source,java]
//----
//include::devguide:example$go/transactionsExample.java[tag=config_warn,indent=0]
//----

Please see the xref:howtos:collecting-information-and-logging.adoc[Go SDK logging documentation] for details.

== Key-Value Operations

You can perform transactional database operations using familiar key-value CRUD methods:

* **C**reate - `Insert()`

* **R**ead - `Get()`

* **U**pdate - `Replace()`

* **D**elete - `Remove()`

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional key-value operations inside the {lambda} -- such as `ctx.Insert()`, rather than `collection.Insert()`.
====

=== Insert

To insert a document within a transaction {lambda}, simply call `ctx.Insert()`.

[source,go]
----
include::devguide:example$go/transactions.go[tag=insert,indent=0]
----

=== Get

To retrieve a document from the database you can call `ctx.Get()`.

[source,go]
----
include::devguide:example$go/transactions.go[tag=get,indent=0]
----

`ctx.Get()` will return a `TransactionGetResult` object, which is very similar to the `GetResult` you are used to.

Getting a document could potentially return an `ErrDocumentNotFound` which can be ignored, if you are unsure whether the document exists or not, or if it not existing does not matter:

[source,go]
----
include::devguide:example$go/transactions.go[tag=getOpt,indent=0]
----

If the `ErrDocumentNotFound` is not ignored then `Get` will cause the transaction to fail with `TransactionFailedError` (after rolling back any changes, of course).
`ErrDocumentNotFound` is one of very few errors that the SDK will allow you to ignore, as the SDK internally tracks the state of the transaction and will not allow illegal operations to continue.

Gets will "Read Your Own Writes", e.g. this will succeed:

[source,go]
----
include::devguide:example$go/transactions.go[tag=getReadOwnWrites,indent=0]
----

=== Replace

Replacing a document requires a `ctx.Get()` call first.
This is necessary so the SDK can check that the document is not involved in another transaction, and take appropriate action if so.

[source,go]
----
include::devguide:example$go/transactions.go[tag=replace,indent=0]
----

=== Remove

As with replaces, removing a document requires a `ctx.Get()` call first.

[source,go]
----
include::devguide:example$go/transactions.go[tag=remove,indent=0]
----

== {sqlpp} Queries

If you already use https://www.couchbase.com/products/n1ql[{sqlpp} (formerly N1QL)], then its use in transactions is very similar.
A query returns a `TransactionQueryResult` that is very similar to the `QueryResult` you are used to, and takes most of the same options.

The main difference between `TransactionsQueryResult` and `QueryResult` is that `TransactionsQueryResult` does not stream results.
This means that there are no `Err` or `Close` functions and that result sets are buffered in memory - allowing the SDK to read and handle any errors that occur on the stream before returning a result/error.

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional query operations inside the {lambda} -- such as `ctx.Query()`, rather than `cluster.Query()` or `scope.Query()`.
====

Here is an example of selecting some rows from the `travel-sample` bucket:

[source,go]
----
include::devguide:example$go/transactions.go[tag=querySelectScope,indent=0]
----

An example using a `Scope` for an UPDATE operation:

[source,go]
----
include::devguide:example$go/transactions.go[tag=queryUpdate,indent=0]
----

And an example combining `SELECT` and `UPDATE`.

[source,go]
----
include::devguide:example$go/transactions.go[tag=queryComplex,indent=0]
----

As you can see from the snippet above, it is possible to call regular Go methods from the {lambda}, permitting complex logic to be performed.
Just remember that since the {lambda} may be called multiple times, so may the method.

Like key-value operations, queries support "Read Your Own Writes".
This example shows inserting a document and then selecting it again:

[source,go]
----
include::devguide:example$go/transactions.go[tag=queryInsert,indent=0]
----

<1> The inserted document is only staged at this point, as the transaction has not yet committed. +
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the `SELECT` can, as we are reading a mutation staged inside the same transaction.

=== Query Options

Query options can be provided via `TransactionQueryOptions`, which provides a subset of the options in the Go SDK's `QueryOptions`.

[source,go]
----
include::devguide:example$go/transactions.go[tag=queryOptions,indent=0]
----

.Supported Transaction Query Options
|===
| Name | Description

| `PositionalParameters([]interface{})` | Allows to set positional arguments for a parameterized query.
| `NamedParameters(map[string]interface{})` | Allows you to set named arguments for a parameterized query.
| `ScanConsistency(QueryScanConsistency)` | Sets a different scan consistency for this query.
| `FlexIndex(bool)` | Tells the query engine to use a flex index (utilizing the search service).
| `ClientContextID(string)` | Sets a context ID returned by the service for debugging purposes.
| `ScanWait(time.Duration)` | Allows to specify a maximum scan wait time.
| `ScanCap(uint32)` | Specifies a maximum cap on the query scan size.
| `PipelineBatch(uint32)` | Sets the batch size for the query pipeline.
| `PipelineCap(uint32)` | Sets the cap for the query pipeline.
| `Profile(QueryProfileMode)` | Allows you to enable additional query profiling as part of the response.
| `Readonly(bool)` | Tells the client and server that this query is readonly.
| `Prepared(bool)` | If set to false will prepare the query and later execute the prepared statement.
| `Raw(map[str]interface{})` | Escape hatch to add arguments that are not covered by these options.
|===

== Mixing Key-Value and {sqlpp}

Key-Value operations and queries can be freely intermixed, and will interact with each other as you would expect.
In this example we insert a document with a key-value operation, and read it with a `SELECT` query.

[source,go]
----
include::devguide:example$go/transactions.go[tag=queryRyow,indent=0]
----

<1> The key-value insert operation is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the `SELECT` can view it, as the insert was in the same transaction.

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=rbac]

== Concurrent Operations

The API allows operations to be performed concurrently inside a transaction, which can assist performance.
There are two rules the application needs to follow:

* The first mutation must be performed alone, in serial.
This is because the first mutation also triggers the creation of metadata for the transaction.
* All concurrent operations must be allowed to complete fully, so the transaction can track which operations need to be rolled back in the event of failure.
This means the application must 'swallow' the error, but record that an error occurred, and then at the end of the concurrent operations, if an error occurred, throw an error to cause the transaction to retry.

=== Non-Transactional Writes

To ensure key-value performance is not compromised, and to avoid conflicting writes, applications should *never* perform non-transactional _writes_ concurrently with transactional ones, on the same document.

// TODO: update this for Go, if available
//You can verify this when debugging your application by subscribing to the client's event logger and checking for any `IllegalDocumentStateEvent` events.
//These events are raised when a non-transactional write has been detected and overridden.

//[source,java]
//----
//include::howtos:example$TransactionsExample.java[tag=concurrency,indent=0]
//----

//The event contains the key of the document involved, to aid the application with debugging.

See xref:concept-docs:transactions.adoc#concurrency-with-non-transactional-writes[Concurrency with Non-Transactional Writes] to learn more.

== Configuration

The default configuration should be appropriate for most use-cases.
Transactions can optionally be globally configured at the point of creating the `Cluster` object.
For example, if you want to change the level of durability which must be attained, this can be configured as part of the connect options:

[source,go]
----
include::devguide:example$go/transactions.go[tag=config,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=config]

== Additional Resources

* Learn more about xref:concept-docs:transactions.adoc[Distributed ACID Transactions].

* Check out the SDK https://pkg.go.dev/github.com/couchbase/gocb/v2[API Reference].
