= Search
:description: You can use the Search Service to create queryable search indexes in Couchbase Server.
:page-toclevels: 3
:page-pagination: full


[abstract]
{description}


The Search Service allows you to create, manage, and query Search indexes on JSON documents stored in Couchbase buckets.
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.
The supported query types include queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries. 
The Go SDK exposes an API for performing Search queries which abstracts some of the complexity of using the underlying REST API.


// As of Couchbase Server 6.5, the Search Service ...

== Getting Started

After familiarizing yourself with how to create and query a search index in the UI you can query it from the SDK.
From Couchbase Server 7.6, Search queries are executed at the Scope level, or the Cluster level --
for earlier versions of Couchbase, it's just the Cluster level.
Search queries, facets, and sorting have a slightly different import from other components of `gocb`, you can import them using `import "github.com/couchbase/gocb/v2/search"`.

There are two APIs for querying search: `cluster.SearchQuery()`, and `cluster.Search()`.
Both are also available at the Scope level.

The former API supports Search queries (`SearchQuery`), while the latter additionally supports the `VectorSearch` added in 7.6.
Most of this documentation will focus on the former API, as the latter is in @Stability.Volatile status.

We will perform a Search query here. For examples, see the <<vector-search>> section.
Here is a simple `MatchQuery` that looks for the text 'swanky' using a defined index:

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=matchquery]
----

We have also included the `Fields` option which will get the content of the specified (indexed) field as a part of the response.

All simple query types are created in the same manner, although some have additional properties, which can be seen in common query type descriptions.
Couchbase Search Service's xref:{version-server}@server:fts:fts-query-types.adoc[range of query types] enable powerful searching using multiple options, to ensure results are just within the required range.
Here is a date range query that looks for dates between 1st of January 2019 and 1st of February 2019, the second parameter is whether the date should be considered inclusive:

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=daterangequery]
----

Queries can also be combined together.
A conjunction query contains multiple child queries; its result documents must satisfy all of the child queries:

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=conjunctionquery]
----

[TIP]
.Search Results Limit
====
By default, the Search Service returns only the first 10 matches (`size: 10`, `from: 0`).
To retrieve more results, you must explicitly define pagination settings such as `size` or `from` in your query.

For information about formatting your Search query and specifying limits, see xref:server:search:search-request-params.adoc[].

For information about pagination in Search responses, see xref:server:fts:fts-search-response.adoc#pagination[Pagination].
====


== Working with Results

The result of a search query has three components: rows, facets, and metdata. 
Rows are the documents that match the query. 
Facets allow the aggregation of information collected on a particular result set. 
Metdata holds additional information not directly related to your query, 
such as success total hits and how long the query took to execute in the cluster.

.Iterating Rows
Here we are iterating over the rows that were returned in the results.
Note that `Fields` is a special case, where it's a function.
`Fields` will include any fields that were requested as part of the SearchQuery (`Fields` option within the options block).

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=iteratingrows]
----

Take care to ensure you call `Err` after accessing rows and check for any errors returned.

.Iterating facets
Facets can only be accessed once all the rows have been iterated.

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=iteratingfacets]
----



== Scoped vs Global Indexes
The Search APIs exist at both the `Cluster` and `Scope` levels.

This is because the Search Service supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.searchQuery()` / `Cluster.search()` for global indexes, and `Scope.search()` for scoped indexes.

== Vector Search
As of Couchbase Server 7.6, the Search Service supports vector search in additional to traditional Search queries.
// todo link to the server docs when available

Vector search queries have a slightly different import from other components of `gocb`, you can import them using `import "github.com/couchbase/gocb/v2/vector"`.

=== Examples
==== Single vector query
In this first example we are performing a single vector query:
[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=single_vector_query]
----

Let's break this down.
We create a `SearchRequest`, which can contain a traditional Search query `SearchQuery` and/or the new `VectorSearch`.
Here we are just using the latter.

The `VectorSearch` allows us to perform one or more `VectorQuery` s.

The `VectorQuery` itself takes the name of the document field that contains embedded vectors ("vector_field" here), plus actual vector query in the form of a `[]float32`.

(Note that Couchbase itself is not involved in generating the vectors, and these will come from an external source such as an embeddings API.)

Finally we execute the `SearchRequest` against the Search index "travel-sample-index", which has previously been setup to vector index the "vector_field" field.

This happens to be a scoped index so we are using `scope.Search()`.
If it was a global index we would use `cluster.Search()` instead - see <<Scoped vs Global Indexes>>.

It returns the same `SearchResult` detailed earlier.

==== Multiple vector queries
You can run multiple vector queries together:

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=multiple_vector_queries]
----


How the results are combined (ANDed or ORed) can be controlled with `vector.SearchOptions.VectorQueryCombination`.

==== Combining Search and Vector Queries
You can combine a traditional Search query with vector queries:

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=vector_fts_query_combination]
----

How the results are combined (ANDed or ORed) can be controlled with `vector.SearchOptions.VectorQueryCombination`.

==== Search queries
Note, traditional Search queries, without vector search, are also supported with the new `cluster.Search()` / `scope.Search()` APIs:

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=fts_search_request]
----

The `SearchQuery` is created in the same way as detailed earlier.


== Consistency

Like the Couchbase Query Service, the Search Service allows `RequestPlus` queries -- _Read-Your-Own_Writes (RYOW)_ consistency, ensuring results contain information from updated indexes.

[source,go,indent=0]
----
include::devguide:example$go/search.go[tag=consistency]
----

