= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: document-operations.adoc

The complete code sample used on this page can be downloaded from xref::example$kv.go[here]
- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Collection operations.


== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the Go SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

[source,golang,indent=0]
----
include::example$kv.go[tag=insert]
----

Options like timeout may also be added to operations.
_Timeout_ in the Go SDK has a type value of `time.Duration`.
Timeout sets the timeout value for the underlying network connection.

[source,golang,indent=0]
----
include::example$kv.go[tag=insertoptions]
----

=== Timeouts

As well as explicitly setting the _Timeout_ value for an operation, the Go SDK also supports setting timeouts via the Golang https://golang.org/pkg/context/[`context.Context`] mechanism.
Using `context.Context` also provides a means to abort requests on the fly, the SDK itself does expose a way to abort requests other than this mechanism.
There are three different ways of setting a timeout on an operation: operation level timeout, `context.Context`, and the global level `KVTimeout`.
All three could be set at the same time for a given operation so the following rules are followed for picking a timeout to use:

1) If the operation level timeout is set then that will be selected over the global timeout.
2a) If `Context` is set then the shortest of the `Context` deadline and the timeout from 1 will be selected.
2b) If `Context` is not set then the timeout from 1 will be selected.

Under the hood the SDK uses `context.Context` for all timeouts and will return a gocb timeout error for timeouts for all 3 of these options.
Timeouts can be checked for with the `gocb.IsTimeoutError(err)` function.

Below we'll set `Context` with a _Replace_ operation.

[source,golang]
----
include::example$kv.go[tag=replacecontext]
----

=== CAS

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

[source,golang,indent=0]
----
include::example$kv.go[tag=replacecas]
----

Typically we would want to use CAS for something more meaningful like performing a Get, modifying the result and updating the document.
By using the CAS value we know that if anyone else modified this document and updated it before our update then ours will error.

[source,golang,indent=0]
----
include::example$kv.go[tag=update]
----

Expiry sets an explicit time to live (TTL) for a document in seconds, for which you can also xref:sdk-xattr-example.adoc[see a more detailed example of TTL discovery] later in the docs.
For a discussion of item (Document) _vs_ Bucket expiration, see the 
xref:6.0@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,golang,indent=0]
----
include::example$kv.go[tag=expiry]
----

== Durability

Writes in Couchbase are written to a single node, and from there the Couchbase Server will take care of sending that mutation to any configured replicas.
The optional durability parameter, which all mutating operations accept, allows the application to wait until this replication (or persistence) is successful before proceeding.

In Couchbase Server releases before 6.5, Durability was set with two options -- see the xref:1.6@go-sdk::durability.adoc[6.0 Durability documentation] -- covering how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist. 
Couchbase Data Platform 6.5 refines these two options, with xref:6.5@server:learn:data/durability.adoc[Durable Writes] -- although they remain essentially the same in use.
The Go SDK exposes both of these forms of Durability.

First we will cover the newer durability features available in Couchbase server 6.5 onwards.
The SDK exposes three durability levels:

----
// DurabilityLevelMajority specifies that a mutation must be replicated (held in memory) to a majority of nodes.
DurabilityLevelMajority = DurabilityLevel(1)

// DurabilityLevelMajorityAndPersistToActive specifies that a mutation must be replicated (held in memory) to a
// majority of nodes and also persisted (written to disk) on the active node.
DurabilityLevelMajorityAndPersistToActive = DurabilityLevel(2)

// DurabilityLevelPersistToMajority specifies that a mutation must be persisted (written to disk) to a majority
// of nodes.
DurabilityLevelPersistToMajority = DurabilityLevel(3)
----

The options are in increasing levels of safety. 
Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

Below we can see how to set this on an operation:

[source,golang,indent=0]
----
include::example$kv.go[tag=durability]
----

The older type of durability, observe based durability, works by monitoring the server to ensure that the change has been replicated or persisted to the required number of nodes within the timeout specified on the operation. 
Here we can see how that is set:

[source,golang,indent=0]
----
include::example$kv.go[tag=observebased]
----

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration, 
and the default level of safety provided by Couchbase will be reasonable for the majority of situations.


[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Document Operations].
====

== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,golang,indent=0]
----
include::example$kv.go[tag=get]
----

Timeout can also be set, as in the earlier `Insert` example:

[source,golang,indent=0]
----
include::example$kv.go[tag=gettimeout]
----

== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

[source,golang,indent=0]
----
include::example$kv.go[tag=remove]
----


== Expiration / TTL

We already touched on how to set `Expiry` on an operation but we didn't discuss how to handle extending that expiry time.
By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents. 
You can use expiration values on documents to handle transient data.
To prevent a document that already has expiry from expiring you can use `Touch` operations which will extend the expiry by the time specified.

[source,golang,indent=0]
----
include::example$kv.go[tag=touch]
----

If you want to get the document at the same time as extending expiry then you can use `GetAndTouch`.

[source,golang,indent=0]
----
include::example$kv.go[tag=getandtouch]
----

== Atomic document modifications

The value of a document can be increased or decreased atomically using `Binary().Increment()` and `Binary().Decrement()`.

.Increment
[source,golang,indent=0]
----
include::example$kv.go[tag=increment]
----

.Decrement
[source,golang,indent=0]
----
include::example$kv.go[tag=decrement]
----

NOTE: Increment & Decrement are considered part of the 'binary' API and as such may still be subject to change.

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.
For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

// Another way of increasing network performance is to _pipeline_ operations with xref:batching-operations.adoc[Batching Operations].

// As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:non-json.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.
