= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: document-operations.adoc

WARNING: These pages cover the first _Developer Preview_ of the Couchbase Go SDK -- 2.0 _alpha_.
As such they are likely to change without notice.
The _alpha_ code _should not_ be used in production.

//The complete code sample used on this page can be downloaded from
//  xref::example$document.cs[here]
//- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.


== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the Go SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

[source,golang]
----
Insert
document := struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}{Foo: "bar", Bar: "foo"}
result, err := col.Insert("document-key", &document, nil)
----

Options may be added to operations:

[source,golang]
----
Insert (with options)
document := struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}{Foo: "bar", Bar: "foo"}
result, err := col.Insert("document-key", &document, &gocb.InsertOptions{
    Timeout: 3 * time.Second,
})
----

_Timeout_ is an optional parameter which in the Go SDK has a type value of `time.Duration`.
Timeout sets the timeout value for the underlying network connection.
We will add to these options for the _Replace_ example:

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

[source,golang]
----
document := struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}{Foo: "foo", Bar: "bar"}
result, err := col.Replace("document-key", &document, &gocb.ReplaceOptions{
    Timeout:    3 * time.Second,
    Cas:        12345,
    Expiration: 60,
})
----

Expiration sets an explicit time to live (TTL) for a document in seconds, for which you can also xref:sdk-xattr-example.adoc[see a more detailed example of TTL discovery] later in the docs.
We'll discuss modifying `Expiration` in more details xref:#net-modifying-expiration[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the 
xref:6.0@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,golang]
----
document := struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}{Foo: "foo", Bar: "bar"}
ctx, cancelFunc := context.WithTimeout(context.Background(), 3*time.Second)
result, err := col.Replace("document-key", &document, &gocb.ReplaceOptions{
    Context:    ctx,
    Cas:        12345,
    Expiration: 60,
})
----

As well as explicitly setting the _Timeout_ value for an operation, the Go SDK also supports setting timeouts via `context.Context`.

[source,golang]
----
document := struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}{Foo: "foo", Bar: "bar"}
result, err := col.Upsert("document-key", &document, &gocb.UpsertOptions{
    Timeout:     3 * time.Second,
    Expiration:  60,
    ReplicateTo: 1,
    PersistTo:   1,
})
----

Here we have added _Durability_ options, namely `PersistTo` and `ReplicateTo`.
In Couchbase Server releases before 6.5, Durability was set with these two options -- see the xref:1.6@go-sdk::durability.adoc[6.0 Durability documentation] -- covering  how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist. 
Couchbase Data Platform 6.5 refines these two options, with xref:6.5@server:learn:data/durability.adoc[Synchronous Replication] -- although they remain essentially the same in use.
// -- as well as adding the option of xref:transactions.adoc[atomic document transactions].

The following example demonstrates using the newer durability features available in Couchbase server 6.5 onwards.

[source,golang]
----
document := struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}{Foo: "foo", Bar: "bar"}
result, err := col.Upsert("document-key", &document, &gocb.UpsertOptions{
    Timeout:     3 * time.Second,
    Expiration:  60,
    DurabilityLevel: gocb.DurabilityLevelMajority,
})
----

[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Document Operations].
====

== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,golang]
----
type doc struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}
result, err := col.Get("document-key", nil)
var content doc
err = result.Content(&content)
----

Timeout can also be set, as in the earlier `Insert` example:

[source,golang]
----
type doc struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}
result, err := col.Get("document-key", &gocb.GetOptions{
    Timeout: 3 * time.Second,
})
var content doc
err = result.Content(&content)
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

Remove (with options)
[source,golang]
----
result, err := col.Remove("document-key", &gocb.RemoveOptions{
    Timeout:     5 * time.Second,
    ReplicateTo: 1,
    PersistTo:   1,
    Cas:         12345,
})
----

== Expiration / TTL


By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents. 
You can use expiration values on documents to handle transient data.

[source,golang]
----
result, err := collection.Touch("document-key", 600, nil)
----

A network timeout can be set with the optional `TouchOptions{}`, in the same fashion as earlier examples on this page:

[source,golang]
----
result, err := collection.Touch("document-key", 600, &gocb.TouchOptions{
    Timeout: 5 * time.Second,
})
----

== Atomic document modifications

The value of a document can be increased or decreased atomically using `Binary().Increment()` and `Binary().Decrement()`.

.Increment
[source,golang]
----
// increment binary value by 1, if document doesn’t exist, seed it at 1000
collection.Binary().Increment("document-key", &gocb.CounterOptions{
    Initial: 1000,
    Delta:   1,
})
----

.Increment (with options)
[source,golang]
----
collection.Binary().Increment("document-key", &gocb.CounterOptions{
    Initial:    1000,
    Delta:      1,
    Timeout:    5 * time.Second,
    Expiration: 3600,
    Cas:        cas,
})
----

.Decrement
[source,golang]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
collection.Binary().Decrement("document-key", &gocb.CounterOptions{
    Initial: 1000,
    Delta:   1,
})
----

.Decrement (with options)
[source,golang]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
collection.Binary().Decrement("document-key", &gocb.CounterOptions{
    Initial:    1000,
    Delta:      1,
    Timeout:    5 * time.Second,
    Expiration: 3600,
    Cas:        cas,
})
----

NOTE: Increment & Decrement are considered part of the 'binary' API and as such may still be subject to change

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.
For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

// Another way of increasing network performance is to _pipeline_ operations with xref:batching-operations.adoc[Batching Operations].

// As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:non-json.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.
