= Data Operations
:description: Key Value (KV) or data service offers the simplest way to retrieve or mutate data where the key is known.
:page-topic-type: howto
:page-aliases: document-operations.adoc
:page-toclevels: 2
:page-pagination: full

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Here we cover CRUD operations, document expiration, and optimistic locking with CAS.

The complete code sample used on this page can be downloaded from https://github.com/couchbase/docs-sdk-go/blob/release/{go-current-version}/modules/devguide/examples/go/kv-crud.go[here]
-- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Collection operations.

== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the Go SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=insert]
----

Options like timeout may also be added to operations.
_Timeout_ in the Go SDK has a type value of `time.Duration`.
Timeout sets the timeout value for the underlying network connection.

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=insertoptions]
----

=== CAS

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=replacecas]
----

Typically we would want to use CAS for something more meaningful like performing a Get, modifying the result and updating the document.
By using the CAS value we know that if anyone else modified this document and updated it before our update then ours will error.

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=update]
----

Expiry sets an explicit time to live (TTL) for a document in seconds.
For a discussion of item (Document) _vs_ Bucket expiration, see the 
xref:7.1@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,go,indent=0]
----
include::devguide:example$go/kv-expiry.go[tag=expiry]
----

== Durability

Writes in Couchbase are written to a single node, and from there the Couchbase Server will take care of sending that mutation to any configured replicas.
The optional durability parameter, which all mutating operations accept, allows the application to wait until this replication (or persistence) is successful before proceeding.

In Couchbase Server releases before 6.5, Durability was set with two options -- see the xref:1.6@go-sdk::durability.adoc[6.0 Durability documentation] -- covering how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist. 
Couchbase Data Platform 6.5 refines these two options, with xref:7.1@server:learn:data/durability.adoc[Durable Writes] -- although they remain essentially the same in use.
The Go SDK exposes both of these forms of Durability.

First we will cover the newer durability features available in Couchbase server 6.5 onwards.
The SDK exposes three durability levels:

----
// DurabilityLevelMajority specifies that a mutation must be replicated (held in memory) to a majority of nodes.
DurabilityLevelMajority = DurabilityLevel(1)

// DurabilityLevelMajorityAndPersistToActive specifies that a mutation must be replicated (held in memory) to a
// majority of nodes and also persisted (written to disk) on the active node.
DurabilityLevelMajorityAndPersistToActive = DurabilityLevel(2)

// DurabilityLevelPersistToMajority specifies that a mutation must be persisted (written to disk) to a majority
// of nodes.
DurabilityLevelPersistToMajority = DurabilityLevel(3)
----

The options are in increasing levels of safety. 
Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

Below we can see how to set this on an operation:

[source,go,indent=0]
----
include::devguide:example$go/kv-durability-enhanced.go[tag=durability]
----

If a version of Couchbase Server lower than 6.5 is being used then the application can fall-back to xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions['client verified' durability]. 
The older type of durability, also known as _observe based durability_, works by monitoring the server to ensure that the change has been replicated or persisted to the required number of nodes within the timeout specified on the operation. 
Here we can see how that is set:

[source,go,indent=0]
----
include::devguide:example$go/kv-durability-observe.go[tag=observebased]
----

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration, 
and the default level of safety provided by Couchbase will be reasonable for the majority of situations.


[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Document Operations].
====

== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=get]
----

Timeout can also be set, as in the earlier `Insert` example:

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=gettimeout]
----

== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

[source,go,indent=0]
----
include::devguide:example$go/kv-crud.go[tag=remove]
----


== Expiration / TTL

We already touched on how to set `Expiry` on an operation but we didn't discuss how to handle extending that expiry time.
By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents. 
You can use expiration values on documents to handle transient data.
To prevent a document that already has expiry from expiring you can use `Touch` operations which will extend the expiry by the time specified.

[source,go,indent=0]
----
include::devguide:example$go/kv-expiry.go[tag=touch]
----

If you want to get the document at the same time as extending expiry then you can use `GetAndTouch`.

[source,go,indent=0]
----
include::devguide:example$go/kv-expiry.go[tag=getandtouch]
----

include::6.5@sdk:shared:partial$documents.adoc[tag=exp-note]


== Atomic Counters

The value of a document can be increased or decreased atomically using `Binary().Increment()` and `Binary().Decrement()`.

NOTE: Increment & Decrement are considered part of the 'binary' API and as such may still be subject to change.

.Increment
[source,go,indent=0]
----
include::devguide:example$go/kv-counter.go[tag=increment]
----

.Decrement
[source,go,indent=0]
----
include::devguide:example$go/kv-counter.go[tag=decrement]
----

TIP: Setting the document expiry time only works when a document is created, and it is not possible to update the expiry time of an existing counter document with the Increment method -- to do this during an increment, use with the `Touch()` method.



// Atomicity Across Data Centers

include::{version-common}@sdk:shared:partial$atomic.adoc[tag=xdcr]

== KV Range Scan

A range scan gives you documents from a collection, even if you don't know the document IDs.
This feature requires Couchbase Server 7.6 or newer.

TIP: KV range scan is suitable for use cases that require relatively low concurrency and tolerate relatively high latency.
If your application does many scans at once, or requires low latency results, we recommend using {sqlpp} (with a primary index on the collection) instead of KV range scan.

[#kv-range-scan-range]
=== Range scan

Here's an example of a KV range scan that gets all documents in a collection:

.KV Range Scan for all documents in a collection
[source,go,indent=0]
----
include::devguide:example$go/kv-range-scan.go[tag=range_scan_all_documents]
----

<1> The `RangeScan` struct has two optional fields: `From` and `To`.
If you omit them like in this example, you'll get all documents in the collection.
These parameters are for advanced use cases; you probably won't need to specify them.
Instead, it's more common to use the "prefix" scan type shown in the next example.


[#kv-range-scan-prefix]
=== Prefix scan

KV range scan can also give you all documents whose IDs start with the same prefix.
Imagine you have a collection where documents are named like this: `<username>::<uuid>`.
In other words, the document ID starts with the name of the user associated with the document, followed by a delimiter, and then a UUID.
If you use this document naming scheme, you can use a prefix range scan to get all documents associated with a user.
For example, to get all documents associated with user "alice", you would write:

.KV Range Scan for all documents in a collection whose IDs start with `alice::`
[source,go,indent=0]
----
include::devguide:example$go/kv-range-scan.go[tag=range_scan_prefix]
----

<1> Note the use of the `NewRangeScanForPrefix` helper function which gives a `RangeScan` scan type configured to return all documents with the given prefix.

[#kv-range-scan-sample]
=== Sample scan

If you want to get random documents from a collection, use a sample scan.

.KV Range Scan for 100 random documents
[source,go,indent=0]
----
include::devguide:example$go/kv-range-scan.go[tag=range_scan_sample]
----

[#kv-range-scan-only-ids]
=== Get IDs instead of full documents

If you only want the document IDs, set the `IDsOnly` field of `ScanOptions` to `true`, like this:

.KV Range Scan for all document IDs in a collection
[source,go,indent=0]
----
include::devguide:example$go/kv-range-scan.go[tag=range_scan_all_document_ids]
----

== Scoped KV Operations

It is possible to perform scoped key-value operations on named xref:7.1@server:learn:data/scopes-and-collections.adoc[`Collections`] _with Couchbase Server release 7.0_ onwards.
See the https://pkg.go.dev/github.com/couchbase/gocb/v2#Collection[API docs] for more information.

Here is an example showing an upsert in the `users` collection, which lives in the `travel-sample.tenant_agent_00` keyspace:

[source,go]
----
include::devguide:example$go/kv-collection-scope.go[tag=namedcollectionupsert, indent=0]
----

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.

Another way of increasing network performance is to _pipeline_ operations with xref:concurrent-async-apis.adoc#bulk-operations-api[Bulk Operations API].

As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:concept-docs:nonjson.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of {sqlpp_url}[{sqlpp} (formerly N1QL)].
