= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters
:page-toclevels: 2

// API refs
:bucket-api-reference: pass:q[BucketManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Cluster.Buckets[`Cluster.Buckets()`]]
:user-api-reference: pass:q[UserManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Cluster.Users[`Cluster.Users()`]]
:query-api-reference: pass:q[QueryIndexManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Cluster.QueryIndexes[`Cluster.QueryIndexes()`]]
:analytics-api-reference: pass:q[AnalyticsIndexManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Cluster.AnalyticsIndexes[`Cluster.AnalyticsIndexes()`]]
:search-api-reference: pass:q[SearchIndexManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Cluster.SearchIndexes[`Cluster.SearchIndexes()`]]
:collection-api-reference: pass:q[CollectionManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Bucket.Collections[`Bucket.Collections()`]]
:view-api-reference: pass:q[ ViewIndexManager -- https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Bucket.ViewIndexes[`Bucket.ViewIndexes()`]]

// one-view-update-warning common partial
:upsertDesignDocument: pass:q[`UpsertDesignDocument` method]
:getDesignDocument: pass:q[`GetDesignDocument`]

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc[API docs].

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Go SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* {bucket-api-reference}
* {user-api-reference}
* {query-api-reference} 
* {analytics-api-reference}
* {search-api-reference}
* {collection-api-reference}
* {view-api-reference}

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.Bucket(name)` before you can use cluster level managers.


== Bucket Management

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `Cluster.Buckets()` method.

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=creatingbucketmgr]
----

The `CreateBucketSettings` and `BucketSettings` structs are used for creating and updating buckets, `BucketSettings` is also used for exposing information about existing buckets.

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available:

|====
| Name | Description | Can be updated
| `Name string` | The name of the bucket, required for creation. | false
| `FlushEnabled boolean` | Enables flushing to be performed on this bucket (see the <<Flushing Buckets>> section below). | true
| `ReplicaIndexDisabled boolean` | Whether or not to replicate indexes. | false
| `RAMQuotaMB uint64` | How much memory should each node use for the bucket, required for creation. | true
| `NumReplicas uint32` | The number of replicas to use for the bucket. | true
| `BucketType BucketType` | The type of the bucket, required for creation. | false
| `EvictionPolicy EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `valueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `MaxTTL time.Duration` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `CompressionMode CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `ConflictResolutionType ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `seqno` | false
|====

The following example creates a "hello" bucket:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=createBucket]
----

We can now get this bucket and update it to enable Flush:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=updateBucket]
----

Once you no longer need to use the bucket, you can remove it:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=removeBucket]
----

=== Flushing Buckets

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `Flush` method:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=flushBucket]
----

The `Flush` operation may fail if the bucket does not have flush enabled, in that case it will return an `ErrBucketNotFlushable`.

== Collection Management

The `CollectionManager` interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.Collections()` method.
Refer to the https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc#Bucket.Collections[`CollectionManager` API documentation]
for further details.

[source,golang]
----
include::example$collection-manager.go[tag=create-collection-manager,indent=0]
----

You can create a scope:

[source,golang,indent=0]
----
include::example$collection-manager.go[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,golang,indent=0]
----
include::example$collection-manager.go[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,golang,indent=0]
----
include::example$collection-manager.go[tag=drop-collection,indent=0]

include::example$collection-manager.go[tag=drop-scope,indent=0]

----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with
xref:server:learn:security/roles.adoc#data-reader[Data Reader]

You can create users with the appropriate RBAC programmatically:
[source,golang,indent=0]
----
include::example$collection-manager.go[tag=scopeAdmin, indent=0]

----


== Index Management

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=index-management-intro]

=== QueryIndexManager

The `QueryIndexManager` interface contains the means for managing indexes used for queries.
It can be instantiated through the `Cluster.QueryIndexes()` method.

[source,golang]
----
include::example$query-index-manager.go[tag=creating-index-mgr,indent=0]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=query-index-manager-intro]

The example below shows how to create a simple primary index, restricted to a named scope and collection, by calling the `CreatePrimaryIndex()` function.
Note that you cannot provide a named scope or collection separately, both must be set for the `QueryIndexManager` to create an index on the relevant keyspace path. 

.Creating a primary index

[source,golang]
----
include::example$query-index-manager.go[tag=primary,indent=0]
----

When a primary index name is not specified, the SDK will create the index as `#primary` by default.
However, if you wish to provide a custom name, you can simply set a `CustomName` property in the `CreatePrimaryQueryIndexOptions` struct.

You may have noticed that the example also sets the `IgnoreIfExists` boolean flag. 
When set to `true`, this optional argument ensures that an error is not thrown if an index under the same name already exists.

Creating a _secondary_ index follows a similar approach, with some minor differences:

.Creating a secondary index

[source,golang]
----
include::example$query-index-manager.go[tag=secondary,indent=0]
----

The `CreateIndex()` function requires an index name to be provided, along with the fields to create the index on.
Like the _primary_ index, you can restrict a _secondary_ index to a named scope and collection by passing some options.

Indexes can easily take a long time to build if they contain a lot of documents.
In these situations, it is more ideal to build indexes in the background.
To achieve this we can use the `Deferred` boolean option, and set it to `true`.

.Deferring index creation

[source,golang]
----
include::example$query-index-manager.go[tag=defer-indexes,indent=0]
----

To delete a query index you can use the `DropIndex()` or `DropPrimaryIndex()` functions. 
Which one you use depends on the type of query index you wish to drop from the database.

.Deleting an index

[source,golang]
----
include::example$query-index-manager.go[tag=drop-primary-or-secondary-index,indent=0]
----

// * Search - note & link to FTS page & API?

== Views Management

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` structs.
All operations on design documents are performed on the `ViewIndexManager` instance:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=viewmgr]
----

The following example upserts a design document with two views:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=createView]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespaceDevelopment`, the other option is `DesignDocumentNamespaceProduction`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=getView]
----

We've created the design document using `DesignDocumentNamespaceDevelopment` and now want to push it to production, we can do this with:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=publishView]
----

To remove this design document:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=removeView]
----
