= Authenticating against Couchbase Server
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: ROOT:sdk-authentication-overview

[abstract]
As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC

Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,golang,indent=0]
----
include::devguide:example$go/connecting.go[tag=simpleconnect]
----


include::6.5@sdk:shared:partial$auth-overview.adoc[tag=rbac]

include::6.5@sdk:shared:partial$auth-overview.adoc[tag=cert-auth]


== Authenticating the Go Client by Certificate

For sample procedures whereby certificates can be generated and deployed, see xref:6.5@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this document assumes that the processes there, or something similar, have been followed.
That is:

* A cluster certificate has been created and installed on the server.
* A client certificate and private key pair have been created, and are accessible to be loaded into your application (the example below loads them from the file system).

[source,golang,indent=0]
----
include::devguide:example$go/connecting-cca.go[tag=certconnect]
----


include::6.5@sdk:shared:partial$auth-overview.adoc[tag=ldap]

[source,golang,indent=0]
----
include::devguide:example$go/connecting.go[tag=insecureLDAP]
----
