= User Management
:description: pass:q[The Go SDK lets you create _users_, assign them _roles_ and associated _privileges_, and remove them from the system.]
:page-aliases: ROOT:sdk-user-management-example.adoc

[abstract]
{description}

== User-Management APIs

Users who have been assigned the *Admin* role for the cluster are able to create, edit, and remove users.
The Go SDK provides APIs to support these activities.
A high-level summary of the APIs can be found in xref:concept-docs:sdk-user-management-overview.adoc[User-Management],
and details of all options in the https://pkg.go.dev/github.com/couchbase/gocb/v2#UserManager[UserManager API docs].

== Using the UserManager API

The most common uses of the `UserManager` API are creating and listing users:

.Creating Users
[source,golang,indent=0]
----
include::devguide:example$go/user-management.go[tag=upsert]
----

.Listing Users
[source,golang,indent=0]
----
include::devguide:example$go/user-management.go[tag=getall]
----

Using a user created in the SDK to access data:

[source,golang,indent=0]
----
include::devguide:example$go/user-management.go[tag=operations]
----

From SDK 2.6, you can also perform password rotation on the currently authenticated user without the need for elevated permissions.

CAUTION: The SDK instance becomes invalidated after changing the user's password, so you need to re-authenticate your SDK client with the new password.
If you don't, you will start to see authentication errors.

[source,golang]
----
include::devguide:example$go/change-password.go[tag=change-password]
----

== Further Reading

The SDK also contains management APIs for dealing with xref:provisioning-cluster-resources.adoc[Cluster resources].
