= MapReduce Views
:description: Our legacy MapReduce Views Service is best replaced by the scalable Query Service.
:navtitle: MapReduce Views
:page-topic-type: howto
:page-aliases: ROOT:view-queries-with-sdk,ROOT:geo-spatial-views

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

// include::{version-common}@sdk:shared:partial$views.adoc[tag=deprecate]


// option 1 - C++ - redirect to migration page, and add note at end.

// option 2 - most others - this common page, with per-sdk archive link at end.



////
Views are a legacy service which pre-dates the {name-sdk}.
Your use case is most likely to be met by the xref:howtos:n1ql-queries-with-sdk.adoc[Query service].
////

xref:{version-server}@server:learn:views/views-intro.adoc[MapReduce Views] date from the earliest days of Couchbase and although still maintained and supported for legacy use, they are deprecated in Couchbase Server, and will eventually be removed.

Views are the only service which does not benefit from xref:{version-server}@server:learn:services-and-indexes/services/services.adoc#services-and-multi-dimensional-scaling[Multi-Dimensional Scaling], and is rarely the best choice over, say, xref:howtos:n1ql-queries-with-sdk.adoc[our Query service] if you are starting a fresh application.
See our discussion document on xref:concept-docs:data-services.adoc[the best service for you to use].

CAUTION: If you are provisioning Views on Couchbase Server for a legacy application, _they must run on a 
xref:{version-server}@server:learn:buckets-memory-and-storage/storage-engines.adoc#couchstore[couchstore] bucket_.


We will maintain support for Views in the SDKs for so long as it can be used with a supported version of Couchbase Server.

Information on using MapReduce Views with the SDK can still be accessed in our https://docs-archive.couchbase.com/go-sdk/2.2/howtos/view-queries-with-sdk.html[documentation archive].

