= MapReduce Views Using the Go SDK with Couchbase Server
:description: You can use MapReduce views to create queryable indexes in Couchbase Server.
:navtitle: MapReduce Views
:page-topic-type: howto
:page-aliases: ROOT:view-queries-with-sdk,ROOT:geo-spatial-views

[abstract]
{description}

// include::{version-server}@sdk:shared:partial$views.adoc[tag=deprecate]
include::7.1@sdk:shared:partial$views.adoc[tag=deprecate]


== MapReduce Views

The normal CRUD methods allow you to look up a document by its ID.
A MapReduce (_view_ query) allows you to lookup one or more documents based on various criteria.
MapReduce views are comprised of a _map_ function that is executed once per document (this is done incrementally, so this is not run each time you query the view) and an optional _reduce_ function that performs aggregation on the results of the _map_ function.
The _map_ and _reduce_ functions are stored on the server and written in JavaScript.

MapReduce queries can be further customized during query time to allow only a subset (or range) of the data to be returned.

TIP: See the xref:7.0@server:learn:views/views-writing.adoc[Incremental MapReduce Views] and xref:7.0@server:learn:views/views-querying.adoc[Querying Data with Views] sections of the general documentation to learn more about views and their architecture.


== Querying Views through the Go SDK

Once you have a view defined, it can be queried from the Go SDK by using the `ViewQuery` method on a Bucket instance.

The following example is the definition of a `by_country` view in a _"landmarks-by-country"_ design document.
This view checks whether a document is a landmark and has a country.
If it does, it emits the landmark's country into the index.
This view allows landmarks to be queried for by country.
For example, it's now possible to ask the question "What countries start with U?"

[source,golang,indent=0]
----
include::devguide:example$go/views-startkey.go[tag=landmarksviewstart]
----

The following example is the definition of a `by_name` view in a _"landmarks-by-name"_ design document in the _"travel-sample"_ sample dataset.
This view checks whether a document is a landmark and has a name.
If it does, it emits the landmark's name into the index.
This view allows landmarks to be queried for by its _"name"_ field.

[source,golang,indent=0]
----
include::devguide:example$go/views-key.go[tag=landmarksview]
----

Once a view result is obtained then it can be iterated over and the ID, keys and values extracted.

[source,golang,indent=0]
----
include::devguide:example$go/views-key.go[tag=results]
----

Take care to ensure you call `Err` after accessing rows to check for any errors returned.
