= MapReduce Views Using the Go SDK with Couchbase Server
:navtitle: MapReduce Views
:page-topic-type: howto
:page-aliases: ROOT:view-queries-with-sdk,ROOT:querying-views,ROOT:geo-spatial-views

[abstract]
You can use MapReduce views to create queryable indexes in Couchbase Server.

WARNING: Although still maintained and supported for legacy use, Views date from the earliest days of Couchbase Server development, and as such are rarely the best choice over, say, xref:n1ql-queries-with-sdk.adoc[our Query service] for your application, see xref:concept-docs:data-services.adoc[our guide to choosing the right service].

== MapReduce Views

The normal CRUD methods allow you to look up a document by its ID.
A MapReduce (_view_ query) allows you to lookup one or more documents based on various criteria.
MapReduce views are comprised of a _map_ function that is executed once per document (this is done incrementally, so this is not run each time you query the view) and an optional _reduce_ function that performs aggregation on the results of the _map_ function.
The _map_ and _reduce_ functions are stored on the server and written in JavaScript.

MapReduce queries can be further customized during query time to allow only a subset (or range) of the data to be returned.

TIP: See the xref:6.0@server:learn:views/views-writing.adoc[Incremental MapReduce Views] and xref:6.0@server:learn:views/views-querying.adoc[Querying Data with Views] sections of the general documentation to learn more about views and their architecture.


== Querying Views through the Go SDK

Once you have a view defined, it can be queried from the Go SDK by using the `ViewQuery` method on a Bucket instance.

The following example is the definition of a `by_name` view in a _"beer"_ design document.
This view checks whether a document is a beer and has a name.
If it does, it emits the beer's name into the index.
This view allows beers to be queried for by name.
For example, it's now possible to ask the question "What beers start with A?"

[source,golang,indent=0]
----
include::example$views.go[tag=beerview]
----

The following example is the definition of a `by_name` view in a _"landmarks"_ design document in the _"travel-sample"_ sample dataset.
This view checks whether a document is a landmark and has a name.
If it does, it emits the landmark's name into the index.
This view allows landmarks to be queried for by its _"name"_ field.

[source,golang,indent=0]
----
include::example$views.go[tag=landmarksview]
----

Once a view result is obtained then it can be iterated over and the ID, keys and values extracted.

[source,golang,indent=0]
----
include::example$views.go[tag=results]
----

Take care to ensure you call `Close` after accessing rows and check for any errors returned.
This will also close the HTTP stream if a large resultset was requested.
