FROM golang:alpine

ENV GO111MODULE="on" \
    GOCACHE="/tmp/.cache/go-build" \
    CGO_ENABLED=0

ARG GROUP_ID=1000
ARG USER_ID=1000
RUN addgroup -g $GROUP_ID jenkins && \
    adduser -D -u $USER_ID -G jenkins jenkins && \
    mkdir -p /tmp/.cache/go-build/ && \
    chmod -R 777 /tmp/.cache && \
    apk add --no-cache --quiet bash make

USER jenkins
