= Couchbase Go SDK Documentation
// Settings:
ifdef::env-github[]
:warning-caption: :warning:
endif::[]
// URLs:
:url-org: https://github.com/couchbase
:url-contribute: https://docs.couchbase.com/home/contribute/index.html
:url-ui: {url-org}/docs-ui
:url-playbook: {url-org}/docs-site

This repository hosts the documentation source for the Couchbase Go SDK.
You are in the branch for the upcoming (unsupported) developer preview release of 3.0.

== Contributing

Check out our {url-contribute}[contributing guide] to learn how to:

* submit a bug or feedback issue
* set up your documentation workspace
* build the documentation
* submit a pull request

Thank you for helping to make the documentation better.

== Docs Component Configuration

This repository contains an Antora docs component.
Keep in mind these key repository features:

* Component name, version, and start page are configured in each branch's _antora.yml_ file.
* The navigation for all of the modules is stored in the ROOT module's _nav.adoc_ file.
* Production branches use the *release/X.Y* naming pattern (e.g., release/5.5, release/6.0).
 ** The {url-playbook}[docs site playbook] instructs Antora to automatically aggregate any branch names that start with *release/*.

== Documentation Site Toolchain

The documentation source files are marked up with AsciiDoc.
Once merged into a version branch, the source files and their assets are aggregated, converted to HTML, and published by Antora to our staging and production sites.
The docs components and {url-ui}[site UI] are orchestrated by the {url-playbook}[docs site playbook].
See the contributing guide to learn more.
