@startuml

node "Couchbase cluster" as cluster

database "Bucket" as bucket

rectangle "Scope" as scope

folder "Collection" as collection



file "Document 1" as document1
file "Document 2" as document2
file "Document 3" as document3

cluster --> bucket
bucket --> scope
scope --> collection
collection --> document1
collection --> document2
collection --> document3

note right of bucket

 Maximum of 30 per cluster

end note

note left of scope

  Maximum of 1000 per cluster

end note

note right of collection

  Maximum of 1000 per cluster

end note

@enduml
