= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:

[abstract]
{description}

In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
At time of writing (January 2026), this is 1.25 and 1.24.
Older versions may remain compatible, but are not supported.


== Platform Compatibility

=== OS Compatibility

The {name-sdk} will run on, and is supported on, the following OSs and platforms.
The SDK has been tested on a representative subset of the platforms listed below.

****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.
* Red Hat Enterprise Linux 8, 9, & 10.
* Oracle Linux 8, 9, & 10.
* Ubuntu (LTS) 22.04 (_Jammy_) & 24.04 (_Noble_).
* Debian 11 (_Bullseye_), Debian 12 (_Bookworm_), & Debian 13 (_Trixie_).
* SUSE Enterprise Linux 12 & 15.
* Alpine Linux 3.21 - 3.23.

[discrete]
=== Microsoft Windows

* Microsoft Windows 10 & 11;
* Windows Server 2019, 2022, & 2025.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (January 2026): 26 (Tahoe), 15 (Sequoia), and 14 (Sonoma).
****



// Network Requirements
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]



== Couchbase Server Compatibility


Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the {name-sdk} and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
Nevertheless, this combination is not recommended by our technical support organization, as not all of the latest features are supported by it.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.


.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25,25,23,25"]
|===
| | SDK 2.6 - 2.7 | 2.8 - 2.9 | 2.10 | 2.11 & 2.12

| *Server 8.0*
| *◎*
| *◎*
| *✔*
| *✔*

| *Server 7.6*
| *◎*
| *✔*
| *✔*
| *✔*

| *Server 7.2*
| *✔*
| *✔*
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy/EOL/[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase {sdk_current_version} Go SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service. 
To make development easier, the {sdk_current_version} SDK includes the Capella client certificate already installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]



=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,6,6"]
|===
| | Server 7.2 | Server 7.6.x  | Server 8.0

| KV Range Scan
| N/A
2+| From SDK 2.8.0

| Vector Search
| N/A
2+| From SDK 2.8.0 (base64 encoded vectors from 2.9.0)

| Zone aware replica reads
| N/A
2+| From SDK 2.9.3

| Vector Query using GSI
2+| N/A
| From SDK 2.11.0 ①
|===

① As part of the standard SDK {sqlpp} API, it should be compatible with all earlier versions of the SDK -- but it has not been tested.

This table is not an exhaustive list -- just a few highlights -- provided to help assess compatibility of older versions in particular.
For alignment of SDKs and new Server features, scroll down to the information below the <<api-version,API Version table>>.



////
// Not for Go SDK yet
| KV preferred server groups reads 
| N/A
2+| From SDK 2.10.0
////




=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
