= Compatibility
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-a:page-toclevels: 2
liases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
At time of writing (October 2023), this is 1.20 and 1.19.
Older versions may remain compatible, but are not supported.


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Go SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,25"]
|===
| | SDK 2.0 - 2.2 | 2.3 - 2.7

| *Server 6.6*
| *✔*
| *✔*

| *Server 7.0-7.2*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase {go-current-version} Go SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service. 
To make development easier, the {go-current-version} SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]



== Platform Compatibility

The Couchbase Go SDK is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
* CentOS 7 & 8.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (October 2023): 14 (Sonoma), 13 (Ventura), and 12 (Monterey).
M1 ARM  architecture is fully supported in the {sdk_dot_minor} Go SDK.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04 (from SDK 2.6).


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,5,6,7"]
|===
| | Server 6.6 | Server 7.0-7.1 | Server 7.2

| Enhanced Durability
3+| All SDK versions

| Durable Writes
3+| Since 2.0

| Analytics
3+| Since 1.5

| Collections
| Developer Preview in 6.6, SDK 2.0
2+| Since 2.1.8

| Scope-Level {sqlpp} Queries & all Collections features
| Not Supported
2+| Since SDK 2.3.0

| Field Level Encryption v2
3+| Since SDK 2.3.0footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
3+| Since SDK 2.0.3 (stable interface from 2.3.0)

| Distributed ACID Transactions
| Not Supported
2+| Since SDK 2.4.0

| Cloud Native Gateway
2+| Not Supported
| From SDK 2.7.0 (with xref:operator::overview.adoc[Couchbase Autonomous Operator] 2.6.1+)
|===

== Couchbase Go SDK

The Couchbase Go SDK is installed and managed using `gopkg`, in accordance with established best practices within the Go Community.
As a result, specific versions are installed within a specific developer environment.
The SDK follows http://semver.org/[Semantic Versioning^] and typically release an update of the SDK the third Tuesday of each month.
In order to update your specific developer environment to this new version, you will have to instruct Go to `go get` that specific version.
For further information, please reference the section on xref:sdk-full-installation.adoc[installation].

include::{version-common}@sdk:shared:partial$network-requirements.adoc[]

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
