= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Go SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

[abstract]
{description}

Couchbase Go SDK 2.x requires Go version 1.13, or later.
In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Go SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,20,20,30"]
|===
| | SDK 1.4 | SDK 1.5 | SDK 1.6 | SDK 2.0 - 2.2

| *Server 5.0-5.5*
| *✔*
| *✔*
| *✔*
| *◎*

| *Server 6.0*
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 6.5-6.6*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 7.0β*
| *✖*
| *✖*
| *◎*
| *◎* _(see below)_
|===

[IMPORTANT]
====
An API change in the planned release version of Couchbase Server 7.0 means changes in the latest versions of the SDK which render these new SDK versions incompatible with the beta versions of 7.0.

Go SDK *2.2.2* is the latest version compatible with Server 7.0β.

Later SDK 2.x releases will be limited to the Default Scope and Collection with the beta 7.0 server, and will only be fully compatible with the full release version.
====

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,7,5,6,5"]
|===
| | Server 5.0, 5.1, & 5.5 | Server 6.0 | Server 6.5 & 6.6 | Server 7.0β

| Enhanced Durability
4+| All SDK versions

| Durable Writes
2+| Not Supported
2+| Since 2.0

| Analytics
| DP in 5.5 with 1.4
3+| Since 1.5

| Collections
2+| Not Supported
| SDK 2.0 for Developer Preview in Server 6.5 & 6.6
| Since 2.0

| Scope-Level N1QL Queries
3+| Not Supported
| Developer Preview in 7.0β, SDK 2.1.7
|===


== Couchbase Go SDK

The Couchbase Go SDK is installed and managed using `gopkg`, in accordance with established best practices within the Go Community.
As a result, specific versions are installed within a specific developer environment.
The SDK follows http://semver.org/[Semantic Versioning^] and typically release an update of the SDK the third Tuesday of each month.
In order to update your specific developer environment to this new version, you will have to instruct Go to `go get` that specific version.
For further information, please reference the section on installation.

include::6.6@sdk:shared:partial$network-requirements.adoc[]

NOTE: With Go 1.6, which does not have the Alternate Address feature, you need to use `?network=default` in the connection string for Couchbase Cloud.


include::6.6@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
