= Couchbase Go SDK Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Go Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-go-sdk,ROOT:relnotes-go-sdk,ROOT:sdk-release-notes,ROOT:release-notes

// tag::latest[]
[abstract]
{description}

These pages cover the 2.x versions of the Couchbase Go SDK (3.x SDK API).
For release notes, download links, and installation methods for 1.6 and earlier releases of the Couchbase Go Client, please see the xref:1.6@go-sdk::sdk-release-notes.adoc[1.x Go Release Notes & Download Archive].


== SDK Installation

[source,console]
----
$ go get github.com/couchbase/gocb/v2@v2.2.3
----

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
// Currently we support using the Couchbase Go Client with Go releases 1.14 and 1.13.
Older versions may work, but are not supported. 
// For details on installation using older versions please see xref:hello-world:start-using-sdk.adoc[Start Using the SDK]

=== API Documentation

The most current and up to date API Documentation is always available through the https://pkg.go.dev/github.com/couchbase/gocb/v2[godoc website].

== Version 2.2.3 (20 April 2021)

Version 2.2.3 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.3?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1071[GOCBC-1071]:
Updated SDK to use new protocol level changes for get collection id.
* https://issues.couchbase.com/browse/GOCBC-1068[GOCBC-1068]:
Dropped log level to warn for when applying a cluster config object is preempted.
* https://issues.couchbase.com/browse/GOCBC-1079[GOCBC-1079]:
During bootstrap don't retry authentication if the error is request cancelled.
* https://issues.couchbase.com/browse/GOCBC-1081[GOCBC-1081]:
During CCCP polling don't retry request if the error is request cancelled.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1074[GOCBC-1074]:
Fixed issue where threshold log tracer was missing fields in log output.
* https://issues.couchbase.com/browse/GOCBC-1080[GOCBC-1080]:
Fixed issue where SDK would always rebuild connections on first cluster config fetched against server 7.0.
* https://issues.couchbase.com/browse/GOCBC-1082[GOCBC-1082]:
Fixed issue where bootstrapping a node during an SDK wide reconnect would cause a delay in connecting to that node.
* https://issues.couchbase.com/browse/GOCBC-1088[GOCBC-1088]:
Fixed issue where the poller controller could deadlock if a node reported a bucket not found at the same time as CCCP successfully fetched a cluster config for the first time.


== Version 2.2.2 (16 March 2021)

Version 2.2.2 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1010[GOCBC-1010]:
Added uncommitted support for collections to `SearchOptions`.
* https://issues.couchbase.com/browse/GOCBC-1024[GOCBC-1024]:
Added partition information to `QueryIndex`.
* https://issues.couchbase.com/browse/GOCBC-1056[GOCBC-1056]:
Various performance enhancements to improve CPU usage.
* https://issues.couchbase.com/browse/GOCBC-1068[GOCBC-1068]:
Dropped log level to warn for when applying a cluster config object is preempted.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1070[GOCBC-1070]:
Fixed issue where `BucketManager` `FlushBucket` didn't return `ErrBucketNotFound` when the bucket doesn't exist.
* https://issues.couchbase.com/browse/GOCBC-1066[GOCBC-1066]:
Fixed issue where shutting down cluster config polling could lead to a panic.

== Version 2.2.1 (16 February 2021)

Version 2.2.1 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1017[GOCBC-1017]:
Updated server endpoints for collections manager.
* https://issues.couchbase.com/browse/GOCBC-1040[GOCBC-1040]:
Updated json serialization of errors to include the underlying cause.
* https://issues.couchbase.com/browse/GOCBC-1054[GOCBC-1054]:
Updated `MutateIn` to allow a blank path with `RemoveSpec`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1047[GOCBC-1047]:
Fixed issue where `GetAllScopes` was not setting the max expiry value for any collections.
* https://issues.couchbase.com/browse/GOCBC-1052[GOCBC-1052]:
Fixed issue where `GetAllDesignDocuments` was ignoring the provided `namespace`.
* https://issues.couchbase.com/browse/GOCBC-1061[GOCBC-1061]:
Fixed issue where an extra, empty, origin was added to user roles on fetching the user.


== Version 2.2.1 (16 February 2021)

Version 2.2.1 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1017[GOCBC-1017]:
Updated server endpoints for collections manager.
* https://issues.couchbase.com/browse/GOCBC-1040[GOCBC-1040]:
Updated json serialization of errors to include the underlying cause.
* https://issues.couchbase.com/browse/GOCBC-1054[GOCBC-1054]:
Updated `MutateIn` to allow a blank path with `RemoveSpec`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1047[GOCBC-1047]:
Fixed issue where `GetAllScopes` was not setting the max expiry value for any collections.
* https://issues.couchbase.com/browse/GOCBC-1052[GOCBC-1052]:
Fixed issue where `GetAllDesignDocuments` was ignoring the provided `namespace`.
* https://issues.couchbase.com/browse/GOCBC-1061[GOCBC-1061]:
Fixed issue where an extra, empty, origin was added to user roles on fetching the user.


== Version 2.2.0 (15 December 2020)

Version 2.2.0 is the first release in the Go SDK 2.2 series.
It brings enhancements and bug fixes over 2.1.8, and improves compatibility with Server 6.6 and with 7.0β.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-869[GOCBC-869]:
`BucketSettings` `MaxTTL` field deprecated in favour of `MaxExpiry`.
* https://issues.couchbase.com/browse/GOCBC-934[GOCBC-934]:
Added support for bucket level durability settings in `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-948[GOCBC-948]:
Changed document expiry durations so that expiry lengths of > 30 days sent as unix timestamps (now + expiry).
* https://issues.couchbase.com/browse/GOCBC-934[GOCBC-934]:
Added support for bucket level durability settings in `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-963[GOCBC-963]:
`GetResult` `Expiry` function deprecated in favour of `ExpiryTime`.
* https://issues.couchbase.com/browse/GOCBC-972[GOCBC-972]:
Added support for `Score` to `SearchOptions`.
* https://issues.couchbase.com/browse/GOCBC-1014[GOCBC-1014]:
Updated search `GeoPolygon` support to API stability committed.
* https://issues.couchbase.com/browse/GOCBC-1015[GOCBC-1015]:
Updated `QueryOptions` `FlexIndex` support to API stability committed.
* https://issues.couchbase.com/browse/GOCBC-1026[GOCBC-1026]:
Updated `BucketSettings` ephemeral eviction policies support to API stability committed.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1022[GOCBC-1022]:
Fixed issue where having multiple buckets open could cause view requests to be sent to an incorrect bucket.
* https://issues.couchbase.com/browse/GOCBC-1021[GOCBC-1021]:
Fixed issue where having multiple buckets open could cause view manager requests to be sent to an incorrect bucket.
* https://issues.couchbase.com/browse/GOCBC-1028[GOCBC-1028]:
Fixed issue where bootstrapping against a non-kv node could never successfully fully connect.


== Version 2.1.8 (17 November 2020)

Version 2.1.8 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.8?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-937[GOCBC-937]:
Added uncommitted support for `GeoPolygon` search queries.
* https://issues.couchbase.com/browse/GOCBC-1005[GOCBC-1005]:
Added document id to key value errors.
* https://issues.couchbase.com/browse/GOCBC-1006[GOCBC-1006]:
Changed the log level for retry strategy retries from info to debug.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1007[GOCBC-1007]:
Fixed issue some operations were being incorrectly sent to the retry orchestrator on errors.

== Version 2.1.7 (20 October 2020)

Version 2.1.7 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.7?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-938[GOCBC-938]:
Added uncommitted support for `FlexIndex` to `QueryOptions`.
* https://issues.couchbase.com/browse/GOCBC-942[GOCBC-942]:
Added uncommitted support for `Scope` level queries.
* https://issues.couchbase.com/browse/GOCBC-944[GOCBC-944]:
Added uncommitted support for `Scope` level analytics queries.
* https://issues.couchbase.com/browse/GOCBC-944[GOCBC-944]:
Added uncommitted support for `User` collections level RBAC.
* https://issues.couchbase.com/browse/GOCBC-994[GOCBC-994]:
Fixed issue where nil values used in subdoc `MutateIn` operations would be rejected by the server.
These values are now coerced into JSON `null` values before sending.
* https://issues.couchbase.com/browse/GOCBC-1001[GOCBC-1001]:
Added missing `Terms`, `DateRanges`, and `NumericRanges` fields to `SearchFacetResult`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-977[GOCBC-977]:
Fixed issue where analytics `GetPendingMutations` was looking for the incorrect data structure in the HTTP response body.
* https://issues.couchbase.com/browse/GOCBC-990[GOCBC-990]:
Fixed issue where enhanced durability timeout adaptive algorithm was incorrect.
* https://issues.couchbase.com/browse/GOCBC-991[GOCBC-991]:
Fixed issue where authentication mechanisms were not correctly iterated on bootstrap.
* https://issues.couchbase.com/browse/GOCBC-996[GOCBC-996]:
Fixed issue where the `Map` datastructure was using invalid paths for `At` and `Exists`.


== Version 2.1.6 (15 September 2020)

Version 2.1.6 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.6?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-979[GOCBC-979]:
Add ExpiryTime to GetResult, providing the point in time at which a document will expire.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-969[GOCBC-969]:
Fixed issue where the SDK would attempt to parse query metrics even if they weren't present.
* https://issues.couchbase.com/browse/GOCBC-976[GOCBC-976]:
Fixed issue where custom transcoders were not supported for performing a get request with expiry.
* https://issues.couchbase.com/browse/GOCBC-978[GOCBC-978]:
Fixed issue where it was possible for more than one request to trigger switching from unknown to pending state for a given collection.
* https://issues.couchbase.com/browse/GOCBC-981[GOCBC-981]:
Fixed issue where setting the `network` connection string property to `default` would be discarded.

== Version 2.1.5 (18 August 2020)

Version 2.1.5 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.5?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-926[GOCBC-926]:
Added a new `Cluster` level option to set which authentication mechanisms to use.
* https://issues.couchbase.com/browse/GOCBC-962[GOCBC-962]:
Exposed the `ThresholdLogTracer` and corresponding options so that threshold logging can be configured.
The threshold logger can then be set on the `Cluster` level options as `Tracer`.
Note: The threshold logger is the default tracer used by the SDK.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-718[GOCBC-718]:
Fixed issue where errors would be silently swallwed when performing JSON unmarshalling of search and view queries.
Unmarshalling errors will now be surfaced by the `result.Err()` function after iterating results.
* https://issues.couchbase.com/browse/GOCBC-950[GOCBC-950]:
Fixed issue where the SDK was not performing HELLO with the JSON feature enabled, leading to some KV error message context being lost.
* https://issues.couchbase.com/browse/GOCBC-968[GOCBC-968]:
Fixed issue where n1ql indexes were being created using prepared statements.

== Version 2.1.4 (21 July 2020)

Version 2.1.4 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.4?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-889[GOCBC-889]:
Added support for remaining service types to `WaitUntilReadyOptions`.
* https://issues.couchbase.com/browse/GOCBC-932[GOCBC-932]:
Added support for ephemeral bucket eviction types in the `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-951[GOCBC-951]:
Adjusted the default max idle http connection timeout to be 4.5s from unlimited.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-925[GOCBC-925]:
Fixed issue where errors could not be accessed for queries responding with a HTTP 200 status code but containing errors.
Any errors that are included in the query response when the status code is 200 will now be surfaced through the result `Err` call.
* https://issues.couchbase.com/browse/GOCBC-928[GOCBC-928]:
Fixed issue where enhanced durability could be incorrectly flagged as unsupported.
* https://issues.couchbase.com/browse/GOCBC-931[GOCBC-931]:
Fixed issue where enhanced durability timeouts were being sent as seconds rather than milliseconds.
* https://issues.couchbase.com/browse/GOCBC-945[GOCBC-945]:
Fixed issue where ephemeral buckets could not be created using the `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-946[GOCBC-946]:
Fixed issue where `MaxTTL` was being sent as nanoseconds rather than seconds when creating buckets using the `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-955[GOCBC-955]:
Fixed issue where xattrs were being reordered when being moved to the front of the list in subdoc operations.

== Version 2.1.3 (1 July 2020)

Version 2.1.3 is an off-cadence release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.3?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-941[GOCBC-941]:
Fixed issue where `WaitUntilReady` at the `Cluster` level would always timeout.

== Version 2.1.2 (16 June 2020)

Version 2.1.2 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-907[GOCBC-907]:
Enhance search query errors to include the index name and error text from the server.
* https://issues.couchbase.com/browse/GOCBC-913[GOCBC-913]:
Ensure that only available services are used for Ping if no services specified.
* https://issues.couchbase.com/browse/GOCBC-923[GOCBC-923]:
Updated const declarations to add types to improve API reference.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-879[GOCBC-879],
https://issues.couchbase.com/browse/GOCBC-890[GOCBC-890]:
Fixed issue causing `Cluster` level operations to return errors when performed before underlying cluster or bucket connections are ready.
These operations (query, search, analytics, views, management APIs) will now behave like key value operations - waiting for connections to be ready before they are sent.
The https://docs.couchbase.com/go-sdk/2.1/howtos/managing-connections.html#waiting-for-bootstrap-completion[`WaitUntilReady`] call can still be used for verifying that connections are ready.
* https://issues.couchbase.com/browse/GOCBC-891[GOCBC-891]:
Fixed issue where the `Name` property of a `Role` was being sent as the incorrect json field name.
* https://issues.couchbase.com/browse/GOCBC-897[GOCBC-897]:
Fixed issue where operations with incredible short timeouts (timing out before operation sent) could cause a data race.
* https://issues.couchbase.com/browse/GOCBC-900[GOCBC-900]:
Fixed issue where `IgnoreIfExists` option was being ignored for query index management.
* https://issues.couchbase.com/browse/GOCBC-906[GOCBC-906]:
Fixed issue where enhanced durability could be incorrectly set as unsupported on early operations.
* https://issues.couchbase.com/browse/GOCBC-914[GOCBC-914]:
Fixed issue where operations using named collections could be sent with an incorrect collection ID in queued before the collection is known.

== Known issues
* https://issues.couchbase.com/browse/GOCBC-941[GOCBC-941]:
Performing `Cluster` level `WaitUntilReady` never completes within the timeout.
This issue was introduced whilst fixing the behaviour for operations at the `Cluster` level when the `WaitUntilReady` call is not used.
The workaround for this is to not use the `Cluster` level `WaitUntilReady` call, `Cluster` level operations will now be queued until the SDK has connected and setup anyway.

== Version 2.1.1 (19 May 2020)

Version 2.1.1 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-778[GOCBC-778]:
Updated legacy durability polling to use a backoff rather than a fixed interval.
* https://issues.couchbase.com/browse/GOCBC-824[GOCBC-824]:
Enhanced timeout errors to contain more information and match up with the https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0035-rto.md[Response Time Observability RFC].
* https://issues.couchbase.com/browse/GOCBC-828[GOCBC-828]:
Added `MaxExpiry` to the `CollectionSpec`.
* https://issues.couchbase.com/browse/GOCBC-870[GOCBC-870]:
Updated `GetAllIndexes` to only fetch GSI indexes.
* https://issues.couchbase.com/browse/GOCBC-884[GOCBC-884]:
Improved logging to always log the cluster config when fetched.
* https://issues.couchbase.com/browse/GOCBC-888[GOCBC-888]:
Re-enabled HTTP dispatch traces.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-691[GOCBC-691]:
Fixed issue where operations on unknown collections (when using 6.5 developer preview) are not automatically retried.
* https://issues.couchbase.com/browse/GOCBC-757[GOCBC-757]:
Fixed issue where an array of arrays could cause a failure when using `Get` with `Projections`.
* https://issues.couchbase.com/browse/GOCBC-882[GOCBC-882]:
Fixed issue where an invalid cluster config would trigger a shutdown of the underlying core SDK causing operations to fail.
* https://issues.couchbase.com/browse/GOCBC-884[GOCBC-884]:
Fixed issue where `UpsertUser` sent an invalid request if a role was specified with no bucket.

=== Known issues

* https://issues.couchbase.com/browse/GOCBC-879[GOCBC-879], 
https://issues.couchbase.com/browse/GOCBC-890[GOCBC-890]:
Performing `Cluster` level operations (query, search, management APIs) before underlying cluster or bucket connections are ready causes errors to be returned.
To mitigate this the `err := WaitUntilReady(time.Duration, WaitUntilReadyOptions)` operation can be used on either `Cluster` or `Bucket` which will either:
+
. Return no error if connections are setup and ready for use
. Return a `TimeoutError` if connections are not ready within the specified time limit.


== Version 2.1.0 (21 April 2020)

Version 2.1.0 is a maintenance release for the Go SDK 2.0.0.
This release contains updating to a new major release of the core part of the SDK.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-843[GOCBC-843]:
Updated to the new version of gocbcore.
This change includes a key behavioral change of no longer reporting non-configuration related connect time errors.
* https://issues.couchbase.com/browse/GOCBC-845[GOCBC-845]:
Add support for the `WaitForReady` operation, support waiting for the KeyValue service to be ready.


== Version 2.0.4 (21 April 2020)

Version 2.0.4 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.4?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-844[GOCBC-844]:
Updated to the latest version of gocbconnstr.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-838[GOCBC-838]:
Fixed issue where HTTP endpoints were being used when SSL is enabled.
* https://issues.couchbase.com/browse/GOCBC-851[GOCBC-851]:
Fixed issue where `ServerName` was not being set on the `tls.Config` when SSL was use.
* https://issues.couchbase.com/browse/GOCBC-853[GOCBC-853]:
Fixed issue where using `PasswordAuthenticator` with a root CA and SSL would cause a panic.
* https://issues.couchbase.com/browse/GOCBC-831[GOCBC-831]:
Fixed issue where search consistency options were not being set in the request payload.


== Version 2.0.3 (17 March 2020)

Version 2.0.3 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.3?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-662[GOCBC-662]:
The server requires that any subdoc xattr ops are at the beginning of the ops list. 
If the user provides an ops list containing subdoc xattr ops out of order, the SDK will now reorder it for them and then reorder it back again when it gets the result.
This ensures that `ContentAt` works as expected.
* https://issues.couchbase.com/browse/GOCBC-700[GOCBC-700]:
Made improvements to errors returned from management operations.
They now provide more contextual information.
* https://issues.couchbase.com/browse/GOCBC-716[GOCBC-716]:
SDK now returns a `FlushNotEnabled` error if bucket flush not enabled.
* https://issues.couchbase.com/browse/GOCBC-719[GOCBC-719]:
SDK now consistently creates tracing spans for all HTTP requests.
* https://issues.couchbase.com/browse/GOCBC-728[GOCBC-728]:
Added cluster level Ping operation.
* https://issues.couchbase.com/browse/GOCBC-807[GOCBC-807]:
Updated best effort retry strategy to use an exponential backoff calculator.
* https://issues.couchbase.com/browse/GOCBC-820[GOCBC-820]:
Removed `context.Context` from search index manager operations.
Note that whilst this is a breaking change it was deemed best to break it and make sure any users who are using it know that they are using unused functionality.


=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-814[GOCBC-814]:
Fixed issue where search was looking for incorrect field in the JSON response.
* https://issues.couchbase.com/browse/GOCBC-817[GOCBC-817]:
Fixed issue where opening a bucket with the same name twice led to incorrect behaviour on both buckets.


== Version 2.0.2 (21 February 2020)

Version 2.0.2 is an off-cycle release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-805[GOCBC-805]:
Updated timeout behavior across the SDK to be consistent. If an operation level timeout is provided then it is used, otherwise the respective global timeout is used.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-804[GOCBC-804]:
Fixed issue with timeouts not being respected for HTTP requests, leading to them never timing out.

== Version 2.0.1 (19 February 2020)

Version 2.0.1 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-775[GOCBC-775]:
Improve error message for when performing cluster level operations with no connections available.
* https://issues.couchbase.com/browse/GOCBC-776[GOCBC-776]:
Added support for KVDurableTimeout.
* https://issues.couchbase.com/browse/GOCBC-786[GOCBC-786]:
Improve error messages for the UserManager GetUser function.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-701[GOCBC-701]:
Fixed issue with enhanced prepared statements not being used.
* https://issues.couchbase.com/browse/GOCBC-702[GOCBC-702]:
Fixed issue with CA root certificates not being able to be provided.
* https://issues.couchbase.com/browse/GOCBC-759[GOCBC-759]:
Fixed issue with streaming results for HTTP based services timing out unexpectedly.
* https://issues.couchbase.com/browse/GOCBC-772[GOCBC-772]:
Fixed issue with many of the management API functions timing out immediately.
* https://issues.couchbase.com/browse/GOCBC-773[GOCBC-773]:
Fixed issue with queries that do not return rows (e.g. mutations) causing errors.
* https://issues.couchbase.com/browse/GOCBC-777[GOCBC-777]:
Fixed issue with failing operations causing nil pointers.
* https://issues.couchbase.com/browse/GOCBC-783[GOCBC-783]:
Fixed issue with Exists returning incorrectly if the document was recently deleted.
* https://issues.couchbase.com/browse/GOCBC-784[GOCBC-784]:
Fixed issue with Unlock returning a doc not found error instead of cas mismatch.
* https://issues.couchbase.com/browse/GOCBC-787[GOCBC-787]:
Fixed issue with some (xattr related) subdoc operations sending invalid packets.
* https://issues.couchbase.com/browse/GOCBC-789[GOCBC-789]:
Fixed issue with search index manager FreezePlan function using an invalid HTTP method.
* https://issues.couchbase.com/browse/GOCBC-790[GOCBC-790]:
Fixed issue with user manager sometimes parsing user role origins incorrectly.
* https://issues.couchbase.com/browse/GOCBC-796[GOCBC-796]:
Fixed issue with cccp poller hanging if the get cluster config op timed out.

== Version 2.0.0 (18 January 2020)

Version 2.0.0 is the first release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-510[GOCBC-510]:
Dropped support for connecting using the http scheme.
* https://issues.couchbase.com/browse/GOCBC-534[GOCBC-534]:
Added support for retry handling.
* https://issues.couchbase.com/browse/GOCBC-552[GOCBC-652]:
Added support for circuit breakers.
* https://issues.couchbase.com/browse/GOCBC-655[GOCBC-655]:
Added support for enhanced timeout errors providing more information about operations which timeout.
* https://issues.couchbase.com/browse/GOCBC-656[GOCBC-656]:
Added support for threshold logging tracer.
* https://issues.couchbase.com/browse/GOCBC-680[GOCBC-680]:
Updated how we expose and handle errors.
* https://issues.couchbase.com/browse/GOCBC-694[GOCBC-694]:
A large number of updates including:
How query and analytics results are iterated.
Minor renaming of various types.
Moving search facets, sorting, and queries to a search subpackage.
Removing serializers.
* https://issues.couchbase.com/browse/GOCBC-740[GOCBC-740]:
Updated expiry options to be `time.Duration`.
* https://issues.couchbase.com/browse/GOCBC-760[GOCBC-760]:
Moved authenticator to ClusterOptions.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 2.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::latest[]
