= Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Go Client.
:page-topic-type: project-doc
:page-aliases: relnotes-go-sdk,ROOT:relnotes-go-sdk,ROOT:sdk-release-notes,ROOT:release-notes

// tag::latest[]
[abstract]
{description}

These pages cover the 2.x versions of the Couchbase Go SDK (3.x SDK API).
For release notes, download links, and installation methods for 1.6 and earlier releases of the Couchbase Go Client, please see the https://docs-archive.couchbase.com/go-sdk/1.4/relnotes-go-sdk.html[1.x Go Release Notes & Download Archive].


== SDK Installation

[source,console]
----
$ go get github.com/couchbase/gocb/v2@v2.6.0
----

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
Older versions may work, but are not supported.

=== API Documentation

The most current and up to date API Documentation is always available through the https://pkg.go.dev/github.com/couchbase/gocb/v2[godoc website].

== Version 2.6.0 (20 October 2022)

Version 2.6.0 is the first release in the Go SDK 2.6 series.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.6.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1159[GOCBC-1159]:
Added support for refreshing the DNS SRV record when cluster becomes uncontactable, if applicable.

* https://issues.couchbase.com/browse/GOCBC-1284[GOCBC-1284],
https://issues.couchbase.com/browse/GOCBC-1328[GOCBC-1328],
https://issues.couchbase.com/browse/GOCBC-1331[GOCBC-1331]:
Significant refactoring work to kv bootstrap, including pipelining fetching a config from the cluster.

* https://issues.couchbase.com/browse/GOCBC-1316[GOCBC-1316]:
Added support for transactions `ExtInsertExisting` - allowing `ErrDocumentExists` to be be ignored in transactional inserts.

* https://issues.couchbase.com/browse/GOCBC-1341[GOCBC-1341]:
Added volatile level API support for `ConfigProfile`.

* https://issues.couchbase.com/browse/GOCBC-1352[GOCBC-1352]:
Added support for trusting the system cert store when TLS is enabled with no `CertPool` registered and `SkipVerify` not set.

* https://issues.couchbase.com/browse/GOCBC-1356[GOCBC-1356]:
Updated the behaviour when `MutateIn` or `Insert` returns `NOT_STORED` from the server to return a `ErrDocumentExists`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1347[GOCBC-1347]:
Fixed issue where a nil agent value could cause logging `TransactionATRLocation` to log a panic.
* https://issues.couchbase.com/browse/GOCBC-1348[GOCBC-1348]:
Fixed issue where a race on creating a client record could lead to a panic.

== Version 2.5.4 (27 October 2022)

Version 2.5.4 is a maintenance release for the Go SDK 2.5.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.5.3?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1347[GOCBC-1347]:
Fixed issue where a nil agent value could cause logging `TransactionATRLocation` to log a panic.

* https://issues.couchbase.com/browse/GOCBC-1348[GOCBC-1348]:
Fixed issue where a race on creating a client record could lead to a panic.

== Version 2.5.3 (21 September 2022)

Version 2.5.3 is a maintenance release for the Go SDK 2.5.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.5.3?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1338[GOCBC-1338]:
Fixed issue where `lazyCircuitBreaker` was not using 64-bit aligned values.

=== Known Issues

* https://issues.couchbase.com/browse/GOCBC-1347[GOCBC-1347]:
Known issue where a nil agent value could cause logging `TransactionATRLocation` to log a panic.
* https://issues.couchbase.com/browse/GOCBC-1348[GOCBC-1348]:
Known issue where a race on creating a client record can lead to a panic.

== Version 2.5.2 (20 July 2022)

Version 2.5.2 is a maintenance release for the Go SDK 2.5.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.5.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1246[GOCBC-1246]:
Added uncomitted stability support for `TransactionLogger` to `TransactionResult`.
* https://issues.couchbase.com/browse/GOCBC-1314[GOCBC-1314]:
Improved logging in the lost transactions process.
* https://issues.couchbase.com/browse/GOCBC-1318[GOCBC-1318]:
Changed `WaitUntilReady` to always wait for any explicitly defined services to be online.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1320[GOCBC-1320]:
Fixed issue where vbucket hashing function wasn't masking out the 16th bit of the key.


== Version 2.5.1 (22 June 2022)

Version 2.5.1 is a maintenance release for the Go SDK 2.5.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.5.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1159[GOCBC-1159]:
Improved support for serverless environments.

* https://issues.couchbase.com/browse/GOCBC-1250[GOCBC-1250]:
Added support for single query transactions via `QueryOptions` `AsTransaction`.

* https://issues.couchbase.com/browse/GOCBC-1298[GOCBC-1298]:
Masked the underlying error reason for `TransactionOperationFailedError`.

* https://issues.couchbase.com/browse/GOCBC-1213[GOCBC-1213]:
Added uncommitted API level support for `UserManager` `ChangePassword`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1300[GOCBC-1300]:
Fixed issue where transactions lost cleanup would not remove deleted collections from the cleanup list.

* https://issues.couchbase.com/browse/GOCBC-1304[GOCBC-1304]:
Fixed issue where transactions lost cleanup could temporarily block further responses being processed for a connection.


== Version 2.5.0 (28 April 2022)

Version 2.5.0 is the first release in the Go SDK 2.5 series.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.5.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1125[GOCBC-1125]:
Deprecated `Cas` on Binary Append and Prepend as the server does not support this.
Usage of `Cas` on these operations will now return an error.

* https://issues.couchbase.com/browse/GOCBC-1203[GOCBC-1203]:
Added `CompressionOptions` to `ClusterOptions`, defaulting to compression being enabled.

* https://issues.couchbase.com/browse/GOCBC-1255[GOCBC-1255]:
Deprecated `AggregatingMeterOptions` and `NewAggregatingMeter`.

* https://issues.couchbase.com/browse/GOCBC-1265[GOCBC-1265]:
Bundle Capella CA certificate with the SDK.

* https://issues.couchbase.com/browse/GOCBC-1253[TXNG-1253]:
Removed `ServerDurationDisabled` from `ThresholdLoggingOptions`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1267[GOCBC-1267]:
Fixed issue where `GetAllIndexes` could incorrectly omit the default collection.

== Version 2.4.1 (16 March 2022)

Version 2.4.1 is a maintenance release for the Go SDK 2.4.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.4.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1221[GOCBC-1221]:
Added support for handling any `retry:true` field in a query error result by retrying it.

* https://issues.couchbase.com/browse/GOCBC-1228[GOCBC-1228]:
Updated the query used within `BuildDeferredIndexes` in `QueryIndexManager`.

* https://issues.couchbase.com/browse/GOCBC-1244[GOCBC-1244]:
Updated SDK dependencies.

* https://issues.couchbase.com/browse/GOCBC-1254[GOCBC-1254]:
Added `NewLoggingMeter` and `LoggingMeterOptions` for creating the `LoggingMeter`.
`AggregatingMeterOptions` and `NewAggregatingMeter` will be deprecated in the next dot minor release.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1248[GOCBC-1248]:
Fixed issue where a hard close of a memdclient during a graceful close could trigger a panic.
* https://issues.couchbase.com/browse/GOCBC-1251[GOCBC-1251]:
Fixed issue where `SearchOptions` `ConsistentWith` was using an incorrect key within the JSON payload.
* https://issues.couchbase.com/browse/GOCBC-1256[GOCBC-1256]:
Fixed issue where config polling could fallback to using the http poller, when no http addresses are registered for use.
* https://issues.couchbase.com/browse/GOCBC-1258[GOCBC-1258]:
Fixed issue where log redaction tags were not closed correctly.

== Version 2.4.0 (16 February 2022)

Version 2.4.0 is the first release in the Go SDK 2.4 series, adding multi-document distributed ACID transactions.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.4.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1172[GOCBC-1172]:
Added uncommitted API stability support for Query option `PreserveExpiry`.

* https://issues.couchbase.com/browse/GOCBC-1176[GOCBC-1176]:
Added uncommitted API stability support for collections to query index manager.

* https://issues.couchbase.com/browse/GOCBC-1239[GOCBC-1239]:
Added `DurabilityLevelUnknown` as default durability level.

* https://issues.couchbase.com/browse/GOCBC-TXNG-127[TXNG-127]:
Integrated transactions into the SDK.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1240[GOCBC-1240]:
Fixed issue where `MutateIn` was not setting durability level.


== Version 2.3.5 (14 December 2021)

Version 2.3.5 is a maintenance release for the Go SDK 2.3.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.3.5?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1152[GOCBC-1152]:
Added uncommitted API stability support for custom conflict resolution to `BucketSettings`.

* https://issues.couchbase.com/browse/GOCBC-1156[GOCBC-1156];
Added volatile API stability support for `includeLocations` to `SearchOptions` and `Operator` to search `MatchQuery`.

* https://issues.couchbase.com/browse/GOCBC-1175[GOCBC-1175]:
Added uncommitted API stability support for `storageBackend` to `BucketSettings`.

* https://issues.couchbase.com/browse/GOCBC-1196[GOCBC-1196]:
Added the `ErrorText` of the response body field to `AnalyticsError`, `SearchError`, `ManagementError`, and `ViewError`, to allow easier debugging and error handling.
Renamed the `ResponseBody` of the `QueryError` to be `ErrorText` and contain only the error text.
Added the `StatusCode` of the response to `AnalyticsError`, `QueryError`, `ManagementError`, and `ViewError`.

* https://issues.couchbase.com/browse/GOCBC-1200[GOCBC-1200]:
Renamed `ErrRateLimiting` and `ErrQuotaLimiting` to `ErrRateLimited` and `ErrQuotaLimited`.
Note: this is a breaking change, it not expected to impact any users.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1202[GOCBC-1202]:
* https://issues.couchbase.com/browse/GOCBC-1211[GOCBC-1211]:
Fixed issues relating to rate limit error message parsing.

* https://issues.couchbase.com/browse/GOCBC-1210[GOCBC-1210]:
Fixed issue where a quota limit error was returned rather than rate limit error for key value response status code 0x32.


== Version 2.3.4 (16 November 2021)

Version 2.3.4 is a maintenance release for the Go SDK 2.3.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.3.4?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1179[GOCBC-1179]:
Added support to attempt graceful closing of connections.

* https://issues.couchbase.com/browse/GOCBC-1154[GOCBC-1154];
https://issues.couchbase.com/browse/GOCBC-1184[GOCBC-1184]:
Added RateLimitFailure and QuotaLimitFailure support for Couchbase Capella.

* https://issues.couchbase.com/browse/GOCBC-1193[GOCBC-1193]:
Added the ResponseBody field to QueryError, to allow easier debugging and error handling.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1185[GOCBC-1185]:
Fixed an issue with Queue and Set retrying during pop and remove operations.

* https://issues.couchbase.com/browse/GOCBC-1186[GOCBC-1186]:
Fixed issue where logging meter could cause a deadlock on closing the cluster object.

* https://issues.couchbase.com/browse/GOCBC-1187[GOCBC-1187]:
Fixed issue where logging meter could log a service/operation pair which has no operations.

* https://issues.couchbase.com/browse/GOCBC-1194[GOCBC-1194]:
Changed ordering of route config bootstrapping, to check all seed nodes for the default network type first.
This fixed an issue with stuck deployments using the Eventing service, after upgrade to server 7.0.2.


== Version 2.3.3 (19 October 2021)

Version 2.3.3 is a maintenance release for the Go SDK 2.3.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.3.3?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1178[GOCBC-1178]:
We no longer remove poller controller watcher from cluster config updates.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1177[GOCBC-1177]:
Fixed issue where a connection being closed by the server during bootstrap could cause the SDK to loop reconnect without backoff.
* https://issues.couchbase.com/browse/GOCBC-1183[GOCBC-1183]:
Fixed issue where SSL certificates were be not verified when no root CAs were provided.


== Version 2.3.2 (21 September 2021)

Version 2.3.2 is a maintenance release for the Go SDK 2.3.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.3.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1009[GOCBC-1009]:
Add support for Eventing function management.
* https://issues.couchbase.com/browse/GOCBC-1166[GOCBC-1166]:
Check error codes and fallback to parsing messages in query index management.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1168[GOCBC-1168]:
Fixed issue where cluster level HTTP operations could hang indefinitely.
* https://issues.couchbase.com/browse/GOCBC-1170[GOCBC-1170]:
Fixed issue where Search `ScanConsistency` was sending an incorrect value for `NotBounded`.

== Version 2.3.1 (17 August 2021)

Version 2.3.1 is a maintenance release for the Go SDK 2.3.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.3.1?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1140[GOCBC-1140]:
Fixed issue where `ViewOptions` would return an error when using `group_level`.
* https://issues.couchbase.com/browse/GOCBC-1144[GOCBC-1144]:
Added missing `min` function to `Disjunction` search query.
* https://issues.couchbase.com/browse/GOCBC-1147[GOCBC-1147]:
Fixed issue where an error occuring whilst fetching the error map during bootstrap could cause an indefinite hang.
* https://issues.couchbase.com/browse/GOCBC-1149[GOCBC-1149]:
Fixed issue where `GetAllScopes` would panic on HTTP request send failure.

== Version 2.2.5 (17 August 2021)

Version 2.2.5 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.5?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1147[GOCBC-1147]:
Fixed issue where an error occuring whilst fetching the error map during bootstrap could cause an indefinite hang.
* https://issues.couchbase.com/browse/GOCBC-1149[GOCBC-1149]:
Fixed issue where `GetAllScopes` would panic on HTTP request send failure.

== Version 2.3.0 (15 July 2021)

Version 2.3.0 is the first release in the Go SDK 2.3 series.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.3.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-935[GOCBC-935]:
Added support for Analytics remote and external link management.
* https://issues.couchbase.com/browse/GOCBC-936[GOCBC-936]:
Added support for compound dataverse names to Analytics management.
* https://issues.couchbase.com/browse/GOCBC-940[GOCBC-940]:
* https://issues.couchbase.com/browse/GOCBC-1096[GOCBC-1096]:
Updated the tracing interface, and made it API stability level committed.
* https://issues.couchbase.com/browse/GOCBC-1037[GOCBC-1037]:
Added support for `PreserveExpiry` option to key value operations.
* https://issues.couchbase.com/browse/GOCBC-1044[GOCBC-1044]:
Added support for meter interface, and default `LoggingMeter` implementation.
* https://issues.couchbase.com/browse/GOCBC-1063[GOCBC-1063]:
Added uncommitted support for `context.Context` to options blocks.
* https://issues.couchbase.com/browse/GOCBC-1077[GOCBC-1077]:
Updated errors returned on Query error code return of 12009.
* https://issues.couchbase.com/browse/GOCBC-1130[GOCBC-1130]:
Updated Query error handling to return an authentication error on error code 13104.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1095[GOCBC-1095]:
Fixed issue where View error contents were being parsed incorrectly.
* https://issues.couchbase.com/browse/GOCBC-1100[GOCBC-1100]:
Fixed issue where the Search metrics `took` field was being parsed incorrectly.
* https://issues.couchbase.com/browse/GOCBC-1106[GOCBC-1106]:
Fixed issue where a Search response containing a `hits` field but the field being `null` would lead to an error.
* https://issues.couchbase.com/browse/GOCBC-1111[GOCBC-1111]:
Fixed issue where any errors returned from the Search service were not being propagated through the SDK.
* https://issues.couchbase.com/browse/GOCBC-1127[GOCBC-1127]:
Fixed issue where Query errors were sometimes not being parsed correctly.
* https://issues.couchbase.com/browse/GOCBC-1132[GOCBC-1132]:
Fixed issue where benchmarks would not compile.

== Version 2.2.4 (15 June 2021)

Version 2.2.4 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.4?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1095[GOCBC-1095]:
Fixed issue where errors returned from views was parsed incorrectly.
* https://issues.couchbase.com/browse/GOCBC-1102[GOCBC-1102]:
Fixed issue where `WaitUntilReady` would never recover if one of the HTTP based services returned an error.
* https://issues.couchbase.com/browse/GOCBC-1106[GOCBC-1106]:
Fixed issue where `hits` being `null` in a search response would leave to an internal error.
* https://issues.couchbase.com/browse/GOCBC-1111[GOCBC-1111]; https://issues.couchbase.com/browse/GOCBC-1112[GOCBC-1112]:
Fixed issue where parsing search errors was using the incorrect field.
* https://issues.couchbase.com/browse/GOCBC-1100[GOCBC-1100]:
Fixed issue where the `took` field in search metrics was parsed incorrectly.

== Version 2.2.3 (20 April 2021)

Version 2.2.3 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.3?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1071[GOCBC-1071]:
Updated SDK to use new protocol level changes for get collection id.
* https://issues.couchbase.com/browse/GOCBC-1068[GOCBC-1068]:
Dropped log level to warn for when applying a cluster config object is preempted.
* https://issues.couchbase.com/browse/GOCBC-1079[GOCBC-1079]:
During bootstrap don't retry authentication if the error is request cancelled.
* https://issues.couchbase.com/browse/GOCBC-1081[GOCBC-1081]:
During CCCP polling don't retry request if the error is request cancelled.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1074[GOCBC-1074]:
Fixed issue where threshold log tracer was missing fields in log output.
* https://issues.couchbase.com/browse/GOCBC-1080[GOCBC-1080]:
Fixed issue where SDK would always rebuild connections on first cluster config fetched against server 7.0.
* https://issues.couchbase.com/browse/GOCBC-1082[GOCBC-1082]:
Fixed issue where bootstrapping a node during an SDK wide reconnect would cause a delay in connecting to that node.
* https://issues.couchbase.com/browse/GOCBC-1088[GOCBC-1088]:
Fixed issue where the poller controller could deadlock if a node reported a bucket not found at the same time as CCCP successfully fetched a cluster config for the first time.


== Version 2.2.2 (16 March 2021)

Version 2.2.2 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1010[GOCBC-1010]:
Added uncommitted support for collections to `SearchOptions`.
* https://issues.couchbase.com/browse/GOCBC-1024[GOCBC-1024]:
Added partition information to `QueryIndex`.
* https://issues.couchbase.com/browse/GOCBC-1056[GOCBC-1056]:
Various performance enhancements to improve CPU usage.
* https://issues.couchbase.com/browse/GOCBC-1068[GOCBC-1068]:
Dropped log level to warn for when applying a cluster config object is preempted.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1070[GOCBC-1070]:
Fixed issue where `BucketManager` `FlushBucket` didn't return `ErrBucketNotFound` when the bucket doesn't exist.
* https://issues.couchbase.com/browse/GOCBC-1066[GOCBC-1066]:
Fixed issue where shutting down cluster config polling could lead to a panic.

== Version 2.2.1 (16 February 2021)

Version 2.2.1 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1017[GOCBC-1017]:
Updated server endpoints for collections manager.
* https://issues.couchbase.com/browse/GOCBC-1040[GOCBC-1040]:
Updated json serialization of errors to include the underlying cause.
* https://issues.couchbase.com/browse/GOCBC-1054[GOCBC-1054]:
Updated `MutateIn` to allow a blank path with `RemoveSpec`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1047[GOCBC-1047]:
Fixed issue where `GetAllScopes` was not setting the max expiry value for any collections.
* https://issues.couchbase.com/browse/GOCBC-1052[GOCBC-1052]:
Fixed issue where `GetAllDesignDocuments` was ignoring the provided `namespace`.
* https://issues.couchbase.com/browse/GOCBC-1061[GOCBC-1061]:
Fixed issue where an extra, empty, origin was added to user roles on fetching the user.


== Version 2.2.1 (16 February 2021)

Version 2.2.1 is a maintenance release for the Go SDK 2.2.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-1017[GOCBC-1017]:
Updated server endpoints for collections manager.
* https://issues.couchbase.com/browse/GOCBC-1040[GOCBC-1040]:
Updated json serialization of errors to include the underlying cause.
* https://issues.couchbase.com/browse/GOCBC-1054[GOCBC-1054]:
Updated `MutateIn` to allow a blank path with `RemoveSpec`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1047[GOCBC-1047]:
Fixed issue where `GetAllScopes` was not setting the max expiry value for any collections.
* https://issues.couchbase.com/browse/GOCBC-1052[GOCBC-1052]:
Fixed issue where `GetAllDesignDocuments` was ignoring the provided `namespace`.
* https://issues.couchbase.com/browse/GOCBC-1061[GOCBC-1061]:
Fixed issue where an extra, empty, origin was added to user roles on fetching the user.


== Version 2.2.0 (15 December 2020)

Version 2.2.0 is the first release in the Go SDK 2.2 series.
It brings enhancements and bug fixes over 2.1.8, and improves compatibility with Server 6.6 and with 7.0β.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.2.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-869[GOCBC-869]:
`BucketSettings` `MaxTTL` field deprecated in favour of `MaxExpiry`.
* https://issues.couchbase.com/browse/GOCBC-934[GOCBC-934]:
Added support for bucket level durability settings in `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-948[GOCBC-948]:
Changed document expiry durations so that expiry lengths of > 30 days sent as unix timestamps (now + expiry).
* https://issues.couchbase.com/browse/GOCBC-934[GOCBC-934]:
Added support for bucket level durability settings in `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-963[GOCBC-963]:
`GetResult` `Expiry` function deprecated in favour of `ExpiryTime`.
* https://issues.couchbase.com/browse/GOCBC-972[GOCBC-972]:
Added support for `Score` to `SearchOptions`.
* https://issues.couchbase.com/browse/GOCBC-1014[GOCBC-1014]:
Updated search `GeoPolygon` support to API stability committed.
* https://issues.couchbase.com/browse/GOCBC-1015[GOCBC-1015]:
Updated `QueryOptions` `FlexIndex` support to API stability committed.
* https://issues.couchbase.com/browse/GOCBC-1026[GOCBC-1026]:
Updated `BucketSettings` ephemeral eviction policies support to API stability committed.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1022[GOCBC-1022]:
Fixed issue where having multiple buckets open could cause view requests to be sent to an incorrect bucket.
* https://issues.couchbase.com/browse/GOCBC-1021[GOCBC-1021]:
Fixed issue where having multiple buckets open could cause view manager requests to be sent to an incorrect bucket.
* https://issues.couchbase.com/browse/GOCBC-1028[GOCBC-1028]:
Fixed issue where bootstrapping against a non-kv node could never successfully fully connect.


== Version 2.1.8 (17 November 2020)

Version 2.1.8 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.8?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-937[GOCBC-937]:
Added uncommitted support for `GeoPolygon` search queries.
* https://issues.couchbase.com/browse/GOCBC-1005[GOCBC-1005]:
Added document id to key value errors.
* https://issues.couchbase.com/browse/GOCBC-1006[GOCBC-1006]:
Changed the log level for retry strategy retries from info to debug.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-1007[GOCBC-1007]:
Fixed issue some operations were being incorrectly sent to the retry orchestrator on errors.

== Version 2.1.7 (20 October 2020)

Version 2.1.7 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.7?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-938[GOCBC-938]:
Added uncommitted support for `FlexIndex` to `QueryOptions`.
* https://issues.couchbase.com/browse/GOCBC-942[GOCBC-942]:
Added uncommitted support for `Scope` level queries.
* https://issues.couchbase.com/browse/GOCBC-944[GOCBC-944]:
Added uncommitted support for `Scope` level analytics queries.
* https://issues.couchbase.com/browse/GOCBC-944[GOCBC-944]:
Added uncommitted support for `User` collections level RBAC.
* https://issues.couchbase.com/browse/GOCBC-994[GOCBC-994]:
Fixed issue where nil values used in subdoc `MutateIn` operations would be rejected by the server.
These values are now coerced into JSON `null` values before sending.
* https://issues.couchbase.com/browse/GOCBC-1001[GOCBC-1001]:
Added missing `Terms`, `DateRanges`, and `NumericRanges` fields to `SearchFacetResult`.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-977[GOCBC-977]:
Fixed issue where analytics `GetPendingMutations` was looking for the incorrect data structure in the HTTP response body.
* https://issues.couchbase.com/browse/GOCBC-990[GOCBC-990]:
Fixed issue where enhanced durability timeout adaptive algorithm was incorrect.
* https://issues.couchbase.com/browse/GOCBC-991[GOCBC-991]:
Fixed issue where authentication mechanisms were not correctly iterated on bootstrap.
* https://issues.couchbase.com/browse/GOCBC-996[GOCBC-996]:
Fixed issue where the `Map` datastructure was using invalid paths for `At` and `Exists`.


== Version 2.1.6 (15 September 2020)

Version 2.1.6 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.6?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-979[GOCBC-979]:
Add ExpiryTime to GetResult, providing the point in time at which a document will expire.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-969[GOCBC-969]:
Fixed issue where the SDK would attempt to parse query metrics even if they weren't present.
* https://issues.couchbase.com/browse/GOCBC-976[GOCBC-976]:
Fixed issue where custom transcoders were not supported for performing a get request with expiry.
* https://issues.couchbase.com/browse/GOCBC-978[GOCBC-978]:
Fixed issue where it was possible for more than one request to trigger switching from unknown to pending state for a given collection.
* https://issues.couchbase.com/browse/GOCBC-981[GOCBC-981]:
Fixed issue where setting the `network` connection string property to `default` would be discarded.

== Version 2.1.5 (18 August 2020)

Version 2.1.5 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.5?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-926[GOCBC-926]:
Added a new `Cluster` level option to set which authentication mechanisms to use.
* https://issues.couchbase.com/browse/GOCBC-962[GOCBC-962]:
Exposed the `ThresholdLogTracer` and corresponding options so that threshold logging can be configured.
The threshold logger can then be set on the `Cluster` level options as `Tracer`.
Note: The threshold logger is the default tracer used by the SDK.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-718[GOCBC-718]:
Fixed issue where errors would be silently swallwed when performing JSON unmarshalling of search and view queries.
Unmarshalling errors will now be surfaced by the `result.Err()` function after iterating results.
* https://issues.couchbase.com/browse/GOCBC-950[GOCBC-950]:
Fixed issue where the SDK was not performing HELLO with the JSON feature enabled, leading to some KV error message context being lost.
* https://issues.couchbase.com/browse/GOCBC-968[GOCBC-968]:
Fixed issue where n1ql indexes were being created using prepared statements.

== Version 2.1.4 (21 July 2020)

Version 2.1.4 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.4?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-889[GOCBC-889]:
Added support for remaining service types to `WaitUntilReadyOptions`.
* https://issues.couchbase.com/browse/GOCBC-932[GOCBC-932]:
Added support for ephemeral bucket eviction types in the `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-951[GOCBC-951]:
Adjusted the default max idle http connection timeout to be 4.5s from unlimited.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-925[GOCBC-925]:
Fixed issue where errors could not be accessed for queries responding with a HTTP 200 status code but containing errors.
Any errors that are included in the query response when the status code is 200 will now be surfaced through the result `Err` call.
* https://issues.couchbase.com/browse/GOCBC-928[GOCBC-928]:
Fixed issue where enhanced durability could be incorrectly flagged as unsupported.
* https://issues.couchbase.com/browse/GOCBC-931[GOCBC-931]:
Fixed issue where enhanced durability timeouts were being sent as seconds rather than milliseconds.
* https://issues.couchbase.com/browse/GOCBC-945[GOCBC-945]:
Fixed issue where ephemeral buckets could not be created using the `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-946[GOCBC-946]:
Fixed issue where `MaxTTL` was being sent as nanoseconds rather than seconds when creating buckets using the `BucketManager`.
* https://issues.couchbase.com/browse/GOCBC-955[GOCBC-955]:
Fixed issue where xattrs were being reordered when being moved to the front of the list in subdoc operations.

== Version 2.1.3 (1 July 2020)

Version 2.1.3 is an off-cadence release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.3?tab=doc[API Documentation]

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-941[GOCBC-941]:
Fixed issue where `WaitUntilReady` at the `Cluster` level would always timeout.

== Version 2.1.2 (16 June 2020)

Version 2.1.2 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-907[GOCBC-907]:
Enhance search query errors to include the index name and error text from the server.
* https://issues.couchbase.com/browse/GOCBC-913[GOCBC-913]:
Ensure that only available services are used for Ping if no services specified.
* https://issues.couchbase.com/browse/GOCBC-923[GOCBC-923]:
Updated const declarations to add types to improve API reference.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-879[GOCBC-879],
https://issues.couchbase.com/browse/GOCBC-890[GOCBC-890]:
Fixed issue causing `Cluster` level operations to return errors when performed before underlying cluster or bucket connections are ready.
These operations (query, search, analytics, views, management APIs) will now behave like key value operations - waiting for connections to be ready before they are sent.
The https://docs.couchbase.com/go-sdk/2.1/howtos/managing-connections.html#waiting-for-bootstrap-completion[`WaitUntilReady`] call can still be used for verifying that connections are ready.
* https://issues.couchbase.com/browse/GOCBC-891[GOCBC-891]:
Fixed issue where the `Name` property of a `Role` was being sent as the incorrect json field name.
* https://issues.couchbase.com/browse/GOCBC-897[GOCBC-897]:
Fixed issue where operations with incredible short timeouts (timing out before operation sent) could cause a data race.
* https://issues.couchbase.com/browse/GOCBC-900[GOCBC-900]:
Fixed issue where `IgnoreIfExists` option was being ignored for query index management.
* https://issues.couchbase.com/browse/GOCBC-906[GOCBC-906]:
Fixed issue where enhanced durability could be incorrectly set as unsupported on early operations.
* https://issues.couchbase.com/browse/GOCBC-914[GOCBC-914]:
Fixed issue where operations using named collections could be sent with an incorrect collection ID in queued before the collection is known.

== Known issues
* https://issues.couchbase.com/browse/GOCBC-941[GOCBC-941]:
Performing `Cluster` level `WaitUntilReady` never completes within the timeout.
This issue was introduced whilst fixing the behaviour for operations at the `Cluster` level when the `WaitUntilReady` call is not used.
The workaround for this is to not use the `Cluster` level `WaitUntilReady` call, `Cluster` level operations will now be queued until the SDK has connected and setup anyway.

== Version 2.1.1 (19 May 2020)

Version 2.1.1 is a maintenance release for the Go SDK 2.1.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-778[GOCBC-778]:
Updated legacy durability polling to use a backoff rather than a fixed interval.
* https://issues.couchbase.com/browse/GOCBC-824[GOCBC-824]:
Enhanced timeout errors to contain more information and match up with the https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0035-rto.md[Response Time Observability RFC].
* https://issues.couchbase.com/browse/GOCBC-828[GOCBC-828]:
Added `MaxExpiry` to the `CollectionSpec`.
* https://issues.couchbase.com/browse/GOCBC-870[GOCBC-870]:
Updated `GetAllIndexes` to only fetch GSI indexes.
* https://issues.couchbase.com/browse/GOCBC-884[GOCBC-884]:
Improved logging to always log the cluster config when fetched.
* https://issues.couchbase.com/browse/GOCBC-888[GOCBC-888]:
Re-enabled HTTP dispatch traces.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-691[GOCBC-691]:
Fixed issue where operations on unknown collections (when using 6.5 developer preview) are not automatically retried.
* https://issues.couchbase.com/browse/GOCBC-757[GOCBC-757]:
Fixed issue where an array of arrays could cause a failure when using `Get` with `Projections`.
* https://issues.couchbase.com/browse/GOCBC-882[GOCBC-882]:
Fixed issue where an invalid cluster config would trigger a shutdown of the underlying core SDK causing operations to fail.
* https://issues.couchbase.com/browse/GOCBC-884[GOCBC-884]:
Fixed issue where `UpsertUser` sent an invalid request if a role was specified with no bucket.

=== Known issues

* https://issues.couchbase.com/browse/GOCBC-879[GOCBC-879], 
https://issues.couchbase.com/browse/GOCBC-890[GOCBC-890]:
Performing `Cluster` level operations (query, search, management APIs) before underlying cluster or bucket connections are ready causes errors to be returned.
To mitigate this the `err := WaitUntilReady(time.Duration, WaitUntilReadyOptions)` operation can be used on either `Cluster` or `Bucket` which will either:
+
. Return no error if connections are setup and ready for use
. Return a `TimeoutError` if connections are not ready within the specified time limit.


== Version 2.1.0 (21 April 2020)

Version 2.1.0 is a maintenance release for the Go SDK 2.0.0.
This release contains updating to a new major release of the core part of the SDK.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.1.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-843[GOCBC-843]:
Updated to the new version of gocbcore.
This change includes a key behavioral change of no longer reporting non-configuration related connect time errors.
* https://issues.couchbase.com/browse/GOCBC-845[GOCBC-845]:
Add support for the `WaitForReady` operation, support waiting for the KeyValue service to be ready.


== Version 2.0.4 (21 April 2020)

Version 2.0.4 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.4?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-844[GOCBC-844]:
Updated to the latest version of gocbconnstr.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-838[GOCBC-838]:
Fixed issue where HTTP endpoints were being used when SSL is enabled.
* https://issues.couchbase.com/browse/GOCBC-851[GOCBC-851]:
Fixed issue where `ServerName` was not being set on the `tls.Config` when SSL was use.
* https://issues.couchbase.com/browse/GOCBC-853[GOCBC-853]:
Fixed issue where using `PasswordAuthenticator` with a root CA and SSL would cause a panic.
* https://issues.couchbase.com/browse/GOCBC-831[GOCBC-831]:
Fixed issue where search consistency options were not being set in the request payload.


== Version 2.0.3 (17 March 2020)

Version 2.0.3 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.3?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-662[GOCBC-662]:
The server requires that any subdoc xattr ops are at the beginning of the ops list. 
If the user provides an ops list containing subdoc xattr ops out of order, the SDK will now reorder it for them and then reorder it back again when it gets the result.
This ensures that `ContentAt` works as expected.
* https://issues.couchbase.com/browse/GOCBC-700[GOCBC-700]:
Made improvements to errors returned from management operations.
They now provide more contextual information.
* https://issues.couchbase.com/browse/GOCBC-716[GOCBC-716]:
SDK now returns a `FlushNotEnabled` error if bucket flush not enabled.
* https://issues.couchbase.com/browse/GOCBC-719[GOCBC-719]:
SDK now consistently creates tracing spans for all HTTP requests.
* https://issues.couchbase.com/browse/GOCBC-728[GOCBC-728]:
Added cluster level Ping operation.
* https://issues.couchbase.com/browse/GOCBC-807[GOCBC-807]:
Updated best effort retry strategy to use an exponential backoff calculator.
* https://issues.couchbase.com/browse/GOCBC-820[GOCBC-820]:
Removed `context.Context` from search index manager operations.
Note that whilst this is a breaking change it was deemed best to break it and make sure any users who are using it know that they are using unused functionality.


=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-814[GOCBC-814]:
Fixed issue where search was looking for incorrect field in the JSON response.
* https://issues.couchbase.com/browse/GOCBC-817[GOCBC-817]:
Fixed issue where opening a bucket with the same name twice led to incorrect behaviour on both buckets.


== Version 2.0.2 (21 February 2020)

Version 2.0.2 is an off-cycle release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-805[GOCBC-805]:
Updated timeout behavior across the SDK to be consistent. If an operation level timeout is provided then it is used, otherwise the respective global timeout is used.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-804[GOCBC-804]:
Fixed issue with timeouts not being respected for HTTP requests, leading to them never timing out.

== Version 2.0.1 (19 February 2020)

Version 2.0.1 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-775[GOCBC-775]:
Improve error message for when performing cluster level operations with no connections available.
* https://issues.couchbase.com/browse/GOCBC-776[GOCBC-776]:
Added support for KVDurableTimeout.
* https://issues.couchbase.com/browse/GOCBC-786[GOCBC-786]:
Improve error messages for the UserManager GetUser function.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-701[GOCBC-701]:
Fixed issue with enhanced prepared statements not being used.
* https://issues.couchbase.com/browse/GOCBC-702[GOCBC-702]:
Fixed issue with CA root certificates not being able to be provided.
* https://issues.couchbase.com/browse/GOCBC-759[GOCBC-759]:
Fixed issue with streaming results for HTTP based services timing out unexpectedly.
* https://issues.couchbase.com/browse/GOCBC-772[GOCBC-772]:
Fixed issue with many of the management API functions timing out immediately.
* https://issues.couchbase.com/browse/GOCBC-773[GOCBC-773]:
Fixed issue with queries that do not return rows (e.g. mutations) causing errors.
* https://issues.couchbase.com/browse/GOCBC-777[GOCBC-777]:
Fixed issue with failing operations causing nil pointers.
* https://issues.couchbase.com/browse/GOCBC-783[GOCBC-783]:
Fixed issue with Exists returning incorrectly if the document was recently deleted.
* https://issues.couchbase.com/browse/GOCBC-784[GOCBC-784]:
Fixed issue with Unlock returning a doc not found error instead of cas mismatch.
* https://issues.couchbase.com/browse/GOCBC-787[GOCBC-787]:
Fixed issue with some (xattr related) subdoc operations sending invalid packets.
* https://issues.couchbase.com/browse/GOCBC-789[GOCBC-789]:
Fixed issue with search index manager FreezePlan function using an invalid HTTP method.
* https://issues.couchbase.com/browse/GOCBC-790[GOCBC-790]:
Fixed issue with user manager sometimes parsing user role origins incorrectly.
* https://issues.couchbase.com/browse/GOCBC-796[GOCBC-796]:
Fixed issue with cccp poller hanging if the get cluster config op timed out.

== Version 2.0.0 (18 January 2020)

Version 2.0.0 is the first release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-510[GOCBC-510]:
Dropped support for connecting using the http scheme.
* https://issues.couchbase.com/browse/GOCBC-534[GOCBC-534]:
Added support for retry handling.
* https://issues.couchbase.com/browse/GOCBC-552[GOCBC-652]:
Added support for circuit breakers.
* https://issues.couchbase.com/browse/GOCBC-655[GOCBC-655]:
Added support for enhanced timeout errors providing more information about operations which timeout.
* https://issues.couchbase.com/browse/GOCBC-656[GOCBC-656]:
Added support for threshold logging tracer.
* https://issues.couchbase.com/browse/GOCBC-680[GOCBC-680]:
Updated how we expose and handle errors.
* https://issues.couchbase.com/browse/GOCBC-694[GOCBC-694]:
A large number of updates including:
How query and analytics results are iterated.
Minor renaming of various types.
Moving search facets, sorting, and queries to a search subpackage.
Removing serializers.
* https://issues.couchbase.com/browse/GOCBC-740[GOCBC-740]:
Updated expiry options to be `time.Duration`.
* https://issues.couchbase.com/browse/GOCBC-760[GOCBC-760]:
Moved authenticator to ClusterOptions.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 2.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::latest[]
