= Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Go Client.
:page-topic-type: project-doc
:page-aliases: relnotes-go-sdk,ROOT:relnotes-go-sdk,ROOT:sdk-release-notes,ROOT:release-notes

[abstract]
{description}

These pages cover the 2.x versions of the Couchbase Go SDK (3.x SDK API).
For release notes, download links, and installation methods for 1.6 and earlier releases of the Couchbase Go Client, please see the https://docs-archive.couchbase.com/go-sdk/1.4/relnotes-go-sdk.html[1.x Go Release Notes & Download Archive].


== SDK Installation

[source,console]
----
$ go get github.com/couchbase/gocb/v2@v2.0.4
----

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
Older versions may work, but are not supported.

=== API Documentation

The most current and up to date API Documentation is always available through the https://pkg.go.dev/github.com/couchbase/gocb/v2[godoc website].


== Version 2.0.4 (21 April 2020)

Version 2.0.4 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.4?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-844[GOCBC-844]:
Updated to the latest version of gocbconnstr.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-838[GOCBC-838]:
Fixed issue where HTTP endpoints were being used when SSL is enabled.
* https://issues.couchbase.com/browse/GOCBC-851[GOCBC-851]:
Fixed issue where `ServerName` was not being set on the `tls.Config` when SSL was use.
* https://issues.couchbase.com/browse/GOCBC-853[GOCBC-853]:
Fixed issue where using `PasswordAuthenticator` with a root CA and SSL would cause a panic.
* https://issues.couchbase.com/browse/GOCBC-831[GOCBC-831]:
Fixed issue where search consistency options were not being set in the request payload.


== Version 2.0.3 (17 March 2020)

Version 2.0.3 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.3?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-662[GOCBC-662]:
The server requires that any subdoc xattr ops are at the beginning of the ops list. 
If the user provides an ops list containing subdoc xattr ops out of order, the SDK will now reorder it for them and then reorder it back again when it gets the result.
This ensures that `ContentAt` works as expected.
* https://issues.couchbase.com/browse/GOCBC-700[GOCBC-700]:
Made improvements to errors returned from management operations.
They now provide more contextual information.
* https://issues.couchbase.com/browse/GOCBC-716[GOCBC-716]:
SDK now returns a `FlushNotEnabled` error if bucket flush not enabled.
* https://issues.couchbase.com/browse/GOCBC-719[GOCBC-719]:
SDK now consistently creates tracing spans for all HTTP requests.
* https://issues.couchbase.com/browse/GOCBC-728[GOCBC-728]:
Added cluster level Ping operation.
* https://issues.couchbase.com/browse/GOCBC-807[GOCBC-807]:
Updated best effort retry strategy to use an exponential backoff calculator.
* https://issues.couchbase.com/browse/GOCBC-820[GOCBC-820]:
Removed `context.Context` from search index manager operations.
Note that whilst this is a breaking change it was deemed best to break it and make sure any users who are using it know that they are using unused functionality.


=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-814[GOCBC-814]:
Fixed issue where search was looking for incorrect field in the JSON response.
* https://issues.couchbase.com/browse/GOCBC-817[GOCBC-817]:
Fixed issue where opening a bucket with the same name twice led to incorrect behaviour on both buckets.


== Version 2.0.2 (21 February 2020)

Version 2.0.2 is an off-cycle release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.2?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-805[GOCBC-805]:
Updated timeout behavior across the SDK to be consistent. If an operation level timeout is provided then it is used, otherwise the respective global timeout is used.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-804[GOCBC-804]:
Fixed issue with timeouts not being respected for HTTP requests, leading to them never timing out.

== Version 2.0.1 (19 February 2020)

Version 2.0.1 is a maintenance release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.1?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-775[GOCBC-775]:
Improve error message for when performing cluster level operations with no connections available.
* https://issues.couchbase.com/browse/GOCBC-776[GOCBC-776]:
Added support for KVDurableTimeout.
* https://issues.couchbase.com/browse/GOCBC-786[GOCBC-786]:
Improve error messages for the UserManager GetUser function.

=== Fixed Issues

* https://issues.couchbase.com/browse/GOCBC-701[GOCBC-701]:
Fixed issue with enhanced prepared statements not being used.
* https://issues.couchbase.com/browse/GOCBC-702[GOCBC-702]:
Fixed issue with CA root certificates not being able to be provided.
* https://issues.couchbase.com/browse/GOCBC-759[GOCBC-759]:
Fixed issue with streaming results for HTTP based services timing out unexpectedly.
* https://issues.couchbase.com/browse/GOCBC-772[GOCBC-772]:
Fixed issue with many of the management API functions timing out immediately.
* https://issues.couchbase.com/browse/GOCBC-773[GOCBC-773]:
Fixed issue with queries that do not return rows (e.g. mutations) causing errors.
* https://issues.couchbase.com/browse/GOCBC-777[GOCBC-777]:
Fixed issue with failing operations causing nil pointers.
* https://issues.couchbase.com/browse/GOCBC-783[GOCBC-783]:
Fixed issue with Exists returning incorrectly if the document was recently deleted.
* https://issues.couchbase.com/browse/GOCBC-784[GOCBC-784]:
Fixed issue with Unlock returning a doc not found error instead of cas mismatch.
* https://issues.couchbase.com/browse/GOCBC-787[GOCBC-787]:
Fixed issue with some (xattr related) subdoc operations sending invalid packets.
* https://issues.couchbase.com/browse/GOCBC-789[GOCBC-789]:
Fixed issue with search index manager FreezePlan function using an invalid HTTP method.
* https://issues.couchbase.com/browse/GOCBC-790[GOCBC-790]:
Fixed issue with user manager sometimes parsing user role origins incorrectly.
* https://issues.couchbase.com/browse/GOCBC-796[GOCBC-796]:
Fixed issue with cccp poller hanging if the get cluster config op timed out.

== Version 2.0.0 (18 January 2020)

Version 2.0.0 is the first release for the Go SDK 2.0.0.

https://pkg.go.dev/github.com/couchbase/gocb/v2@v2.0.0?tab=doc[API Documentation]

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/GOCBC-510[GOCBC-510]:
Dropped support for connecting using the http scheme.
* https://issues.couchbase.com/browse/GOCBC-534[GOCBC-534]:
Added support for retry handling.
* https://issues.couchbase.com/browse/GOCBC-552[GOCBC-652]:
Added support for circuit breakers.
* https://issues.couchbase.com/browse/GOCBC-655[GOCBC-655]:
Added support for enhanced timeout errors providing more information about operations which timeout.
* https://issues.couchbase.com/browse/GOCBC-656[GOCBC-656]:
Added support for threshold logging tracer.
* https://issues.couchbase.com/browse/GOCBC-680[GOCBC-680]:
Updated how we expose and handle errors.
* https://issues.couchbase.com/browse/GOCBC-694[GOCBC-694]:
A large number of updates including:
How query and analytics results are iterated.
Minor renaming of various types.
Moving search facets, sorting, and queries to a search subpackage.
Removing serializers.
* https://issues.couchbase.com/browse/GOCBC-740[GOCBC-740]:
Updated expiry options to be `time.Duration`.
* https://issues.couchbase.com/browse/GOCBC-760[GOCBC-760]:
Moved authenticator to ClusterOptions.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 2.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
