= The Data Model
:description: Couchbase's use of JSON as a storage format allows powerful search and query over documents.
:nav-title: Data Model
:page-topic-type: concept
:page-aliases: ROOT:core-operations, ROOT:datastructures

[abstract]
{description}
Several data structures are supported by the SDK, including map, list, queue, and set.


include::7.0@sdk:shared:partial$data-model.adoc[tag=intro]

== Data Structures 

Data structures in Couchbase are similar in concept to data structures in Go:

* *Map* is like a Go `map`, and is a key-value structure, where a value is accessed by using a key string.
* *List* is like a Go `slice` and is a sequential data structure.
Values can be placed in the beginning or end of a list, and can be accessed using numeric indexes.
* *Set* is a wrapper over a _list_ which provides the ability to handle unique values.

These data structures are stored as JSON documents in Couchbase, and can therefore be accessed using N1QL, Full Text Search, and normal key-value operations.
Data structures can also be manipulated using the traditional sub-document and full-document KV APIs.

Using the data structures API may help your application in two ways:

* *Simplicity*: Data structures provide high level operations by which you can deal with documents as if they were container data structures.
Adding an item to a dictionary is expressed as `MapAdd`, rather than retrieving the entire document, modifying it locally, and then saving it back to the server.
* *Efficiency*: Data structure operations do not transfer the entire document across the network.
Only the relevant data is exchanged between client and server, allowing for less network overhead and lower latency.

// == Creating a Data Structure

