= Document 
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
:nav-title: Documents & Doc Ops
:page-topic-type: concept
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic

[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::7.1@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,golang,indent=0]
----
Upsert(docid string, document interface{}, options *gocb.UpsertOptions) (*MutationResult, error)
Insert(docid string, document interface{}, options *gocb.InsertOptions) (*MutationResult, error)
Replace(docid string, document interface{}, options *gocb.ReplaceOptions) (*MutationResult, error)
Get(docid string, options *gocb.GetOptions) (*GetResult, error)
Remove(docid string, options *gocb.RemoveOptions) (*MutationResult, error)
----

include::7.1@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::7.1@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,golang,indent=0]
----
include::example$documents.go[tag=mutate-in]
----

or xref:7.0@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
update `travel-sample`.inventory.airline SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::7.1@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport USE KEYS ["airport_1254"];
----

or

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport WHERE META().id = "airport_1254";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,golang,indent=0]
----
include::example$documents.go[tag=lookup-in]
----

// Counters

include::7.1@sdk:shared:partial$documents.adoc[tag=counters1]

[source,go,indent=0]
----
include::example$documents.go[tag=counters]
----

include::7.1@sdk:shared:partial$documents.adoc[tag=counters2]

[source,golang,indent=0]
----
include::example$documents.go[tag=counter-increment]
----

include::7.1@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.Binary()`.
This enables you to work with counters using `Get()` and `Replace()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://pkg.go.dev/github.com/couchbase/gocb/v2#BinaryCollection.Decrement[in the API docs].

// Expiry
include::7.1@sdk:shared:partial$documents.adoc[tag=expiration]


////
include::7.1@sdk:shared:partial$documents.adoc[tag=]


include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]
////
