= Durability & Failure
:description: Data durability refers to the fault tolerance and persistence of data in the face of software or hardware failure.
:page-topic-type: concept
:page-aliases: ROOT:failure-considerations,ROOT:durability,ROOT:enhanced-durability


[abstract]
{description}
Even the most reliable software and hardware might fail at some point, and along with the failures, introduce a chance of data loss.
Couchbase’s durability features include Synchronous Replication, and the possibility to use distributed, multi-document ACID transactions.
It is the responsibility of the development team and the software architect to evaluate the best choice for each use case.

include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=intro]

include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=syncrep]
Options for making changes to `numKvConnections` (kvEndpoints) for Durable Writes, change the `kv_pool_size` value. 
Increasing the number of reader and writer threads for Couchbase Server storage _may_ be advantageous: see the discussion on the xref:7.1@server:learn:buckets-memory-and-storage/storage.adoc#threading[Server storage page].
include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=syncrep3]

include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=older]

include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=performance]

// include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=txns]

// include::7.1@sdk:shared:partial$durability-replication-failure-considerations.adoc[tag=failover]

