= Health Check
:nav-title: Health Check
:page-topic-type: concept
:page-aliases: ROOT:health-check

[abstract]
Health Check provides ping() and diagnostics() tests for the health of the network and the cluster.

`Ping` and `diagnostics` methods, on the bucket and cluster objects respectively, can give us information about the current state of nodes, and their connections.

== Uses

'Ping` provides a raw JSON payload suitable for feeding into reactive log and aggregation components, including monitoring systems like _Splunk_, _ElasticSearch_, and _Nagios_.
It can also help keep connections alive if you are operating across an environment which aggressively closes down unused connections.

`Diagnostics` provides a strongly typed API for proactive, pull-based monitoring systems, such as:

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[Kubernetes Liveness and Readiness Probes via HTTP or CLI commands].
* https://docs.docker.com/engine/reference/builder/#healthcheck[Docker Health Check with CLI commands].
* http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html[AWS ELB through HTTP].

This API does not provide binary yes/no answers about the health of the cluster; rather it summarizes as much information as possible, for the application developer to assemble a complete, contextual view and come to a conclusion.

Note: `Ping` may reopen a connection, so is not without side-effects.
`Diagnostics` shows what the SDK _perceives_ as the current state of the network and services -- it is without side-effects, but may not be up to date.


== Ping

`Ping` _actively_ queries the status of the specified services,giving status and latency information for every node reachable.
In addition to its use as a monitoring tool, a regular `Ping` can be used in an environment which does not respect keep alive values for a connection.

The return value is a `PingResult` containing detail about the report including a `services` field.
The `services` field has `type` keys for each service available, such as `kv` and `n1ql`, and the value containing latency and status information.
The report also supports being exported to JSON for purposes such as logging.


[source,golang]
----
services := []gocb.ServiceType{gocb.ServiceTypeKeyValue, gocb.ServiceTypeQuery}
report, err := bucket.Ping(&gocb.PingOptions{ServiceTypes: services})
b, err := json.Marshal(report)
fmt.Printf("%s", string(b))

/*
{
  "version": 2,
  "sdk": "gocb/v2.0.0 gocbcore/v8.0.0",
  "id": "7cec10e3-3469-4c27-80b3-cca995f591c4",
  "services": {
    "kv": [
      {
        "id": "0xc000160d80",
        "remote": "10.112.194.103:11210",
        "state": "ok",
        "namespace": "<md>travel-sample<md>",
        "latency_us": 322298
      },
      {
        "id": "0xc000160c60",
        "remote": "10.112.194.101:11210",
        "state": "ok",
        "namespace": "<md>travel-sample<md>",
        "latency_us": 363870
      },
      {
        "id": "0xc000160cf0",
        "remote": "10.112.194.102:11210",
        "state": "timeout",
        "namespace": "<md>travel-sample<md>",
        "latency_us": 1240660
      }
    ],
    "query": [
      {
        "state": "ok",
        "latency_us": 4173543
      }
    ]
  }
}
*/
----


== Diagnostics

`Diagnostics` returns a list of the nodes that the SDK currently has (or had) a connection to, and the current status of the connection.
However this call _does not_ actively poll the nodes, reporting instead the state the last time it tried to access each node.
If you want the _current_ status, then use xref:#ping[Ping].

[source,javascript]
----
bucket.diagnostics((err, res) => {
    console.log(res)
})
/*
{
    "id":"0x10290d100","kv":[
        {
            "id":"0000000072b21d66",
            "last_activity_us":2363294,
            "local":"10.112.195.1:51473",
            "remote":"10.112.195.101:11210",
            "status":"connected"
        },
        {
            "id":"000000000ba84e5e",
            "last_activity_us":7369021,
            "local":"10.112.195.1:51486",
            "remote":"10.112.195.102:11210",
            "status":"connected"
        },
        {
            "id":"0000000077689398",
            "last_activity_us":4855640,
            "local":"10.112.195.1:51409",
            "remote":"10.112.195.103:11210",
            "status":"connected"
        }
    ],
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "version":1
}
*/
----

// above needs updating and localising (per SDK) for 3.0
