= Querying with N1QL
:nav-title: Querying with N1QL
:page-topic-type: concept
:page-aliases: ROOT:n1ql-query,

[abstract]
Parallel data management for complex queries over many records, using a familiar N1QL-like syntax.

include::partial$alpha-warning.adoc[]

The N1QL Query Language provides a familiar, SQL-like experience for querying documents stored in Couchbase.
You can xref:6.5@server:n1ql:n1ql-language-reference/index.adoc[read up on the language in our reference guide], 
but you probably just want to xref:howtos:n1ql-queries-with-sdk.adoc[dive into a practical example].

Below, we fill in some of the gaps between reference and rolling-up-your-sleeves practicality,
with discussion of a few areas of the Query service where more background knowledge will help you to better program your application.


== Indexes

The Couchbase query service makes use of xref:6.5@server:learn:services-and-indexes/indexes/indexes.adoc[_indexes_] in order to do its work.
Indexes replicate subsets of documents from data nodes over to index nodes, 
allowing specific data (for example, specific document properties) to be retrieved quickly, 
and to distribute load away from data nodes in xref:6.5@server:learn:services-and-indexes/services/services.adoc[MDS] topologies.

[IMPORTANT]
In order to make a bucket queryable, it must have at least one index defined.

You can define a _primary index_ on a bucket.
When a _primary_ index is defined you can issue non-covered (see below) queries on the bucket as well.
This includes using the `META` function in the queries.

[source,n1ql]
----
CREATE PRIMARY INDEX ON `users`
----

You can also define indexes over given document fields and then use those fields in the query:

[source,n1ql]
----
CREATE INDEX ix_name ON `users`(name);
CREATE INDEX ix_email ON `users`(email);
----

This would allow you to query the _users_ bucket regarding a document's `name` or `email` properties, thus:

[source,n1ql]
----
SELECT name, email FROM `users` WHERE name="Monty Python" OR email="monty@python.org";
----

Indexes help improve the performance of a query.
When an index includes the actual values of all the fields specified in the query, 
the index _covers_ the query, and eliminates the need to fetch the actual values from the Data Service.
An index, in this case, is called a _covering index_, and the query is called a _covered_ query.
For more information, see xref:6.5@server:n1ql:n1ql-language-reference/covering-indexes.adoc[Covering Indexes].

You can also create and define indexes in the SDK using:

[source,csharp]
----
var bucketManager = bucket.CreateManager();
await bucketManager.CreateN1qlPrimaryIndexAsync();
await bucketManager.CreateN1qlIndexAsync("index_name", new string[] { "name" })
await bucketManager.CreateN1qlIndexAsync("index_emai", new string[] { "email" })
----


== Index Building

Creating indexes on buckets with many existing documents can take a long time.
You can build indexes in the background, creating _deferred_ indexes.
The deferred indexes can be built together, rather than having to re-scan the entire bucket for each index.

[source,sql]
----
CREATE PRIMARY INDEX ON `users` WITH {"defer_build": true};
CREATE INDEX ix_name ON `users`(name) WITH {"defer_build": true};
CREATE INDEX ix_email ON `users`(email) WITH {"defer_build": true};
BUILD INDEX ON `users`(`#primary`, `ix_name`, `ix_email`);
----

The indexes are not built until the `BUILD INDEX` statement is executed.
At this point, the server scans all of the documents in the `users` bucket, 
and indexes it for all of the applicable indexes (in this case, those that have a `name` or `email` field).

Building deferred indexes can also be done via the SDK:

[source,csharp]
----
var bucketManager = bucket.CreateManager();
await bucketManager.CreateN1qlPrimaryIndexAsync(defer = true);
await bucketManager.CreateN1qlIndexAsync("ix_name", defer = true, new string[] { "name" });
await bucketManager.CreateN1qlIndexAsync("ix_email", defer = true, new string[] { "email" });
await bucketManager.BuildN1qlDeferredIndexesAsync();
await bucketManager.WatchN1qlIndexes(new List<string> { "ix_name", "ix_email", "#primary"}, TimeSpan.FromSeconds(2));
----


== Index Consistency

Because indexes are by design outside the data service, they are _eventually consistent_ with respect to changes to documents 
and, depending on how you issue the query, may at times not contain the most up-to-date information.
This may especially be the case when deployed in a write-heavy environment: changes may take some time to propagate over to the index nodes.

The asynchronous updating nature of xref:6.5@server:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Global Secondary Indexes (GSIs)] means that they can be very quick to query and do not require the additional overhead of index recaclculations at the time documents are modified.
N1QL queries are forwarded to the relevant indexes, and the queries are done based on indexed information, rather than the documents as they exist in the data service.

With default query options, the query service will rely on the current index state: 
the most up-to-date document versions are not retrieved, and only the indexed versions are queried.
This provides the best performance.
Only updates occurring with a small time frame may not yet have been indexed.
For cases where consistency is more important than performance, the `scan_consistency` property of a query may be set to `REQUEST_PLUS`.
ensuring that indexes are synchronized with the data service before querying.

The following options are available:

include::6.5@server:learn:page$services-and-indexes/indexes/index-replication.adoc[tag=scan_consistency]
////
* `not_bounded`: Executes the query immediately, without requiring any consistency for the query.
If index-maintenance is running behind, out-of-date results may be returned.
* `at_plus`: Executes the query, requiring indexes first to be updated to the timestamp of the last update.
If index-maintenance is running behind, the query waits for it to catch up.
* `request_plus`: Executes the query, requiring the indexes first to be updated to the timestamp of the current query-request.
If index-maintenance is running behind, the query waits for it to catch up.

For N1QL, the default consistency is `not_bounded`.
////
Consider the following snippet:

[source,csharp]
----

var randomNumber = new Random().Next(0, 10000000);

bucket.Upsert($"user:{randomNumber}", new {
    name = "Brass Doorknob",
    email = "brass.doorknob@juno.com",
    random = randomNumber
});

var query = new QueryRequest("SELECT name, email, random, META(default).id FROM default WHERE $1 IN name'")
    .AddPositionalParamter("Brass");

var result = bucket.Query<dynamic>(query);
----

The above query may not return the newly inserted document because it has not yet been indexed.
The query is issued immediately after document creation, and in this case the query engine may process the query before the index has been updated.

If the above code is modified to use _RequestPlus_, query processing will wait until all updates have been processed and recalculated into the index from the point in time the query was received:

[source,csharp]
----
var query = new QueryRequest("SELECT name, email, random, META(default).id FROM default WHERE $1 IN name'")
    .AddPositionalParamter("Brass")
    // If this line is removed, the latest 'random' field might not be present
    .ScanConsistency(ScanConsistency.RequestPlus);

var result = bucket.Query<dynamic>(query);
----

This gives the application developer more control over the balance between performance (latency) and consistency,
and allows optimization on a case-by-case basis.




////
** Awaiting LINQ updates **

== Building Statements with LINQ

[NOTE]
LINQ is a community project.
Although it works well with Couchbase, it is not part of the officially-supported product.

LINQ (Language Integrated Query), is a powerful way to guide you in building your statements: 
you obtain Type safety and auto completion of relevant methods and N1QL clauses. 
It implements https://msdn.microsoft.com/en-us/library/mt693024.aspx[Microsoft’s language integrated query extensions to the C# language], 
and is similar to other LINQ providers like Linq2SQL, Entity Framework and NHibernate. 
The difference is that it emits N1QL in place of SQL. 
If you have used any other LINQ provider, you will find its familiarity and consistency make it an easy transition.

_Linq2Couchbase_, the LINQ provider for the Couchbase .NET SDK, is a stand-alone project which depends on Couchbase .NET SDK 
and can be found on https://www.nuget.org/packages/linq2Couchbase[NuGet] -- and by using the NuGet package manager to include the dependency:

[source]
----
PM> Install-Package Linq2Couchbase
----

Once you have included the dependency, you can construct queries just like any other LINQ provider in a SQL-like fashion. Nearly all N1QL statements and functions are supported, for example:

* INNER, LEFT Outer, and Index JOINs
* Math and Date functions
* Filtering, projections and sorting
* Grouping and aggregations
* META keyword, NEST and UNNEST
* Etc.

In addition to N1QL language features, Linq2Coucbase supports ORM features like Change-tracking, and mapping of JSON fields to keys and other POCO properties. 
The provider’s core object is the `BucketContext`, which is a Unit of Work (UoW) type object for performing querying and mutations on a per request basis. 
////
