= Couchbase Go SDK 2.3
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase Go SDK 2.x is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 7.0).
The Go 2.x SDK also introduces improved error handling providing extra error information.


[.column]
[.content]
[source,golang,indent=0]
----
include::example$overview.go[tag=overview]
----


++++
</div>
++++

[.column]
====== {empty}

== Couchbase Go SDK 2.3

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
Try out our xref:sample-application.adoc[Travel Sample Application].
And take a look at the xref:howtos:working-with-collections.adoc[Collections feature].


[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)]; 
xref:howtos:n1ql-queries-with-sdk.adoc[Query]; 
xref:howtos:full-text-searching-with-sdk.adoc[Search]; 
xref:howtos:analytics-using-sdk.adoc[Analytics]; 
xref:howtos:view-queries-with-sdk.adoc[Views] -- 
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
https://pkg.go.dev/github.com/couchbase/gocb/v2[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
The Couchbase Go SDK 2.x is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area.
Version 2 of the Go SDK has added support for https://github.com/golang/go/wiki/Modules[Go Modules]. 
Error handling is improved with extra information.


[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to 
xref:project-docs:compatibility.adoc[compatibility tables]; 
xref:project-docs:sdk-release-notes.adoc[release notes]; 
xref:project-docs:get-involved.adoc[contribution guide]; and the 
xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 2.x API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/go-sdk/23[Couchbase forums^].
The Go SDK can be combined with many other projects in the broader Go ecosystem and beyond -- in the https://blog.couchbase.com/?s=Golang[Couchbase Blog^] there are several examples.

++++
</div>
++++
