= Setting Up Couchbase Go SDK
:description: Discover how to get up and running developing applications with the Couchbase Go SDK.
// using a virtual python installation]
:navtitle: Setting Up the Go SDK

[abstract]
{description}


A simple Go orientation intro for __non-__Go folk who are evaluating the Couchbase Go SDK.

[IMPORTANT]
.Is This Page for You?
====
This page is to help evaluate the Couchbase Go SDK, if Go is not where you spend the majority of your working day. 
It is aimed at Software Architects, QE folk, managers, and anyone else who needs to run through using the Go SDK without necessarily being comfortable with installing and developing with Go.
If this is not you, head back to the xref:overview.adoc[rest of the Couchbase Go SDK documentation].
====



* The https://go.dev/doc/tutorial/getting-started[Go Getting Started Guide] is an excellent introduction to installing and using the Go platform.

* Be aware that the Go SDK supports https://github.com/golang/go/wiki/Modules[Go Modules]. 
You can use `go get` to download the SDK:
+
TIP: `go get` only works if you have initialised a https://go.dev/blog/using-go-modules[Go module], and have a `go.mod` file in your working directory.
+
.Install the latest version of the Couchbase {sdk_dot_minor} Go SDK
[source,console,subs="+attributes"]
----
$ go get github.com/couchbase/gocb/v2@v{sdk_current_version}
----
