= Install and Start Using the Go SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
The Couchbase Go SDK allows you to connect to a Couchbase cluster from Go. It is a native Go library and uses the high-performance gocbcore to handle communicating to the cluster over Couchbase’s binary protocols

The Couchbase Go SDK 2.0 is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 as a xref:concept-docs:collections.adoc[developer preview]).
The Go 2.0 SDK introduces support for `context.Context` across all operations and improved error handling providing extra error information.


== Installing the SDK

Version 2 of the Go SDK has added support for https://github.com/golang/go/wiki/Modules[Go Modules]. If you are using Go 1.11.1+ with https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support[modules enabled and setup] then you can use `go get`:

[source,bash]
----
$ go get github.com/couchbase/gocb/v2@v2.0.0-beta.1
----

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
Currently we support using the Couchbase Go Client with Go releases 1.13 and 1.12.
Older versions may work, but are not supported.

Information on new features, fixes, and known issues -- as well as information on how to install older release versions -- is in the xref:1.6@go-sdk:project-docs:relnotes-go-sdk.html[release notes].

== Hello Couchbase

Now you have the Go client installed, open your favourite text editor and try out the following:

[source,golang,indent=0]
----
include::example$startusing.go[tag=connect]
----

Couchbase uses xref:6.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use more appropriate, restrictive settings -- but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

Connection to the cluster is initialized by:

[source,golang,indent=0]
----
include::example$startusing.go[tag=bucket]
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,golang,indent=0]
----
include::example$startusing.go[tag=named-bucket]
----

The 2.0 SDK is ready for the introduction of xref:#[Collections] in an upcoming release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we've used the `DefaultCollection`, which covers the whole Bucket.

[source,golang,indent=0]
----
include::example$startusing.go[tag=upsert-get]
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.

== Additional Resources

// The API reference is generated for each release and can be found http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0/[here].

// xref:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on https://github.com/couchbase/gocb[GitHub].
