= Install and Start Using the Go SDK with Couchbase Server
:description: Installing the Couchbase Go SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]


== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase Go SDK, and trying out the Hello World code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password, and bucket  -- and see the <<cloud-connections, Cloud section>>, below.

[source,go]
----
include::devguide:example$CloudConnect.java[tag=cloud-connect,indent=0]
----
--

Local Couchbase Server::
+ 
-- 
[source.try-it,go]
----
include::example$StartUsing.java[tags=**]
----

As well as the Go SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====

The Travel Sample bucket comes pre-loaded with the trial version of Couchbase Capella



== Installing the SDK

Version 2 of the Go SDK has added support for https://github.com/golang/go/wiki/Modules[Go Modules]. 
You can use `go get` to download the SDK:

[source,console]
----
$ go get github.com/couchbase/gocb/v2@v2.4.1
----

More details on installation can be found xref:project-docs:sdk-full-installation.adoc[here].

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.


== Step by Step

Now you have the Go client installed, open your preferred text editor and try out the following:

[source,golang,indent=0]
----
include::example$startusing.go[tag=connect]
----

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

Couchbase uses xref:7.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use more appropriate, restrictive settings -- but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

To access the KV (Key/Value) API or to query views, you need to open a `Bucket`:

[source,golang,indent=0]
----
include::example$startusing.go[tag=bucket]
----

If you installed the travel sample data bucket, replace _bucketName_ with _travel-sample_.


The {go-current-version} SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature in the latest release of the Couchbase Data Platform, Couchbase Server 7.0.
This brings complete support of Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Scope_.
Here we will use the `users` collection within the `tenant_agent_00` scope from `travel-sample` bucket as an example.

[source,golang,indent=0]
----
include::example$startusing.go[tag=collection]
----

The code shows how you would use a named collection and scope. A named or default collection will provide the same functionality as bucket-level operations did in previous versions of Couchbase Server.

The `DefaultCollection` must be used when connecting to a 6.6 cluster or earlier.

[source,golang,indent=0]
----
include::example$startusing.go[tag=upsert-get]
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.


== Next Steps

Now you're up and running, try one of the following:

// Should search and analytics be removed?

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] (CRUD) against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based N1QL language;
// * Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
// * A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The API reference is generated for each release and can be found https://pkg.go.dev/github.com/couchbase/gocb/v2[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 API (Go 1.x) to API 3 page (Go 2.x SDK)] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on https://github.com/couchbase/gocb[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/go-sdk/23[community forum] is a great source of help.
