= Start Using the Go SDK
:description: A quick start guide to get you up and running with Couchbase and the Go SDK.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:page-toclevels: 2
:page-pagination: next
:page-topic-type: tutorial

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

In this guide, you will learn:

* How to xref:connect[connect to Couchbase Capella or Couchbase Server].

* How to xref:add-and-retrieve-documents[add and retrieve Documents].

* How to xref:sql-lookup[lookup documents] with the {sqlpp_url}[{sqlpp} (formerly N1QL)] query language.

== Hello Couchbase

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
To connect to xref:cloud::index.adoc[Couchbase Capella], be sure to get the correct endpoint as well as user, password and bucket name.

[source,go]
----
include::devguide:example$go/cloud.go[tags=**]
----
--

Local Couchbase Server::
+ 
-- 
[source.try-it,go]
----
include::example$startusing.go[tags=**]
----

As well as the Go SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.

== Quick Installation

Version 2 of the Go SDK has added support for https://github.com/golang/go/wiki/Modules[Go Modules]. 
You can use `go get` to download the SDK:

[source,console]
----
$ go get github.com/couchbase/gocb/v2
----

More details on installation can be found xref:project-docs:sdk-full-installation.adoc[here].

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.

== Prerequisites

The following code samples assume:

[tabs]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically by the Capella free trial.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step by Step

Create an empty file named `main.go` and walk through adding code step-by-step.

Here are all the imports needed to run the sample code:

[source,golang]
----
include::devguide:example$go/cloud.go[tags=imports,indent=0]
----

Now, create an empty `main()` function.

[source,golang,indent=0]
----
func main() {
	// add code here...
}
----

In your `main()` function, add the following variables and update them accordingly:

[{tabs}]
====
Couchbase Capella::
+
--
[source,golang]
----
include::devguide:example$go/cloud.go[tag=connect-info,indent=0]
----
--

Local Couchbase Server::
+
--

[source,golang]
----
include::example$startusing.go[tag=connect-info,indent=0]
----
--
====

=== Connect

Connect to your cluster by calling the `Cluster.Connect()` function and pass it your connection details.
The basic connection details that you’ll need are given below -- for more background information, see xref:howtos:managing-connections.adoc[].

[tabs]
====
Couchbase Capella::
+
--
Couchbase Capella requires mandatory use of TLS (Transport Layer Security).
As of Go SDK version 2.5.0, the standard certificate required to connect to a Capella cluster is automatically included with no additional configuration.

[source,golang]
----
include::devguide:example$go/cloud.go[tag=connect,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 2.6 introduces a `wan-development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:go-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.

--
Local Couchbase Server::
+
--
[source,golang]
----
include::example$startusing.go[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost` as shown here. 
For production deployments, you will want to use a secure server, with `couchbases://`.
--
====

Following successful authentication, add this code snippet to access your `Bucket`:

[source,golang]
----
include::devguide:example$go/cloud.go[tag=bucket,indent=0]
----

=== Add and Retrieve Documents

The Go SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
_Collections_ allow documents to be grouped by purpose or theme, according to a specified _Scope_.

Here we refer to the `users` collection within the `tenant_agent_00` scope from the Travel Sample bucket as an example, but you may replace this with your own data.

[source,golang]
----
include::devguide:example$go/cloud.go[tag=collection,indent=0]
----

[IMPORTANT]
====
.For Local Couchbase Server only
The `DefaultCollection` must be used when connecting to a 6.6 cluster or earlier -- see comment in the code snippet above.
====

The code shows how you would use a named collection and scope. 
A named or default collection will provide the same functionality as bucket-level operations did in previous versions of Couchbase Server.

xref:howtos:kv-operations.adoc[Data operations], such as storing and retrieving documents, can be done using `Collection.Upsert()` and `Collection.Get()`.

Add the following code to create a new document:

[source,golang]
----
include::devguide:example$go/cloud.go[tag=upsert,indent=0]
----

Now, let's retrieve it using a key-value (data) operation.

[source,golang]
----
include::devguide:example$go/cloud.go[tag=get,indent=0]
----

=== {sqlpp} Lookup

Couchbase {sqlpp} queries are performed by invoking `Cluster.Query()` or `Scope.Query`.

Cluster level queries require you to specify the fully qualified keyspace each time (e.g. `travel-sample.inventory.airline`).
However, with a Scope level query you only need to specify the Collection name -- which in this case is `airline`:

[source,golang]
----
include::devguide:example$go/cloud.go[tag=query,indent=0]
----

You can learn more about {sqlpp} queries on the xref:howtos:n1ql-queries-with-sdk.adoc[] page.

=== Execute!

Now we can run our code using the following command:

[source,console]
----
$ go run main.go
----

The results you should expect are as follows:

[source,console]
----
User: {Jade jade@test-email.com [Swimming Rowing]}
map[airline:map[callsign:MILE-AIR country:United States iata:Q5 icao:MLA id:10 name:40-Mile Air type:airline]]
----

== Next Steps

Now you're up and running, try one of the following:

// Should search and analytics be removed?

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] (CRUD) against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language;
// * Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
// * A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The API reference is generated for each release and can be found https://pkg.go.dev/github.com/couchbase/gocb/v2[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 API (Go 1.x) to API 3 page (Go 2.x SDK)] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on https://github.com/couchbase/gocb[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/go-sdk/23[community forum] is a great source of help.
