= Install and Start Using the Go SDK with Couchbase Server
:description: Installing the Couchbase Go SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
The Couchbase Go SDK allows you to connect to a Couchbase cluster from Go.
It is a native Go library and uses the high-performance gocbcore to handle communicating to the cluster over Couchbase’s binary protocols

The Couchbase Go SDK 2.x is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, 
and adding support for future Couchbase Server features like Collections and Scopes 
(available in Couchbase Server 6.5 as a xref:concept-docs:collections.adoc[developer preview]).
The Go 2.0 SDK also introduces improved error handling providing extra error information.

If you're upgrading your application from Couchbase Go SDK 1.x, please read our xref:project-docs:migrating-sdk-code-to-3.n.adoc[Migration Guide].


== Installing the SDK

Version 2 of the Go SDK has added support for https://github.com/golang/go/wiki/Modules[Go Modules]. 
You can use `go get` to download the SDK:

[source,console]
----
$ go get github.com/couchbase/gocb/v2@v2.2.4
----

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
Currently we support using the Couchbase Go Client with Go releases 1.13 and up.
Older versions may work, but are not supported.

Information on new features, fixes, and known issues -- as well as information on how to install older release versions -- is in the xref:1.6@go-sdk:project-docs:relnotes-go-sdk.html[release notes].

== Hello Couchbase

Now you have the Go client installed, open your favourite text editor and try out the following:

[source,golang,indent=0]
----
include::example$startusing.go[tag=connect]
----

If you are connecting to Couchbase Cloud rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

Couchbase uses xref:6.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use more appropriate, restrictive settings -- but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

To access the KV (Key/Value) API or to query views, you need to open a `Bucket`:

[source,golang,indent=0]
----
include::example$startusing.go[tag=bucket]
----

If you installed the travel sample data bucket, replace _bucket-name_ with _travel-sample_.


The 2.0 SDK is ready for the introduction of xref:#[Collections] in an upcoming release of the Couchbase Data Platform.
Couchbase Server 6.5 brings a limited xref:6.5@server:developer-preview:preview-mode.adoc[Developer Preview] of Collections, 
allowing Documents to be grouped by purpose or theme, according to a specified _Collection_. 

[source,golang,indent=0]
----
include::example$startusing.go[tag=collection]
----

The commented-out code shows how you would use a named collection and scope.
However, in this case we've used the `DefaultCollection`, which provides the same functionality as bucket-level operations did in previous versions of Couchbase Server.
The `DefaultCollection` must be used when connecting to a 6.6 cluster or earlier.

[source,golang,indent=0]
----
include::example$startusing.go[tag=upsert-get]
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.


== Cloud Connections

For developing on Couchbase Cloud, 
try the https://github.com/couchbase/docs-sdk-go/blob/release/2.1/modules/devguide/examples/go/cloud.go[Cloud-based Hello World program].

If you are not working from the same _Availability Zone_ as your Couchbase Cloud, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments], 
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements], 
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and can be found https://pkg.go.dev/github.com/couchbase/gocb/v2[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on https://github.com/couchbase/gocb[GitHub].
