= Install and Start Using the Go SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase Go SDK allows you to connect to a Couchbase cluster from Go. It is a native Go library and uses the high-performance gocbcore to handle communicating to the cluster over Couchbase’s binary protocols

WARNING: These pages cover the first _Developer Preview_ of the Couchbase Golang SDK 2.0 (DP1).
As such they are likely to change without notice.
The DP1 code _should not_ be used in production.

== Installing the SDK

You can install the SDK via `go get`, note that the _Developer Preview_ is not available via `gopkg`.

[source,go]
----
$ go get github.com/couchbase/gocb
----

Information on new features, fixes, and known issues -- as well as information on how to install older release versions -- is in the xref::project-docs:relnotes-go-sdk.html[release notes].

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
Currently we support using the Couchbase Go Client with Go releases 1.12 and 1.11.
Older versions may work, but are not supported.

== Hello Couchbase

Now you have the Go client installed, open your favourite text editor and try out the following:

[source,golang]
----
import "gopkg.in/couchbase/gocb.v2"
...

opts := gocb.ClusterOptions{
    Authenticator: gocb.PasswordAuthenticator{
        "Administrator",
        "password",
    }
}
cluster, _ := gocb.NewCluster("10.112.180.101", opts)
----

Couchbase uses xref:6.5@server:learn/security:roles.adoc[Role Based Access Control (RBAC) to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:3.0dp1@go-sdk:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

Connection to the cluster is initialized by:

[source,golang]
----
// get a bucket reference
bucket, _ := cluster.Bucket("bucket-name", &gocb.BucketOptions{});
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,golang]
----
// get a collection reference
collection, _ := bucket.DefaultCollection(&gocb.CollectionOptions{})
// for a named collection and scope
// myCollection, err := bucket.Scope("my-scope").Collection("my-collection", &gocb.CollectionOptions{})
----

The 2.0 SDK is ready for the introduction of xref:#[Collections] in an upcoming release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we've used the `DefaultCollection`, which covers the whole Bucket.

[source,golang]
----
// Upsert Document
upsertResult, _ := col.Upsert("my-document", map[string]string{"name": "mike"}, &gocb.UpsertOptions{})

 // Get Document
getResult, _ := collection.Get("my-document", &gocb.GetOptions{})
----

KV Operations are described in detail on the xref:net-sdk:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page -- or first see a complete worked example of 
using the Couchbase Go client, our xref:3.0dp1@sample-application.adoc[Travel Sample Application].

== Additional Resources

The API reference is generated for each release and can be found xref:http://docs.couchbase.com/sdk-api/couchbase-go-client-3.0.0dp1/[here].

xref::project-docs:migrating-sdk-code-to-2.n.adoc[The Migrating from SDK1 to 2 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on xref:https://github.com/couchbase/couchbase-go-client[GitHub].
