= Start Using the Go SDK
:description: A quick start guide to get you up and running with Couchbase and the Go SDK.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:page-toclevels: 2
:forum-link: https://www.couchbase.com/forums/c/go-sdk/23
:page-partial:

// Note to editors
// 
// This page pulls in content from
// https://github.com/couchbase/docs-sdk-common/blob/release/8.0.1/modules/shared/partials/start-using-sdk.adoc
//
// and code samples from
// https://github.com/couchbase/docs-sdk-go/tree/release/2.12/modules/devguide/examples/go
// 
// It can be seen built at
// https://docs.couchbase.com/go-sdk/2.12/hello-world/start-using-sdk.html



[abstract]
{description}

Couchbase has a simple interface for creating and modifying records in a document, 
based upon the *collection* into which the documents are organized.
You can read more about data modeling <<data-modeling,below>>, 
but first let's look at those data operations, and installing the {name-sdk}.

// remember to add a nomenclature note to the next version of this page for LCB.

[source,golang]
----
include::devguide:example$go/kv-durability-enhanced_test.go[indent=0,tag=durability]
----

`upsert` inserts (creates) the document if it does not exist, or replaces it if it does.
We'll explore creating and retrieving data records in more detail <<create-read-update-delete,below>>,
after walking through a quick installation.


== Before You Start

Couchbase Capella, our Database-as-a-Service, lets you get on with what matters, while we take care of the administration for you.
Alternately, if you need to control every aspect of deployment -- 
or just want to run the Server in a VM on your laptop -- 
there are several self-managed options available:

[tabs]
==== 
Couchbase Capella::
+
--
If you haven't already got a cluster set up, the easiest route is to https://cloud.couchbase.com/sign-up[sign up to Couchbase Capella and deploy a free tier cluster^], 
then come back to this page.
Make a note of the xref:cloud:get-started:connect.adoc[endpoint] to connect to, 
and remember the credentials for the user that you set up.
--

Self-Managed Couchbase Server::
+
--
Install Couchbase Server locally, or in your private Cloud:

* xref:{version-server}@server:install:get-started.adoc[Deployment overview]
* xref:{version-server}@server:install:getting-started-docker.adoc[Docker Install]
* xref:operator::overview.adoc[Couchbase Autonomous Operator]
** xref:operator::install-kubernetes.adoc[Kubernetes]
** xref:operator::install-openshift.adoc[Openshift]
* xref:{version-server}server:cloud:couchbase-cloud-deployment.adoc[Cloud Marketplace]:
** xref:{version-server}@server:cloud:couchbase-aws-marketplace.adoc[AWS Marketplace]
** xref:{version-server}@server:cloud:couchbase-azure-marketplace.adoc[Azure Marketplace]
** xref:{version-server}@server:cloud:couchbase-gcp-cloud-launcher.adoc[GCP Marketplace]

For the example code below to run, you'll need the username and password of the Administrator user that you create, and the IP address of at least one of the nodes of the cluster.
--
====


// Script the docs!
// Can any of the SDK installations be scripted?

=== Prerequisites

In line with the https://golang.org/doc/devel/release.html#policy[Golang project], we support both the current, and the previous, versions of Go.
At time of writing (February 2026), this is 1.25 and 1.26.

The code examples also assume:

[tabs]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically when deploying a Capella free tier cluster.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to cluster resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In production, Couchbase strongly recommends setting up users with more granular access roles as a best practice for data security.
--

Self-Managed Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role-Based Access Control (RBAC)] to control access to cluster resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
In production, Couchbase strongly recommends setting up users with more granular access roles as a best practice for data security.
--
====


== Installation

// tag::quick-install[]
You can use `go get` to download the SDK:

[source,console]
----
$ go get github.com/couchbase/gocb/v2
----

More details on installation can be found xref:project-docs:sdk-full-installation.adoc[here].
// end::quick-install[]


=== IDE Plugins

To make development easier, Couchbase plugins are available for VSCode and the IntelliJ family of IDEs and editors.
For links and more information on these and other integrations across the {name_platform} ecosystem, 
check out the xref:project-docs:third-party-integrations.adoc[] page.


=== Grab the Code

If you're all set up and in a real hurry, just grab this code sample and add in your Capella details.

.Complete Hello World code sample [*Click to open or collapse the listing*]
[%collapsible]
====
....
include::devguide:example$go/cloud_test.go[tags=**]
....
====

Otherwise, read on as we introduce the CRUD API and connection to Capella or self-managed Couchbase Server.

TIP: There's a *View* link to the complete sample code on GitHub above each of the snippets on these SDK pages, and a *Copy* icon to grab just the snippet shown.


== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,golang]
----
include::devguide:example$go/cloud_test.go[tag=connect,indent=0]
----

Note, the client certificate for connecting to a Capella cluster is included in the SDK installation.
--

Self-Managed Couchbase Server::
+ 
-- 
[source,golang]
----
include::devguide:example$go/startusing_test.go[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost` as shown here. 
For production deployments, you will want to use a TLS, enabled with `couchbases://`.
--

Cloud Native Gateway (CNG)::
+
--
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string --
currently only compatible with recent versions of xref:operator:ROOT:concept-cloud-native-gateway.adoc[Couchbase Autonomous Operator]:

[source,golang]
----
	cluster, err := gocb.Connect("couchbase2://"+connectionString, gocb.ClusterOptions{
		Authenticator: gocb.PasswordAuthenticator{
			Username: username,
			Password: password,
		},
----

Read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.

--
====


For a deeper look at connection options, read xref:howtos:managing-connections.adoc[].

TIP: The connection code for getting started uses the Administrator password that you were given during set up.
In any production app you should create a role restricted to the permissions needed for your app -- 
more on this in xref:concept-docs:best-practices.adoc#roles-and-rbac[the Security documentation].

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
The `wan-development` Configuration Profile, provides pre-configured timeout settings suitable for working in high latency environments.
See xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:go-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.



=== Opening a Bucket

Following successful authentication, add this code snippet to access your `Bucket`:

[source,golang]
----
include::devguide:example$go/cloud_test.go[tag=bucket,indent=0]
----


`WaitUntilReady` is an optional call,
but it is good practice to use it.
Opening resources such as buckets is asynchronous --
that is, the `cluster.Bucket` call returns immediately and proceeds in the background.
`WaitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first key-value (KV) operation on the bucket will wait for it to be ready.

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope* -- see data modeling, <<data-modeling,below>>.
Here we will use the `airport` collection within the `inventory` scope from `travel-sample` bucket as an example.

Here we refer to the `users` collection within the `tenant_agent_00` scope from the Travel Sample bucket as an example, but you may replace this with your own data.

[source,golang]
----
include::devguide:example$go/cloud_test.go[tag=collection,indent=0]
----



== Create, Read, Update, Delete

Couchbase documents are organized into buckets, scopes, and collections.
https://en.wikipedia.org/wiki/CRUD[CRUD operations^] -- Create, Read, Update, Delete -- can be performed upon documents in a collection.


=== Insert (Create) and Upsert

`insert` and `upsert` will both create a new document.
The difference between the two is that if a document with that key already exists, the `insert` operation will fail, throwing `ErrDocumentExists` --
while the `upsert` operation will succeed, replacing the content.

Add the following code to create a new document:

[source,golang]
----
include::devguide:example$go/cloud_test.go[tag=upsert,indent=0]
----


=== Get (Read)

The `get` method reads a document from a collection.
If the collection does not have a document with this ID, the `get` method also throws `ErrDocumentNotFound`.

[source,golang]
----
include::devguide:example$go/cloud_test.go[tag=get,indent=0]
----


=== Replace (Update) and Optimistic Locking

When you replace a document, it's usually good practice to use xref:howtos:kv-operations.adoc#optimistic-locking[optimistic locking].
Otherwise, changes might get lost if two people change the same document at the same time.

Setting a Compare and Swap (CAS) value is a form of optimistic locking -- dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of ``0``.

[source,go,indent=0]
----
include::devguide:example$go/kv-crud_test.go[tag=replacecas]
----

Typically we would want to use CAS for something more meaningful like performing a `Get`, modifying the result and updating the document.
By using the CAS value we know that if anyone else modified this document and updated it before our update then ours will error.

[source,go,indent=0]
----
include::devguide:example$go/kv-crud_test.go[tag=update]
----


=== Remove (Delete)

The remove method deletes a document from a collection:


When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

[source,go,indent=0]
----
include::devguide:example$go/kv-crud_test.go[tag=remove]
----

////
=== Execute!

Now we can run our code using the following command:

[source,console]
----
$ go run main.go
----

The results you should expect are as follows:

[source,console]
----
User: {Jade jade@test-email.com [Swimming Rowing]}
map[airline:map[callsign:MILE-AIR country:United States iata:Q5 icao:MLA id:10 name:40-Mile Air type:airline]]
----
////

== Data Modeling

Documents are organized into collections -- collections of documents that belong together.
You get to decide what it means to "belong." 
Developers usually put documents of the same type in the same collection.

For example, imagine you have two types of documents: customers and invoices. 
You could put the customer documents in a collection called `customers`, and the invoice documents in a collection called `invoices`.

Each document belongs to exactly one collection. 
A document's ID is unique _within_ the collection.

Different scopes can hold collections with different names. 
There is no relationship between collections in different scopes.
Each collection belongs to just one scope and
a collection's name is unique within the scope.


More details can be found on the xref:concept-docs:data-model.adoc[Data Model page].
// The xref:student-record-developer-tutorial.adoc[Student Records Tutorial] gives an introduction to data modeling in a document database alongside using the {name-sdk}.



== What Next?

=== Help and Troubleshooting

* xref:howtos:troubleshooting-cloud-connections.adoc[Troubleshooting common network problems].
* {forum-link}[Help forum].
* https://discord.com/channels/915294689681362954/1217642561645318194[Discord channel].
* Read the xref:howtos:error-handling.adoc[error handling page].
* xref:cloud:get-started:capella-iq/get-started-with-iq.adoc#generate-sdk-code-preview[Get help from Couchbase iQ].

=== Next Steps

* Take a look at the xref:hello-world:sample-application.adoc[].
* xref:concept-docs:data-durability-acid-transactions.adoc[Learn more about the Data Service].
* xref:concept-docs:querying-your-data.adoc[Discover {sqlpp}] -- our SQL-family querying language.
// * Explore some of the xref:project-docs:third-party-integrations.adoc[third party integrations] with Couchbase and the {name_platform} SDK, across the {name_platform} ecosystem.

=== Additional Resources

* The API reference is generated for each release and can be found https://pkg.go.dev/github.com/couchbase/gocb/v2[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

* Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on https://github.com/couchbase/gocb[GitHub].
