= Install and Start Using the Go SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase Go SDK allows you to connect to a Couchbase cluster from Go. It is a native Go library and uses the high-performance gocbcore to handle communicating to the cluster over Couchbase’s binary protocols

WARNING: These pages cover the first _Developer Preview_ of the Couchbase .NET SDK 3.0 (DP1).
As such they are likely to change without notice.
The DP1 code _should not_ be used in production.

== Installing the SDK

You can install the SDK via go get

[source,go]
----
$ go get gopkg.in/couchbase/gocb.v3
----

Information on new features, fixes, and known issues -- as well as information on how to install older release versions -- is in the xref:https://docs.couchbase.com/go-sdk/1.5/relnotes-go-sdk.html[release notes].


== Hello Couchbase

/localise to Go!

Now you have the .NET client installed grab the code from link:href://devguideexamples or open a fresh project in VS Code and try out the following:

[source,csharp]
----
var config = new Configuration
{
    Servers = new List<Uri> {new Uri("http://10.112.180.101:8091")},
    UserName = "username",
    Password = "password"
};
----

Couchbase uses xref:6.5@server:learn/security:roles.adoc[Role Based Access Control (RBAC) to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:3.0dp1@net-sdk:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.


// initialize cluster

[source,csharp]
----
var cluster = new Cluster();
await cluster.Initialize(config)

// possible alternative (doesn't currently work)
//var cluster = await Cluster.Connect(config);
----

Connection to the cluster is initialized by
// to be filled in when above is clarified.

// Mike: ideal is for socket / http client init during cluster connect, but we typically require a bucket, so may be delated until a bucket instance is requested, like it is in 2.x.

[source,csharp]
----
// get a bucket reference
var bucket = await cluster.Bucket("bucket-name");
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,csharp]
----
// get a collection reference
var collection = await bucket.DefaultCollection;
var myCollection = bucket.Scope("my-collection");
----

The 3.0 SDK is ready for the introduction of xref:#[Collections] in Cheshire Cat, the next release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we will use the `DefaultCollection`, which covers the whole Bucket.

[source,csharp]
----
// upsert document
var upsertResult = await collection.Binary.Upsert("my-document", new {name = "mike"});

// get document
var getResult = await collection.Binary.Get("my-document");
----

The `Binary` service is a wrapper for the core Key Value (KV) database service.
KV Operations are described in detail on the xref:net-sdk:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page -- or first see a complete worked example of using the Couchbase .NET client, our xref:3.0dp1@sample-application.adoc[Travel Sample Application].

== Additional Resources

The API reference is generated for each release and can be found xref:http://docs.couchbase.com/sdk-api/couchbase-go-client-3.0.0dp1/[here].

xref:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Go SDK.
The Go SDK source code is available on xref:https://github.com/couchbase/couchbase-go-client[GitHub].
