name: Build Code Samples 

on:
  push:
    branches: [release/2.2]
    paths:
      - 'modules/test/*'
      - 'modules/Makefile'
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
  pull_request:
    branches: [release/2.2]
    paths:
      - 'modules/test/*'
      - 'modules/Makefile'
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
env:
  GO_VERSION: 1.13

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory:
        ./modules

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build code samples
        run: make build
        working-directory: ${{ env.working-directory }}
