name: Test Code Samples (Dev)

on:
  push:
    branches: [ "release/2.*" ]

env:
  REGISTRY: registry.gitlab.com/cb-vanilla/server
  CB_EDITION: 7.0.0
  CB_BUILD: 5295

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true' # cancel previous workflow runs when pushing a new commit.
          paths: '["**/Makefile", "modules/test/**", "**/*.go", "**/*.mod", "**/*.sum"]'

  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      working-directory:
        ./modules

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PSWD }}

      - name: Build Couchbase Docker image
        run: CB_EDITION=${{ env.REGISTRY }}:${{ env.CB_EDITION }} CB_BUILD=${{ env.CB_BUILD }}  make cb-build    
        working-directory: ${{ env.working-directory }}

      - name: Run Couchbase Server+SDK container
        run: make cb-start
        working-directory: ${{ env.working-directory }}

      - name: Test code samples
        run: make tests 
        working-directory: ${{ env.working-directory }}
      
      - name: Cleanup
        run: make cb-stop
        working-directory: ${{ env.working-directory }}

      - name: Notify slack on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ":octocat: Go SDK Automation Failure"
          text: ":no_entry: Oh noes! The commit has broken the build...please verify :paddlin:"
          fields: repo,workflow,job,commit,author
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
