name: Run Code Examples

on:
  push:
    branches: [release/2.2]
    paths:
    - "/modules/**/*.bats"
    - "/modules/**/*.go"
  pull_request:
    branches: [release/2.2]
    paths:
    - "/modules/**/*.bats"
    - "/modules/**/*.go"
env:
  CB_IMAGE: build-docker.couchbase.com/smallcb-sdks
  CB_VERSION: cb7-sdk3-ub20

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      - name: Run Couchbase Server
        run: cd modules && CB_IMAGE=${{ env.CB_IMAGE }} CB_VERSION=${{ env.CB_VERSION }} make cb-run

      - name: Test code samples
        run: make tests
